import type { LessonContent } from '../types';

const lessonA1004: LessonContent = {
  level: 'a1',
  number: 4,
  title: 'Vocales cortas y largas',
  subtitle: 'Aprende a distinguir de oído las vocales cortas y largas, el sonido de la doble O y cuándo la terminación ED suena o es muda.',
  videoTitle: 'Vocales cortas y largas',
  videoDescription: 'En este video practicarás los pares de vocales cortas y largas, la doble O y la terminación ED.',
  objective: 'Al terminar, podrás distinguir de oído palabras como man y mane, bit y bite, y saber cuándo la ED de un verbo suena o es muda.',
  exercises: [
    {
      type: 'listening-choice',
      title: 'Escucha y elige la palabra',
      instructions: 'Escucha la palabra y toca la que escuchaste. Las dos opciones se diferencian por una vocal corta o larga.',
      questions: [
        {
          id: 1,
          audioText: 'man',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'man', text: 'man' },
            { id: 'mane', text: 'mane' },
          ],
          correctOptionIds: ['man'],
          explanation: 'man tiene vocal corta (sonido "ah"). mane tiene vocal larga (sonido "ei").',
        },
        {
          id: 2,
          audioText: 'rain',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'ran', text: 'ran' },
            { id: 'rain', text: 'rain' },
          ],
          correctOptionIds: ['rain'],
          explanation: 'rain tiene vocal larga (sonido "ei"). ran tiene vocal corta (sonido "ah").',
        },
        {
          id: 3,
          audioText: 'cane',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'cane', text: 'cane' },
            { id: 'can', text: 'can' },
          ],
          correctOptionIds: ['cane'],
          explanation: 'cane tiene vocal larga (sonido "ei"). can tiene vocal corta.',
        },
        {
          id: 4,
          audioText: 'beat',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'bet', text: 'bet' },
            { id: 'beat', text: 'beat' },
          ],
          correctOptionIds: ['beat'],
          explanation: 'beat tiene vocal larga (sonido "i"). bet tiene vocal corta (sonido "eh").',
        },
        {
          id: 5,
          audioText: 'set',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'set', text: 'set' },
            { id: 'seat', text: 'seat' },
          ],
          correctOptionIds: ['set'],
          explanation: 'set tiene vocal corta (sonido "eh"). seat tiene vocal larga (sonido "i").',
        },
        {
          id: 6,
          audioText: 'meet',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'met', text: 'met' },
            { id: 'meet', text: 'meet' },
          ],
          correctOptionIds: ['meet'],
          explanation: 'meet tiene vocal larga (sonido "i"). met tiene vocal corta (sonido "eh").',
        },
        {
          id: 7,
          audioText: 'bite',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'bite', text: 'bite' },
            { id: 'bit', text: 'bit' },
          ],
          correctOptionIds: ['bite'],
          explanation: 'bite tiene vocal larga (sonido "ai"). bit tiene vocal corta (sonido "i").',
        },
        {
          id: 8,
          audioText: 'sit',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'site', text: 'site' },
            { id: 'sit', text: 'sit' },
          ],
          correctOptionIds: ['sit'],
          explanation: 'sit tiene vocal corta. site tiene vocal larga (sonido "ai").',
        },
        {
          id: 9,
          audioText: 'kite',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'kite', text: 'kite' },
            { id: 'kit', text: 'kit' },
          ],
          correctOptionIds: ['kite'],
          explanation: 'kite tiene vocal larga (sonido "ai"). kit tiene vocal corta.',
        },
        {
          id: 10,
          audioText: 'hope',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'hop', text: 'hop' },
            { id: 'hope', text: 'hope' },
          ],
          correctOptionIds: ['hope'],
          explanation: 'hope tiene vocal larga (sonido "ou"). hop tiene vocal corta (sonido "oh").',
        },
        {
          id: 11,
          audioText: 'got',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'got', text: 'got' },
            { id: 'goat', text: 'goat' },
          ],
          correctOptionIds: ['got'],
          explanation: 'got tiene vocal corta (sonido "oh"). goat tiene vocal larga (sonido "ou").',
        },
        {
          id: 12,
          audioText: 'note',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'not', text: 'not' },
            { id: 'note', text: 'note' },
          ],
          correctOptionIds: ['note'],
          explanation: 'note tiene vocal larga (sonido "ou"). not tiene vocal corta.',
        },
        {
          id: 13,
          audioText: 'cut',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'cut', text: 'cut' },
            { id: 'cute', text: 'cute' },
          ],
          correctOptionIds: ['cut'],
          explanation: 'cut tiene vocal corta. cute tiene vocal larga (sonido "iu").',
        },
        {
          id: 14,
          audioText: 'duke',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'duck', text: 'duck' },
            { id: 'duke', text: 'duke' },
          ],
          correctOptionIds: ['duke'],
          explanation: 'duke tiene vocal larga (sonido "iu"). duck tiene vocal corta.',
        },
        {
          id: 15,
          audioText: 'huge',
          language: 'en',
          prompt: '¿Qué palabra escuchaste?',
          options: [
            { id: 'huge', text: 'huge' },
            { id: 'hug', text: 'hug' },
          ],
          correctOptionIds: ['huge'],
          explanation: 'huge tiene vocal larga (sonido "iu"). hug tiene vocal corta.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Vocal corta o larga?',
      instructions: 'Escucha la palabra y decide si su vocal es corta o larga.',
      questions: [
        {
          id: 16,
          audioText: 'hat',
          language: 'en',
          prompt: '¿La vocal es corta o larga?',
          options: [
            { id: 'short', text: 'Vocal corta' },
            { id: 'long', text: 'Vocal larga' },
          ],
          correctOptionIds: ['short'],
          explanation: 'hat tiene vocal corta (sonido "ah").',
        },
        {
          id: 17,
          audioText: 'hate',
          language: 'en',
          prompt: '¿La vocal es corta o larga?',
          options: [
            { id: 'short', text: 'Vocal corta' },
            { id: 'long', text: 'Vocal larga' },
          ],
          correctOptionIds: ['long'],
          explanation: 'hate tiene vocal larga: la A suena "ei".',
        },
        {
          id: 18,
          audioText: 'fit',
          language: 'en',
          prompt: '¿La vocal es corta o larga?',
          options: [
            { id: 'short', text: 'Vocal corta' },
            { id: 'long', text: 'Vocal larga' },
          ],
          correctOptionIds: ['short'],
          explanation: 'fit tiene vocal corta.',
        },
        {
          id: 19,
          audioText: 'fight',
          language: 'en',
          prompt: '¿La vocal es corta o larga?',
          options: [
            { id: 'short', text: 'Vocal corta' },
            { id: 'long', text: 'Vocal larga' },
          ],
          correctOptionIds: ['long'],
          explanation: 'fight tiene vocal larga: la I suena "ai".',
        },
        {
          id: 20,
          audioText: 'sell',
          language: 'en',
          prompt: '¿La vocal es corta o larga?',
          options: [
            { id: 'short', text: 'Vocal corta' },
            { id: 'long', text: 'Vocal larga' },
          ],
          correctOptionIds: ['short'],
          explanation: 'sell tiene vocal corta (sonido "eh").',
        },
        {
          id: 21,
          audioText: 'seal',
          language: 'en',
          prompt: '¿La vocal es corta o larga?',
          options: [
            { id: 'short', text: 'Vocal corta' },
            { id: 'long', text: 'Vocal larga' },
          ],
          correctOptionIds: ['long'],
          explanation: 'seal tiene vocal larga: suena "i".',
        },
        {
          id: 22,
          audioText: 'not',
          language: 'en',
          prompt: '¿La vocal es corta o larga?',
          options: [
            { id: 'short', text: 'Vocal corta' },
            { id: 'long', text: 'Vocal larga' },
          ],
          correctOptionIds: ['short'],
          explanation: 'not tiene vocal corta (sonido "oh").',
        },
        {
          id: 23,
          audioText: 'note',
          language: 'en',
          prompt: '¿La vocal es corta o larga?',
          options: [
            { id: 'short', text: 'Vocal corta' },
            { id: 'long', text: 'Vocal larga' },
          ],
          correctOptionIds: ['long'],
          explanation: 'note tiene vocal larga: la O suena "ou".',
        },
        {
          id: 24,
          audioText: 'luck',
          language: 'en',
          prompt: '¿La vocal es corta o larga?',
          options: [
            { id: 'short', text: 'Vocal corta' },
            { id: 'long', text: 'Vocal larga' },
          ],
          correctOptionIds: ['short'],
          explanation: 'luck tiene vocal corta.',
        },
        {
          id: 25,
          audioText: 'Luke',
          language: 'en',
          prompt: '¿La vocal es corta o larga?',
          options: [
            { id: 'short', text: 'Vocal corta' },
            { id: 'long', text: 'Vocal larga' },
          ],
          correctOptionIds: ['long'],
          explanation: 'Luke tiene vocal larga: la U suena "iu".',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: 'El sonido de la doble O',
      instructions: 'Escucha la palabra. La doble O puede sonar como en hoop (sonido U) o como en floor (sonido O).',
      questions: [
        {
          id: 26,
          audioText: 'moon',
          language: 'en',
          prompt: '¿Qué sonido escuchaste?',
          options: [
            { id: 'u', text: 'Sonido U (como en hoop)' },
            { id: 'o', text: 'Sonido O (como en floor)' },
          ],
          correctOptionIds: ['u'],
          explanation: 'moon suena con sonido U, como hoop.',
        },
        {
          id: 27,
          audioText: 'floor',
          language: 'en',
          prompt: '¿Qué sonido escuchaste?',
          options: [
            { id: 'u', text: 'Sonido U (como en hoop)' },
            { id: 'o', text: 'Sonido O (como en floor)' },
          ],
          correctOptionIds: ['o'],
          explanation: 'floor suena con sonido O, como door.',
        },
        {
          id: 28,
          audioText: 'zoo',
          language: 'en',
          prompt: '¿Qué sonido escuchaste?',
          options: [
            { id: 'u', text: 'Sonido U (como en hoop)' },
            { id: 'o', text: 'Sonido O (como en floor)' },
          ],
          correctOptionIds: ['u'],
          explanation: 'zoo suena con sonido U, como hoop.',
        },
        {
          id: 29,
          audioText: 'door',
          language: 'en',
          prompt: '¿Qué sonido escuchaste?',
          options: [
            { id: 'u', text: 'Sonido U (como en hoop)' },
            { id: 'o', text: 'Sonido O (como en floor)' },
          ],
          correctOptionIds: ['o'],
          explanation: 'door suena con sonido O, como floor.',
        },
        {
          id: 30,
          audioText: 'loop',
          language: 'en',
          prompt: '¿Qué sonido escuchaste?',
          options: [
            { id: 'u', text: 'Sonido U (como en hoop)' },
            { id: 'o', text: 'Sonido O (como en floor)' },
          ],
          correctOptionIds: ['u'],
          explanation: 'loop suena con sonido U, como hoop.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: 'ED: ¿suena o es muda?',
      instructions: 'Escucha el verbo en pasado. Si termina en T o D antes de ED, la ED suena como una sílaba extra ("id"). En los demás casos es muda.',
      questions: [
        {
          id: 31,
          audioText: 'wanted',
          language: 'en',
          prompt: '¿Cómo se pronuncia la ED?',
          options: [
            { id: 'sounds', text: 'La ED suena (sílaba extra)' },
            { id: 'mute', text: 'La ED es muda' },
          ],
          correctOptionIds: ['sounds'],
          explanation: 'wanted termina en T + ED, así que la ED suena "id": wan-ted.',
        },
        {
          id: 32,
          audioText: 'walked',
          language: 'en',
          prompt: '¿Cómo se pronuncia la ED?',
          options: [
            { id: 'sounds', text: 'La ED suena (sílaba extra)' },
            { id: 'mute', text: 'La ED es muda' },
          ],
          correctOptionIds: ['mute'],
          explanation: 'walked no termina en T ni D antes de ED, así que la ED es muda: se dice "wokt".',
        },
        {
          id: 33,
          audioText: 'needed',
          language: 'en',
          prompt: '¿Cómo se pronuncia la ED?',
          options: [
            { id: 'sounds', text: 'La ED suena (sílaba extra)' },
            { id: 'mute', text: 'La ED es muda' },
          ],
          correctOptionIds: ['sounds'],
          explanation: 'needed termina en D + ED, así que la ED suena "id": nee-ded.',
        },
        {
          id: 34,
          audioText: 'played',
          language: 'en',
          prompt: '¿Cómo se pronuncia la ED?',
          options: [
            { id: 'sounds', text: 'La ED suena (sílaba extra)' },
            { id: 'mute', text: 'La ED es muda' },
          ],
          correctOptionIds: ['mute'],
          explanation: 'played tiene la ED muda: se dice "pleid".',
        },
        {
          id: 35,
          audioText: 'started',
          language: 'en',
          prompt: '¿Cómo se pronuncia la ED?',
          options: [
            { id: 'sounds', text: 'La ED suena (sílaba extra)' },
            { id: 'mute', text: 'La ED es muda' },
          ],
          correctOptionIds: ['sounds'],
          explanation: 'started termina en T + ED, así que la ED suena "id": star-ted.',
        },
        {
          id: 36,
          audioText: 'watched',
          language: 'en',
          prompt: '¿Cómo se pronuncia la ED?',
          options: [
            { id: 'sounds', text: 'La ED suena (sílaba extra)' },
            { id: 'mute', text: 'La ED es muda' },
          ],
          correctOptionIds: ['mute'],
          explanation: 'watched tiene la ED muda: se dice "wocht".',
        },
        {
          id: 37,
          audioText: 'decided',
          language: 'en',
          prompt: '¿Cómo se pronuncia la ED?',
          options: [
            { id: 'sounds', text: 'La ED suena (sílaba extra)' },
            { id: 'mute', text: 'La ED es muda' },
          ],
          correctOptionIds: ['sounds'],
          explanation: 'decided termina en D + ED, así que la ED suena "id": de-ci-ded.',
        },
        {
          id: 38,
          audioText: 'cleaned',
          language: 'en',
          prompt: '¿Cómo se pronuncia la ED?',
          options: [
            { id: 'sounds', text: 'La ED suena (sílaba extra)' },
            { id: 'mute', text: 'La ED es muda' },
          ],
          correctOptionIds: ['mute'],
          explanation: 'cleaned tiene la ED muda: se dice "klind".',
        },
        {
          id: 39,
          audioText: 'hated',
          language: 'en',
          prompt: '¿Cómo se pronuncia la ED?',
          options: [
            { id: 'sounds', text: 'La ED suena (sílaba extra)' },
            { id: 'mute', text: 'La ED es muda' },
          ],
          correctOptionIds: ['sounds'],
          explanation: 'hated termina en T + ED, así que la ED suena "id": ha-ted.',
        },
        {
          id: 40,
          audioText: 'danced',
          language: 'en',
          prompt: '¿Cómo se pronuncia la ED?',
          options: [
            { id: 'sounds', text: 'La ED suena (sílaba extra)' },
            { id: 'mute', text: 'La ED es muda' },
          ],
          correctOptionIds: ['mute'],
          explanation: 'danced tiene la ED muda: se dice "danst".',
        },
      ],
    },
  ],
};

export default lessonA1004;
