import type { LessonContent } from '../types';

const lessonA1005: LessonContent = {
  level: 'a1',
  number: 5,
  title: 'How do you spell it?',
  subtitle: 'Aprende a deletrear tu nombre y apellido, a decir correos electrónicos con at y dot, y a escribir lo que escuchas.',
  videoTitle: 'How do you spell it?',
  videoDescription: 'En este video aprenderás a preguntar y responder cómo se deletrea algo, las letras dobles y los correos electrónicos.',
  objective: 'Al terminar, podrás deletrear tu nombre, tu apellido y tu correo electrónico en inglés, y entender cuando otra persona los deletrea.',
  exercises: [
    {
      type: 'listening-choice',
      title: 'Escucha el nombre y elige cómo se deletrea',
      instructions: 'Escucha el nombre y elige su deletreo. Cuando hay dos letras iguales seguidas, se dice "double".',
      questions: [
        {
          id: 1,
          audioText: 'Anna',
          language: 'en',
          prompt: '¿Cómo se deletrea este nombre?',
          options: [
            { id: 'a', text: 'A-double N-A' },
            { id: 'b', text: 'A-double N-E' },
            { id: 'c', text: 'A-M-A' },
          ],
          correctOptionIds: ['a'],
          explanation: 'Anna se deletrea A-double N-A: las dos N se dicen "double N".',
        },
        {
          id: 2,
          audioText: 'Tom',
          language: 'en',
          prompt: '¿Cómo se deletrea este nombre?',
          options: [
            { id: 'a', text: 'T-A-M' },
            { id: 'b', text: 'T-O-M' },
            { id: 'c', text: 'D-O-M' },
          ],
          correctOptionIds: ['b'],
          explanation: 'Tom se deletrea T-O-M.',
        },
        {
          id: 3,
          audioText: 'Emma',
          language: 'en',
          prompt: '¿Cómo se deletrea este nombre?',
          options: [
            { id: 'a', text: 'E-N-M-A' },
            { id: 'b', text: 'E-double M-E' },
            { id: 'c', text: 'E-double M-A' },
          ],
          correctOptionIds: ['c'],
          explanation: 'Emma se deletrea E-double M-A: las dos M se dicen "double M".',
        },
        {
          id: 4,
          audioText: 'Mary',
          language: 'en',
          prompt: '¿Cómo se deletrea este nombre?',
          options: [
            { id: 'a', text: 'M-A-R-Y' },
            { id: 'b', text: 'M-E-R-Y' },
            { id: 'c', text: 'N-A-R-Y' },
          ],
          correctOptionIds: ['a'],
          explanation: 'Mary se deletrea M-A-R-Y.',
        },
        {
          id: 5,
          audioText: 'Lee',
          language: 'en',
          prompt: '¿Cómo se deletrea este nombre?',
          options: [
            { id: 'a', text: 'L-O-double E' },
            { id: 'b', text: 'R-double E' },
            { id: 'c', text: 'L-double E' },
          ],
          correctOptionIds: ['c'],
          explanation: 'Lee se deletrea L-double E: las dos E se dicen "double E".',
        },
        {
          id: 6,
          audioText: 'Jessica',
          language: 'en',
          prompt: '¿Cómo se deletrea este nombre?',
          options: [
            { id: 'a', text: 'G-E-double S-I-C-A' },
            { id: 'b', text: 'J-E-double S-I-C-A' },
            { id: 'c', text: 'J-E-S-I-C-A' },
          ],
          correctOptionIds: ['b'],
          explanation: 'Jessica se deletrea J-E-double S-I-C-A: las dos S se dicen "double S".',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: 'Escucha el correo electrónico',
      instructions: 'Escucha el correo y elige cómo se escribe. Recuerda: @ se dice "at", . se dice "dot", _ se dice "underscore" y - se dice "dash".',
      questions: [
        {
          id: 7,
          audioText: 'My email is laura underscore guzman at gmail dot com.',
          language: 'en',
          prompt: '¿Qué correo escuchaste?',
          options: [
            { id: 'a', text: 'laura-guzman@gmail.com' },
            { id: 'b', text: 'laura.guzman@gmail.com' },
            { id: 'c', text: 'laura_guzman@gmail.com' },
          ],
          correctOptionIds: ['c'],
          explanation: '"underscore" es el guion bajo ( _ ).',
        },
        {
          id: 8,
          audioText: 'My email is maria dash lopez at hotmail dot com.',
          language: 'en',
          prompt: '¿Qué correo escuchaste?',
          options: [
            { id: 'a', text: 'maria-lopez@hotmail.com' },
            { id: 'b', text: 'maria_lopez@hotmail.com' },
            { id: 'c', text: 'maria.lopez@hotmail.com' },
          ],
          correctOptionIds: ['a'],
          explanation: '"dash" es el guion ( - ).',
        },
        {
          id: 9,
          audioText: 'My email is sara dot perez at gmail dot com.',
          language: 'en',
          prompt: '¿Qué correo escuchaste?',
          options: [
            { id: 'a', text: 'sara-perez@gmail.com' },
            { id: 'b', text: 'sara_perez@gmail.com' },
            { id: 'c', text: 'sara.perez@gmail.com' },
          ],
          correctOptionIds: ['c'],
          explanation: '"dot" es el punto ( . ).',
        },
        {
          id: 10,
          audioText: 'My email is john two three at yahoo dot com.',
          language: 'en',
          prompt: '¿Qué correo escuchaste?',
          options: [
            { id: 'a', text: 'john23@yahoo.com' },
            { id: 'b', text: 'john32@yahoo.com' },
            { id: 'c', text: 'john.23@yahoo.com' },
          ],
          correctOptionIds: ['a'],
          explanation: 'Los números se dicen uno por uno: two three = 23.',
        },
        {
          id: 11,
          audioText: 'My email is tom at outlook dot com.',
          language: 'en',
          prompt: '¿Qué correo escuchaste?',
          options: [
            { id: 'a', text: 'tom@outlook.com' },
            { id: 'b', text: 'tom.outlook@com' },
            { id: 'c', text: 'tom@outlook.net' },
          ],
          correctOptionIds: ['a'],
          explanation: '"at" es @ y "dot com" es .com.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Completa los espacios',
      instructions: 'Escribe la palabra que falta. Toca una palabra si quieres ver su traducción.',
      questions: [
        {
          id: 12,
          before: [
            { word: 'How', translation: 'cómo' },
            { word: 'do', translation: 'hacer' },
            { word: 'you', translation: 'tú' },
          ],
          after: [
            { word: 'your', translation: 'tu' },
            { word: 'last', translation: 'último / apellido' },
            { word: 'name?', translation: 'nombre' },
          ],
          answer: 'spell',
          sentenceTranslation: '¿Cómo se deletrea tu apellido?',
        },
        {
          id: 13,
          before: [
            { word: 'Can', translation: 'puedes' },
            { word: 'you', translation: 'tú' },
          ],
          after: [
            { word: 'that,', translation: 'eso' },
            { word: 'please?', translation: 'por favor' },
          ],
          answer: 'spell',
          sentenceTranslation: '¿Puedes deletrearlo, por favor?',
        },
        {
          id: 14,
          before: [
            { word: 'My', translation: 'mi' },
            { word: 'email', translation: 'correo' },
            { word: 'is', translation: 'es' },
            { word: 'maria', translation: 'María' },
          ],
          after: [
            { word: 'gmail', translation: 'gmail' },
            { word: 'dot', translation: 'punto' },
            { word: 'com.', translation: 'com' },
          ],
          answer: 'at',
          sentenceTranslation: 'Mi correo es maria arroba gmail punto com.',
        },
        {
          id: 15,
          before: [
            { word: 'My', translation: 'mi' },
            { word: 'email', translation: 'correo' },
            { word: 'is', translation: 'es' },
            { word: 'maria', translation: 'María' },
            { word: 'at', translation: 'arroba / en' },
            { word: 'gmail', translation: 'gmail' },
          ],
          after: [
            { word: 'com.', translation: 'com' },
          ],
          answer: 'dot',
          sentenceTranslation: 'Mi correo es maria arroba gmail punto com.',
        },
        {
          id: 16,
          before: [
            { word: 'In', translation: 'en' },
            { word: 'the', translation: 'el/la' },
            { word: 'name', translation: 'nombre' },
            { word: 'Lee,', translation: 'Lee' },
            { word: 'we', translation: 'nosotros' },
            { word: 'say', translation: 'decimos' },
            { word: 'L,', translation: 'L' },
          ],
          after: [
            { word: 'E.', translation: 'E' },
          ],
          answer: 'double',
          sentenceTranslation: 'En el nombre Lee, decimos L, doble E.',
        },
        {
          id: 17,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'symbol', translation: 'símbolo' },
            { word: '_', translation: 'guion bajo' },
            { word: 'is', translation: 'es' },
          ],
          after: [],
          answer: 'underscore',
          sentenceTranslation: 'El símbolo _ es guion bajo.',
        },
        {
          id: 18,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'symbol', translation: 'símbolo' },
            { word: '-', translation: 'guion' },
            { word: 'is', translation: 'es' },
          ],
          after: [],
          answer: 'dash',
          sentenceTranslation: 'El símbolo - es guion.',
        },
        {
          id: 19,
          before: [
            { word: 'Can', translation: 'puedes' },
            { word: 'you', translation: 'tú' },
          ],
          after: [
            { word: 'that,', translation: 'eso' },
            { word: 'please?', translation: 'por favor' },
          ],
          answer: 'repeat',
          sentenceTranslation: '¿Puedes repetirlo, por favor?',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 20,
          tokens: [
            { id: 'q20-how', word: 'How', translation: 'cómo' },
            { id: 'q20-do', word: 'do', translation: 'hacer' },
            { id: 'q20-you', word: 'you', translation: 'tú' },
            { id: 'q20-spell', word: 'spell', translation: 'deletrear' },
            { id: 'q20-your', word: 'your', translation: 'tu' },
            { id: 'q20-name', word: 'name?', translation: 'nombre' },
          ],
          correctOrder: ['q20-how', 'q20-do', 'q20-you', 'q20-spell', 'q20-your', 'q20-name'],
          sentenceTranslation: '¿Cómo se deletrea tu nombre?',
        },
        {
          id: 21,
          tokens: [
            { id: 'q21-my', word: 'My', translation: 'mi' },
            {
              id: 'q21-last',
              word: 'last',
              translation: 'último / apellido',
            },
            { id: 'q21-name', word: 'name', translation: 'nombre' },
            { id: 'q21-is', word: 'is', translation: 'es' },
            { id: 'q21-guzman', word: 'Guzman.', translation: 'Guzman' },
          ],
          correctOrder: ['q21-my', 'q21-last', 'q21-name', 'q21-is', 'q21-guzman'],
          sentenceTranslation: 'Mi apellido es Guzman.',
        },
        {
          id: 22,
          tokens: [
            { id: 'q22-can', word: 'Can', translation: 'puedes' },
            { id: 'q22-you', word: 'you', translation: 'tú' },
            { id: 'q22-spell', word: 'spell', translation: 'deletrear' },
            { id: 'q22-that', word: 'that,', translation: 'eso' },
            { id: 'q22-please', word: 'please?', translation: 'por favor' },
          ],
          correctOrder: ['q22-can', 'q22-you', 'q22-spell', 'q22-that', 'q22-please'],
          sentenceTranslation: '¿Puedes deletrearlo, por favor?',
        },
        {
          id: 23,
          tokens: [
            { id: 'q23-my', word: 'My', translation: 'mi' },
            { id: 'q23-email', word: 'email', translation: 'correo' },
            { id: 'q23-is', word: 'is', translation: 'es' },
            { id: 'q23-laura', word: 'laura', translation: 'Laura' },
            { id: 'q23-at', word: 'at', translation: 'arroba / en' },
            { id: 'q23-gmail', word: 'gmail', translation: 'gmail' },
            { id: 'q23-dot', word: 'dot', translation: 'punto' },
            { id: 'q23-com', word: 'com.', translation: 'com' },
          ],
          correctOrder: ['q23-my', 'q23-email', 'q23-is', 'q23-laura', 'q23-at', 'q23-gmail', 'q23-dot', 'q23-com'],
          sentenceTranslation: 'Mi correo es laura arroba gmail punto com.',
        },
        {
          id: 24,
          tokens: [
            { id: 'q24-can', word: 'Can', translation: 'puedes' },
            { id: 'q24-you', word: 'you', translation: 'tú' },
            { id: 'q24-repeat', word: 'repeat', translation: 'repetir' },
            { id: 'q24-that', word: 'that,', translation: 'eso' },
            { id: 'q24-please', word: 'please?', translation: 'por favor' },
          ],
          correctOrder: ['q24-can', 'q24-you', 'q24-repeat', 'q24-that', 'q24-please'],
          sentenceTranslation: '¿Puedes repetirlo, por favor?',
        },
      ],
    },
  ],
};

export default lessonA1005;
