import type { LessonContent } from '../types';

const lessonA1008: LessonContent = {
  level: 'a1',
  number: 8,
  title: 'Colores, formas, tamaños y objetos',
  subtitle: 'Aprende los colores, las formas, los tamaños y los objetos del aula y de la casa.',
  videoTitle: 'Colores, formas, tamaños y objetos',
  videoDescription: 'En este video aprenderás colores, formas, tamaños y objetos del aula y de la casa, y cómo preguntar What color is it?',
  objective: 'Al terminar, podrás nombrar colores, formas, tamaños y objetos, y describirlos con oraciones cortas.',
  exercises: [
    {
      type: 'listening-choice',
      title: 'Escucha el color',
      instructions: 'Escucha el color en inglés y elige su significado.',
      questions: [
        {
          id: 1,
          audioText: 'red',
          language: 'en',
          prompt: '¿Qué color es?',
          options: [
            { id: 'rojo', text: 'Rojo' },
            { id: 'azul', text: 'Azul' },
            { id: 'amarillo', text: 'Amarillo' },
          ],
          correctOptionIds: ['rojo'],
          explanation: 'red significa rojo.',
        },
        {
          id: 2,
          audioText: 'blue',
          language: 'en',
          prompt: '¿Qué color es?',
          options: [
            { id: 'rojo', text: 'Rojo' },
            { id: 'amarillo', text: 'Amarillo' },
            { id: 'azul', text: 'Azul' },
          ],
          correctOptionIds: ['azul'],
          explanation: 'blue significa azul.',
        },
        {
          id: 3,
          audioText: 'green',
          language: 'en',
          prompt: '¿Qué color es?',
          options: [
            { id: 'amarillo', text: 'Amarillo' },
            { id: 'verde', text: 'Verde' },
            { id: 'rojo', text: 'Rojo' },
          ],
          correctOptionIds: ['verde'],
          explanation: 'green significa verde.',
        },
        {
          id: 4,
          audioText: 'yellow',
          language: 'en',
          prompt: '¿Qué color es?',
          options: [
            { id: 'amarillo', text: 'Amarillo' },
            { id: 'rojo', text: 'Rojo' },
            { id: 'verde', text: 'Verde' },
          ],
          correctOptionIds: ['amarillo'],
          explanation: 'yellow significa amarillo.',
        },
        {
          id: 5,
          audioText: 'black',
          language: 'en',
          prompt: '¿Qué color es?',
          options: [
            { id: 'rojo', text: 'Rojo' },
            { id: 'verde', text: 'Verde' },
            { id: 'negro', text: 'Negro' },
          ],
          correctOptionIds: ['negro'],
          explanation: 'black significa negro.',
        },
        {
          id: 6,
          audioText: 'white',
          language: 'en',
          prompt: '¿Qué color es?',
          options: [
            { id: 'verde', text: 'Verde' },
            { id: 'blanco', text: 'Blanco' },
            { id: 'rojo', text: 'Rojo' },
          ],
          correctOptionIds: ['blanco'],
          explanation: 'white significa blanco.',
        },
        {
          id: 7,
          audioText: 'orange',
          language: 'en',
          prompt: '¿Qué color es?',
          options: [
            { id: 'naranja', text: 'Naranja' },
            { id: 'rojo', text: 'Rojo' },
            { id: 'verde', text: 'Verde' },
          ],
          correctOptionIds: ['naranja'],
          explanation: 'orange significa naranja.',
        },
        {
          id: 8,
          audioText: 'pink',
          language: 'en',
          prompt: '¿Qué color es?',
          options: [
            { id: 'rojo', text: 'Rojo' },
            { id: 'verde', text: 'Verde' },
            { id: 'rosado', text: 'Rosado' },
          ],
          correctOptionIds: ['rosado'],
          explanation: 'pink significa rosado.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: 'Escucha el objeto',
      instructions: 'Escucha el objeto en inglés y elige su significado.',
      questions: [
        {
          id: 9,
          audioText: 'book',
          language: 'en',
          prompt: '¿Qué objeto es?',
          options: [
            { id: 'libro', text: 'Libro' },
            { id: 'silla', text: 'Silla' },
            { id: 'puerta', text: 'Puerta' },
          ],
          correctOptionIds: ['libro'],
          explanation: 'book significa libro.',
        },
        {
          id: 10,
          audioText: 'pen',
          language: 'en',
          prompt: '¿Qué objeto es?',
          options: [
            { id: 'mesa', text: 'Mesa' },
            { id: 'bolígrafo', text: 'Bolígrafo' },
            { id: 'cama', text: 'Cama' },
          ],
          correctOptionIds: ['bolígrafo'],
          explanation: 'pen significa bolígrafo.',
        },
        {
          id: 11,
          audioText: 'desk',
          language: 'en',
          prompt: '¿Qué objeto es?',
          options: [
            { id: 'ventana', text: 'Ventana' },
            { id: 'lámpara', text: 'Lámpara' },
            { id: 'escritorio', text: 'Escritorio' },
          ],
          correctOptionIds: ['escritorio'],
          explanation: 'desk significa escritorio.',
        },
        {
          id: 12,
          audioText: 'chair',
          language: 'en',
          prompt: '¿Qué objeto es?',
          options: [
            { id: 'silla', text: 'Silla' },
            { id: 'libro', text: 'Libro' },
            { id: 'cama', text: 'Cama' },
          ],
          correctOptionIds: ['silla'],
          explanation: 'chair significa silla.',
        },
        {
          id: 13,
          audioText: 'window',
          language: 'en',
          prompt: '¿Qué objeto es?',
          options: [
            { id: 'puerta', text: 'Puerta' },
            { id: 'ventana', text: 'Ventana' },
            { id: 'mesa', text: 'Mesa' },
          ],
          correctOptionIds: ['ventana'],
          explanation: 'window significa ventana.',
        },
        {
          id: 14,
          audioText: 'lamp',
          language: 'en',
          prompt: '¿Qué objeto es?',
          options: [
            { id: 'lámpara', text: 'Lámpara' },
            { id: 'escritorio', text: 'Escritorio' },
            { id: 'silla', text: 'Silla' },
          ],
          correctOptionIds: ['lámpara'],
          explanation: 'lamp significa lámpara.',
        },
        {
          id: 15,
          audioText: 'bed',
          language: 'en',
          prompt: '¿Qué objeto es?',
          options: [
            { id: 'mesa', text: 'Mesa' },
            { id: 'cama', text: 'Cama' },
            { id: 'libro', text: 'Libro' },
          ],
          correctOptionIds: ['cama'],
          explanation: 'bed significa cama.',
        },
        {
          id: 16,
          audioText: 'door',
          language: 'en',
          prompt: '¿Qué objeto es?',
          options: [
            { id: 'ventana', text: 'Ventana' },
            { id: 'silla', text: 'Silla' },
            { id: 'puerta', text: 'Puerta' },
          ],
          correctOptionIds: ['puerta'],
          explanation: 'door significa puerta.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Completa con el color, el tamaño o la forma',
      instructions: 'Escribe la palabra en inglés. La pista en español aparece entre paréntesis.',
      questions: [
        {
          id: 17,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'sky', translation: 'cielo' },
            { word: 'is', translation: 'es' },
          ],
          after: [],
          answer: 'blue',
          hint: 'azul',
          sentenceTranslation: 'El cielo es azul.',
        },
        {
          id: 18,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'banana', translation: 'banana' },
            { word: 'is', translation: 'es' },
          ],
          after: [],
          answer: 'yellow',
          hint: 'amarillo',
          sentenceTranslation: 'La banana es amarilla.',
        },
        {
          id: 19,
          before: [
            { word: 'Snow', translation: 'nieve' },
            { word: 'is', translation: 'es' },
          ],
          after: [],
          answer: 'white',
          hint: 'blanco',
          sentenceTranslation: 'La nieve es blanca.',
        },
        {
          id: 20,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'grass', translation: 'césped' },
            { word: 'is', translation: 'es' },
          ],
          after: [],
          answer: 'green',
          hint: 'verde',
          sentenceTranslation: 'El césped es verde.',
        },
        {
          id: 21,
          before: [
            { word: 'An', translation: 'un/una' },
            { word: 'elephant', translation: 'elefante' },
            { word: 'is', translation: 'es' },
          ],
          after: [],
          answer: 'big',
          hint: 'grande',
          sentenceTranslation: 'Un elefante es grande.',
        },
        {
          id: 22,
          before: [
            { word: 'An', translation: 'un/una' },
            { word: 'ant', translation: 'hormiga' },
            { word: 'is', translation: 'es' },
          ],
          after: [],
          answer: 'small',
          hint: 'pequeño',
          sentenceTranslation: 'Una hormiga es pequeña.',
        },
        {
          id: 23,
          before: [
            { word: 'A', translation: 'un/una' },
            { word: 'giraffe', translation: 'jirafa' },
            { word: 'is', translation: 'es' },
          ],
          after: [],
          answer: 'tall',
          hint: 'alto',
          sentenceTranslation: 'Una jirafa es alta.',
        },
        {
          id: 24,
          before: [
            { word: 'A', translation: 'un/una' },
            { word: 'pizza', translation: 'pizza' },
            { word: 'slice', translation: 'trozo' },
            { word: 'is', translation: 'es' },
            { word: 'a', translation: 'un/una' },
          ],
          after: [],
          answer: 'triangle',
          hint: 'triángulo',
          sentenceTranslation: 'Un trozo de pizza es un triángulo.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 25,
          tokens: [
            { id: 'q25-what', word: 'What', translation: 'qué' },
            { id: 'q25-color', word: 'color', translation: 'color' },
            { id: 'q25-is', word: 'is', translation: 'es' },
            { id: 'q25-it', word: 'it?', translation: 'eso' },
          ],
          correctOrder: ['q25-what', 'q25-color', 'q25-is', 'q25-it'],
          sentenceTranslation: '¿De qué color es?',
        },
        {
          id: 26,
          tokens: [
            { id: 'q26-its', word: 'It’s', translation: 'es' },
            { id: 'q26-a', word: 'a', translation: 'un/una' },
            { id: 'q26-big', word: 'big', translation: 'grande' },
            { id: 'q26-red', word: 'red', translation: 'rojo' },
            { id: 'q26-chair', word: 'chair.', translation: 'silla' },
          ],
          correctOrder: ['q26-its', 'q26-a', 'q26-big', 'q26-red', 'q26-chair'],
          sentenceTranslation: 'Es una silla roja grande.',
        },
        {
          id: 27,
          tokens: [
            { id: 'q27-the', word: 'The', translation: 'el/la' },
            { id: 'q27-book', word: 'book', translation: 'libro' },
            { id: 'q27-is', word: 'is', translation: 'es' },
            { id: 'q27-blue', word: 'blue.', translation: 'azul' },
          ],
          correctOrder: ['q27-the', 'q27-book', 'q27-is', 'q27-blue'],
          sentenceTranslation: 'El libro es azul.',
        },
        {
          id: 28,
          tokens: [
            { id: 'q28-the', word: 'The', translation: 'el/la' },
            { id: 'q28-pen', word: 'pen', translation: 'bolígrafo' },
            { id: 'q28-is', word: 'is', translation: 'es' },
            { id: 'q28-small', word: 'small.', translation: 'pequeño' },
          ],
          correctOrder: ['q28-the', 'q28-pen', 'q28-is', 'q28-small'],
          sentenceTranslation: 'El bolígrafo es pequeño.',
        },
        {
          id: 29,
          tokens: [
            { id: 'q29-what', word: 'What', translation: 'qué' },
            { id: 'q29-is', word: 'is', translation: 'es' },
            { id: 'q29-this', word: 'this?', translation: 'esto' },
          ],
          correctOrder: ['q29-what', 'q29-is', 'q29-this'],
          sentenceTranslation: '¿Qué es esto?',
        },
      ],
    },
  ],
};

export default lessonA1008;
