import type { LessonContent } from '../types';

const lessonA1012: LessonContent = {
  level: 'a1',
  number: 12,
  title: 'Who, what, where y how',
  subtitle: 'Aprende a preguntar con who, what, where y how, y a responder preguntas de sí o no.',
  videoTitle: 'Who, what, where y how',
  videoDescription: 'En este video aprenderás las palabras para preguntar (who, what, where, how) y las respuestas cortas de sí o no.',
  objective: 'Al terminar, podrás hacer preguntas básicas con who, what, where y how, y responder sí o no.',
  exercises: [
    {
      type: 'fill-in-the-blanks',
      title: 'Who, what, where o how',
      instructions: 'Escribe la palabra para preguntar: what (qué), who (quién), where (dónde) o how (cómo).',
      questions: [
        {
          id: 1,
          before: [],
          after: [
            { word: 'is', translation: 'es / está' },
            { word: 'your', translation: 'tu' },
            { word: 'name?', translation: 'nombre' },
          ],
          answer: 'What',
          sentenceTranslation: '¿Cuál es tu nombre?',
        },
        {
          id: 2,
          before: [],
          after: [
            { word: 'is', translation: 'es / está' },
            { word: 'she?', translation: 'ella' },
          ],
          answer: 'Who',
          sentenceTranslation: '¿Quién es ella?',
        },
        {
          id: 3,
          before: [],
          after: [
            { word: 'are', translation: 'eres / son' },
            { word: 'you?', translation: 'tú' },
          ],
          answer: 'Where',
          sentenceTranslation: '¿Dónde estás?',
        },
        {
          id: 4,
          before: [],
          after: [
            { word: 'are', translation: 'eres / son' },
            { word: 'you?', translation: 'tú' },
          ],
          answer: 'How',
          sentenceTranslation: '¿Cómo estás?',
        },
        {
          id: 5,
          before: [],
          after: [
            { word: 'old', translation: 'años' },
            { word: 'are', translation: 'eres / son' },
            { word: 'you?', translation: 'tú' },
          ],
          answer: 'How',
          sentenceTranslation: '¿Cuántos años tienes?',
        },
        {
          id: 6,
          before: [],
          after: [
            { word: 'is', translation: 'es / está' },
            { word: 'the', translation: 'el/la' },
            { word: 'book?', translation: 'libro' },
          ],
          answer: 'Where',
          sentenceTranslation: '¿Dónde está el libro?',
        },
        {
          id: 7,
          before: [],
          after: [
            { word: 'color', translation: 'color' },
            { word: 'is', translation: 'es / está' },
            { word: 'it?', translation: 'eso' },
          ],
          answer: 'What',
          sentenceTranslation: '¿De qué color es?',
        },
        {
          id: 8,
          before: [],
          after: [
            { word: 'are', translation: 'eres / son' },
            { word: 'they?', translation: 'ellos' },
          ],
          answer: 'Who',
          sentenceTranslation: '¿Quiénes son ellos?',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Respuestas cortas de sí o no',
      instructions: 'Completa la respuesta corta con am, is o are.',
      questions: [
        {
          id: 9,
          before: [
            { word: 'Are', translation: 'eres / son' },
            { word: 'you', translation: 'tú' },
            { word: 'a', translation: 'un/una' },
            { word: 'student?', translation: 'estudiante' },
            { word: 'Yes,', translation: 'sí' },
            { word: 'I', translation: 'yo' },
          ],
          after: [],
          answer: 'am',
          sentenceTranslation: '¿Eres estudiante? Sí, lo soy.',
        },
        {
          id: 10,
          before: [
            { word: 'Is', translation: 'es / está' },
            { word: 'he', translation: 'él' },
            { word: 'your', translation: 'tu' },
            { word: 'brother?', translation: 'hermano' },
            { word: 'Yes,', translation: 'sí' },
            { word: 'he', translation: 'él' },
          ],
          after: [],
          answer: 'is',
          sentenceTranslation: '¿Es tu hermano? Sí, lo es.',
        },
        {
          id: 11,
          before: [
            { word: 'Are', translation: 'eres / son' },
            { word: 'they', translation: 'ellos' },
            { word: 'friends?', translation: 'amigos' },
            { word: 'Yes,', translation: 'sí' },
            { word: 'they', translation: 'ellos' },
          ],
          after: [],
          answer: 'are',
          sentenceTranslation: '¿Son amigos? Sí, lo son.',
        },
        {
          id: 12,
          before: [
            { word: 'Is', translation: 'es / está' },
            { word: 'it', translation: 'eso' },
            { word: 'a', translation: 'un/una' },
            { word: 'dog?', translation: 'perro' },
            { word: 'No,', translation: 'no' },
            { word: 'it', translation: 'eso' },
          ],
          after: [
            { word: 'not.', translation: 'no' },
          ],
          answer: 'is',
          sentenceTranslation: '¿Es un perro? No, no lo es.',
        },
        {
          id: 13,
          before: [
            { word: 'Am', translation: 'soy' },
            { word: 'I', translation: 'yo' },
            { word: 'late?', translation: 'tarde' },
            { word: 'No,', translation: 'no' },
            { word: 'you', translation: 'tú' },
          ],
          after: [
            { word: 'not.', translation: 'no' },
          ],
          answer: 'are',
          sentenceTranslation: '¿Llego tarde? No, no llegas tarde.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Qué te preguntan?',
      instructions: 'Escucha la pregunta y elige por qué te están preguntando.',
      questions: [
        {
          id: 14,
          audioText: 'What is your name?',
          language: 'en',
          prompt: '¿Por qué te preguntan?',
          options: [
            { id: 'name', text: 'Tu nombre' },
            { id: 'person', text: 'Una persona' },
            { id: 'place', text: 'Un lugar' },
            { id: 'how', text: 'Cómo estás' },
            { id: 'age', text: 'Tu edad' },
            { id: 'color', text: 'Un color' },
          ],
          correctOptionIds: ['name'],
          explanation: 'What is your name? pregunta por el nombre.',
        },
        {
          id: 15,
          audioText: 'Who is she?',
          language: 'en',
          prompt: '¿Por qué te preguntan?',
          options: [
            { id: 'name', text: 'Tu nombre' },
            { id: 'person', text: 'Una persona' },
            { id: 'place', text: 'Un lugar' },
            { id: 'how', text: 'Cómo estás' },
            { id: 'age', text: 'Tu edad' },
            { id: 'color', text: 'Un color' },
          ],
          correctOptionIds: ['person'],
          explanation: 'Who pregunta por una persona.',
        },
        {
          id: 16,
          audioText: 'Where is the book?',
          language: 'en',
          prompt: '¿Por qué te preguntan?',
          options: [
            { id: 'name', text: 'Tu nombre' },
            { id: 'person', text: 'Una persona' },
            { id: 'place', text: 'Un lugar' },
            { id: 'how', text: 'Cómo estás' },
            { id: 'age', text: 'Tu edad' },
            { id: 'color', text: 'Un color' },
          ],
          correctOptionIds: ['place'],
          explanation: 'Where pregunta por un lugar.',
        },
        {
          id: 17,
          audioText: 'How are you?',
          language: 'en',
          prompt: '¿Por qué te preguntan?',
          options: [
            { id: 'name', text: 'Tu nombre' },
            { id: 'person', text: 'Una persona' },
            { id: 'place', text: 'Un lugar' },
            { id: 'how', text: 'Cómo estás' },
            { id: 'age', text: 'Tu edad' },
            { id: 'color', text: 'Un color' },
          ],
          correctOptionIds: ['how'],
          explanation: 'How are you? pregunta cómo estás.',
        },
        {
          id: 18,
          audioText: 'How old are you?',
          language: 'en',
          prompt: '¿Por qué te preguntan?',
          options: [
            { id: 'name', text: 'Tu nombre' },
            { id: 'person', text: 'Una persona' },
            { id: 'place', text: 'Un lugar' },
            { id: 'how', text: 'Cómo estás' },
            { id: 'age', text: 'Tu edad' },
            { id: 'color', text: 'Un color' },
          ],
          correctOptionIds: ['age'],
          explanation: 'How old pregunta por la edad.',
        },
        {
          id: 19,
          audioText: 'What color is it?',
          language: 'en',
          prompt: '¿Por qué te preguntan?',
          options: [
            { id: 'name', text: 'Tu nombre' },
            { id: 'person', text: 'Una persona' },
            { id: 'place', text: 'Un lugar' },
            { id: 'how', text: 'Cómo estás' },
            { id: 'age', text: 'Tu edad' },
            { id: 'color', text: 'Un color' },
          ],
          correctOptionIds: ['color'],
          explanation: 'What color pregunta por el color.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 20,
          tokens: [
            { id: 'q20-what', word: 'What', translation: 'qué' },
            { id: 'q20-is', word: 'is', translation: 'es / está' },
            { id: 'q20-your', word: 'your', translation: 'tu' },
            { id: 'q20-name', word: 'name?', translation: 'nombre' },
          ],
          correctOrder: ['q20-what', 'q20-is', 'q20-your', 'q20-name'],
          sentenceTranslation: '¿Cuál es tu nombre?',
        },
        {
          id: 21,
          tokens: [
            { id: 'q21-who', word: 'Who', translation: 'quién' },
            { id: 'q21-is', word: 'is', translation: 'es / está' },
            { id: 'q21-she', word: 'she?', translation: 'ella' },
          ],
          correctOrder: ['q21-who', 'q21-is', 'q21-she'],
          sentenceTranslation: '¿Quién es ella?',
        },
        {
          id: 22,
          tokens: [
            { id: 'q22-where', word: 'Where', translation: 'dónde' },
            { id: 'q22-is', word: 'is', translation: 'es / está' },
            { id: 'q22-the', word: 'the', translation: 'el/la' },
            { id: 'q22-book', word: 'book?', translation: 'libro' },
          ],
          correctOrder: ['q22-where', 'q22-is', 'q22-the', 'q22-book'],
          sentenceTranslation: '¿Dónde está el libro?',
        },
        {
          id: 23,
          tokens: [
            { id: 'q23-how', word: 'How', translation: 'cómo' },
            { id: 'q23-old', word: 'old', translation: 'años' },
            { id: 'q23-are', word: 'are', translation: 'eres / son' },
            { id: 'q23-you', word: 'you?', translation: 'tú' },
          ],
          correctOrder: ['q23-how', 'q23-old', 'q23-are', 'q23-you'],
          sentenceTranslation: '¿Cuántos años tienes?',
        },
        {
          id: 24,
          tokens: [
            { id: 'q24-are', word: 'Are', translation: 'eres / son' },
            { id: 'q24-you', word: 'you', translation: 'tú' },
            { id: 'q24-a', word: 'a', translation: 'un/una' },
            {
              id: 'q24-student',
              word: 'student?',
              translation: 'estudiante',
            },
          ],
          correctOrder: ['q24-are', 'q24-you', 'q24-a', 'q24-student'],
          sentenceTranslation: '¿Eres estudiante?',
        },
        {
          id: 25,
          tokens: [
            { id: 'q25-where', word: 'Where', translation: 'dónde' },
            { id: 'q25-are', word: 'are', translation: 'eres / son' },
            { id: 'q25-you', word: 'you', translation: 'tú' },
            { id: 'q25-from', word: 'from?', translation: 'de' },
          ],
          correctOrder: ['q25-where', 'q25-are', 'q25-you', 'q25-from'],
          sentenceTranslation: '¿De dónde eres?',
        },
      ],
    },
  ],
};

export default lessonA1012;
