import type { LessonContent } from '../types';

const lessonA1017: LessonContent = {
  level: 'a1',
  number: 17,
  title: 'Habitaciones, muebles y preposiciones',
  subtitle: 'Aprende los nombres de las habitaciones y los muebles, y las preposiciones para decir dónde están las cosas.',
  videoTitle: 'Habitaciones, muebles y preposiciones',
  videoDescription: 'En este video aprenderás las habitaciones de la casa, los muebles y las preposiciones in, on, under, next to, behind, in front of y between.',
  objective: 'Al terminar, podrás describir tu casa y decir dónde están las cosas.',
  exercises: [
    {
      type: 'listening-choice',
      title: 'Escucha la habitación',
      instructions: 'Escucha la habitación en inglés y elige su significado.',
      questions: [
        {
          id: 1,
          audioText: 'kitchen',
          language: 'en',
          prompt: '¿Qué habitación es?',
          options: [
            { id: 'cocina', text: 'Cocina' },
            { id: 'baño', text: 'Baño' },
            { id: 'jardín', text: 'Jardín' },
          ],
          correctOptionIds: ['cocina'],
          explanation: 'kitchen = cocina.',
        },
        {
          id: 2,
          audioText: 'bedroom',
          language: 'en',
          prompt: '¿Qué habitación es?',
          options: [
            { id: 'sala', text: 'Sala' },
            { id: 'dormitorio', text: 'Dormitorio' },
            { id: 'comedor', text: 'Comedor' },
          ],
          correctOptionIds: ['dormitorio'],
          explanation: 'bedroom = dormitorio.',
        },
        {
          id: 3,
          audioText: 'bathroom',
          language: 'en',
          prompt: '¿Qué habitación es?',
          options: [
            { id: 'baño', text: 'Baño' },
            { id: 'cocina', text: 'Cocina' },
            { id: 'dormitorio', text: 'Dormitorio' },
          ],
          correctOptionIds: ['baño'],
          explanation: 'bathroom = baño.',
        },
        {
          id: 4,
          audioText: 'living room',
          language: 'en',
          prompt: '¿Qué habitación es?',
          options: [
            { id: 'jardín', text: 'Jardín' },
            { id: 'sala', text: 'Sala' },
            { id: 'baño', text: 'Baño' },
          ],
          correctOptionIds: ['sala'],
          explanation: 'living room = sala.',
        },
        {
          id: 5,
          audioText: 'dining room',
          language: 'en',
          prompt: '¿Qué habitación es?',
          options: [
            { id: 'comedor', text: 'Comedor' },
            { id: 'dormitorio', text: 'Dormitorio' },
            { id: 'cocina', text: 'Cocina' },
          ],
          correctOptionIds: ['comedor'],
          explanation: 'dining room = comedor.',
        },
        {
          id: 6,
          audioText: 'garden',
          language: 'en',
          prompt: '¿Qué habitación es?',
          options: [
            { id: 'sala', text: 'Sala' },
            { id: 'comedor', text: 'Comedor' },
            { id: 'jardín', text: 'Jardín' },
          ],
          correctOptionIds: ['jardín'],
          explanation: 'garden = jardín.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Dónde está?',
      instructions: 'Escucha la oración y elige dónde está la cosa.',
      questions: [
        {
          id: 7,
          audioText: 'The lamp is next to the bed.',
          language: 'en',
          prompt: '¿Dónde está la cosa?',
          options: [
            { id: 'next', text: 'Al lado de' },
            { id: 'behind', text: 'Detrás de' },
            { id: 'between', text: 'Entre' },
          ],
          correctOptionIds: ['next'],
          explanation: 'next to = al lado de.',
        },
        {
          id: 8,
          audioText: 'The bag is behind the door.',
          language: 'en',
          prompt: '¿Dónde está la cosa?',
          options: [
            { id: 'front', text: 'Delante de' },
            { id: 'under', text: 'Debajo de' },
            { id: 'behind', text: 'Detrás de' },
          ],
          correctOptionIds: ['behind'],
          explanation: 'behind = detrás de.',
        },
        {
          id: 9,
          audioText: 'The TV is in front of the sofa.',
          language: 'en',
          prompt: '¿Dónde está la cosa?',
          options: [
            { id: 'on', text: 'Sobre' },
            { id: 'front', text: 'Delante de' },
            { id: 'between', text: 'Entre' },
          ],
          correctOptionIds: ['front'],
          explanation: 'in front of = delante de.',
        },
        {
          id: 10,
          audioText: 'The chair is between the desk and the bed.',
          language: 'en',
          prompt: '¿Dónde está la cosa?',
          options: [
            { id: 'between', text: 'Entre' },
            { id: 'under', text: 'Debajo de' },
            { id: 'next', text: 'Al lado de' },
          ],
          correctOptionIds: ['between'],
          explanation: 'between = entre.',
        },
        {
          id: 11,
          audioText: 'The cat is under the table.',
          language: 'en',
          prompt: '¿Dónde está la cosa?',
          options: [
            { id: 'on', text: 'Sobre' },
            { id: 'behind', text: 'Detrás de' },
            { id: 'under', text: 'Debajo de' },
          ],
          correctOptionIds: ['under'],
          explanation: 'under = debajo de.',
        },
        {
          id: 12,
          audioText: 'The book is on the desk.',
          language: 'en',
          prompt: '¿Dónde está la cosa?',
          options: [
            { id: 'front', text: 'Delante de' },
            { id: 'on', text: 'Sobre' },
            { id: 'next', text: 'Al lado de' },
          ],
          correctOptionIds: ['on'],
          explanation: 'on = sobre.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Completa los espacios',
      instructions: 'Escribe la palabra que falta.',
      questions: [
        {
          id: 13,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'sofa', translation: 'sofá' },
            { word: 'is', translation: 'es / está' },
          ],
          after: [
            { word: 'the', translation: 'el/la' },
            { word: 'living', translation: 'sala' },
            { word: 'room.', translation: 'cuarto' },
          ],
          answer: 'in',
          sentenceTranslation: 'El sofá está en la sala.',
        },
        {
          id: 14,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'lamp', translation: 'lámpara' },
            { word: 'is', translation: 'es / está' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'the', translation: 'el/la' },
            { word: 'bed.', translation: 'cama' },
          ],
          answer: 'next',
          sentenceTranslation: 'La lámpara está al lado de la cama.',
        },
        {
          id: 15,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'cat', translation: 'gato' },
            { word: 'is', translation: 'es / está' },
          ],
          after: [
            { word: 'the', translation: 'el/la' },
            { word: 'table.', translation: 'mesa' },
          ],
          answer: 'under',
          sentenceTranslation: 'El gato está debajo de la mesa.',
        },
        {
          id: 16,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'TV', translation: 'televisión' },
            { word: 'is', translation: 'es / está' },
            { word: 'in', translation: 'en' },
          ],
          after: [
            { word: 'of', translation: 'de' },
            { word: 'the', translation: 'el/la' },
            { word: 'sofa.', translation: 'sofá' },
          ],
          answer: 'front',
          sentenceTranslation: 'La televisión está delante del sofá.',
        },
        {
          id: 17,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'bag', translation: 'bolso' },
            { word: 'is', translation: 'es / está' },
          ],
          after: [
            { word: 'the', translation: 'el/la' },
            { word: 'door.', translation: 'puerta' },
          ],
          answer: 'behind',
          sentenceTranslation: 'El bolso está detrás de la puerta.',
        },
        {
          id: 18,
          before: [
            { word: 'There', translation: 'hay' },
          ],
          after: [
            { word: 'a', translation: 'un/una' },
            { word: 'bed', translation: 'cama' },
            { word: 'in', translation: 'en' },
            { word: 'the', translation: 'el/la' },
            { word: 'bedroom.', translation: 'dormitorio' },
          ],
          answer: 'is',
          sentenceTranslation: 'Hay una cama en el dormitorio.',
        },
        {
          id: 19,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'chair', translation: 'silla' },
            { word: 'is', translation: 'es / está' },
          ],
          after: [
            { word: 'the', translation: 'el/la' },
            { word: 'desk', translation: 'escritorio' },
            { word: 'and', translation: 'y' },
            { word: 'the', translation: 'el/la' },
            { word: 'bed.', translation: 'cama' },
          ],
          answer: 'between',
          sentenceTranslation: 'La silla está entre el escritorio y la cama.',
        },
        {
          id: 20,
          before: [],
          after: [
            { word: 'is', translation: 'es / está' },
            { word: 'the', translation: 'el/la' },
            { word: 'fridge?', translation: 'nevera' },
          ],
          answer: 'Where',
          sentenceTranslation: '¿Dónde está la nevera?',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 21,
          tokens: [
            { id: 'q21-the', word: 'The', translation: 'el/la' },
            { id: 'q21-sofa', word: 'sofa', translation: 'sofá' },
            { id: 'q21-is', word: 'is', translation: 'es / está' },
            { id: 'q21-in', word: 'in', translation: 'en' },
            { id: 'q21-the-2', word: 'the', translation: 'el/la' },
            { id: 'q21-living', word: 'living', translation: 'sala' },
            { id: 'q21-room', word: 'room.', translation: 'cuarto' },
          ],
          correctOrder: ['q21-the', 'q21-sofa', 'q21-is', 'q21-in', 'q21-the-2', 'q21-living', 'q21-room'],
          sentenceTranslation: 'El sofá está en la sala.',
        },
        {
          id: 22,
          tokens: [
            { id: 'q22-the', word: 'The', translation: 'el/la' },
            { id: 'q22-lamp', word: 'lamp', translation: 'lámpara' },
            { id: 'q22-is', word: 'is', translation: 'es / está' },
            { id: 'q22-next', word: 'next', translation: 'al lado' },
            { id: 'q22-to', word: 'to', translation: 'a' },
            { id: 'q22-the-2', word: 'the', translation: 'el/la' },
            { id: 'q22-bed', word: 'bed.', translation: 'cama' },
          ],
          correctOrder: ['q22-the', 'q22-lamp', 'q22-is', 'q22-next', 'q22-to', 'q22-the-2', 'q22-bed'],
          sentenceTranslation: 'La lámpara está al lado de la cama.',
        },
        {
          id: 23,
          tokens: [
            { id: 'q23-where', word: 'Where', translation: 'dónde' },
            { id: 'q23-is', word: 'is', translation: 'es / está' },
            { id: 'q23-the', word: 'the', translation: 'el/la' },
            { id: 'q23-fridge', word: 'fridge?', translation: 'nevera' },
          ],
          correctOrder: ['q23-where', 'q23-is', 'q23-the', 'q23-fridge'],
          sentenceTranslation: '¿Dónde está la nevera?',
        },
        {
          id: 24,
          tokens: [
            { id: 'q24-there', word: 'There', translation: 'hay' },
            { id: 'q24-is', word: 'is', translation: 'es / está' },
            { id: 'q24-a', word: 'a', translation: 'un/una' },
            { id: 'q24-bed', word: 'bed', translation: 'cama' },
            { id: 'q24-in', word: 'in', translation: 'en' },
            { id: 'q24-the', word: 'the', translation: 'el/la' },
            {
              id: 'q24-bedroom',
              word: 'bedroom.',
              translation: 'dormitorio',
            },
          ],
          correctOrder: ['q24-there', 'q24-is', 'q24-a', 'q24-bed', 'q24-in', 'q24-the', 'q24-bedroom'],
          sentenceTranslation: 'Hay una cama en el dormitorio.',
        },
        {
          id: 25,
          tokens: [
            { id: 'q25-is', word: 'Is', translation: 'es / está' },
            { id: 'q25-there', word: 'there', translation: 'hay' },
            { id: 'q25-a', word: 'a', translation: 'un/una' },
            { id: 'q25-tv', word: 'TV', translation: 'televisión' },
            { id: 'q25-in', word: 'in', translation: 'en' },
            { id: 'q25-the', word: 'the', translation: 'el/la' },
            { id: 'q25-kitchen', word: 'kitchen?', translation: 'cocina' },
          ],
          correctOrder: ['q25-is', 'q25-there', 'q25-a', 'q25-tv', 'q25-in', 'q25-the', 'q25-kitchen'],
          sentenceTranslation: '¿Hay televisión en la cocina?',
        },
        {
          id: 26,
          tokens: [
            { id: 'q26-the', word: 'The', translation: 'el/la' },
            { id: 'q26-cat', word: 'cat', translation: 'gato' },
            { id: 'q26-is', word: 'is', translation: 'es / está' },
            { id: 'q26-under', word: 'under', translation: 'debajo de' },
            { id: 'q26-the-2', word: 'the', translation: 'el/la' },
            { id: 'q26-table', word: 'table.', translation: 'mesa' },
          ],
          correctOrder: ['q26-the', 'q26-cat', 'q26-is', 'q26-under', 'q26-the-2', 'q26-table'],
          sentenceTranslation: 'El gato está debajo de la mesa.',
        },
      ],
    },
  ],
};

export default lessonA1017;
