import type { LessonContent } from '../types';

const lessonA1019: LessonContent = {
  level: 'a1',
  number: 19,
  title: 'Ropa, calzado y accesorios',
  subtitle: 'Aprende los nombres de la ropa, el calzado y los accesorios, y a decir qué lleva una persona.',
  videoTitle: 'Ropa, calzado y accesorios',
  videoDescription: 'En este video aprenderás ropa, calzado y accesorios, y a usar wear / wearing para decir qué lleva alguien.',
  objective: 'Al terminar, podrás describir qué lleva puesto una persona y opinar sobre su ropa.',
  exercises: [
    {
      type: 'listening-choice',
      title: 'Escucha la ropa',
      instructions: 'Escucha la palabra en inglés y elige su significado.',
      questions: [
        {
          id: 1,
          audioText: 'shirt',
          language: 'en',
          prompt: '¿Qué prenda es?',
          options: [
            { id: 'camisa', text: 'Camisa' },
            { id: 'falda', text: 'Falda' },
            { id: 'abrigo', text: 'Abrigo' },
          ],
          correctOptionIds: ['camisa'],
          explanation: 'shirt = camisa.',
        },
        {
          id: 2,
          audioText: 'dress',
          language: 'en',
          prompt: '¿Qué prenda es?',
          options: [
            { id: 'jeans', text: 'Jeans' },
            { id: 'vestido', text: 'Vestido' },
            { id: 'chaqueta', text: 'Chaqueta' },
          ],
          correctOptionIds: ['vestido'],
          explanation: 'dress = vestido.',
        },
        {
          id: 3,
          audioText: 'skirt',
          language: 'en',
          prompt: '¿Qué prenda es?',
          options: [
            { id: 'falda', text: 'Falda' },
            { id: 'camisa', text: 'Camisa' },
            { id: 'vestido', text: 'Vestido' },
          ],
          correctOptionIds: ['falda'],
          explanation: 'skirt = falda.',
        },
        {
          id: 4,
          audioText: 'jeans',
          language: 'en',
          prompt: '¿Qué prenda es?',
          options: [
            { id: 'vestido', text: 'Vestido' },
            { id: 'jeans', text: 'Jeans' },
            { id: 'abrigo', text: 'Abrigo' },
          ],
          correctOptionIds: ['jeans'],
          explanation: 'jeans = jeans.',
        },
        {
          id: 5,
          audioText: 'jacket',
          language: 'en',
          prompt: '¿Qué prenda es?',
          options: [
            { id: 'chaqueta', text: 'Chaqueta' },
            { id: 'falda', text: 'Falda' },
            { id: 'camisa', text: 'Camisa' },
          ],
          correctOptionIds: ['chaqueta'],
          explanation: 'jacket = chaqueta.',
        },
        {
          id: 6,
          audioText: 'coat',
          language: 'en',
          prompt: '¿Qué prenda es?',
          options: [
            { id: 'jeans', text: 'Jeans' },
            { id: 'abrigo', text: 'Abrigo' },
            { id: 'vestido', text: 'Vestido' },
          ],
          correctOptionIds: ['abrigo'],
          explanation: 'coat = abrigo.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: 'Escucha el calzado y los accesorios',
      instructions: 'Escucha la palabra en inglés y elige su significado.',
      questions: [
        {
          id: 7,
          audioText: 'sneakers',
          language: 'en',
          prompt: '¿Qué es?',
          options: [
            { id: 'tenis', text: 'Tenis' },
            { id: 'botas', text: 'Botas' },
            { id: 'sandalias', text: 'Sandalias' },
          ],
          correctOptionIds: ['tenis'],
          explanation: 'sneakers = tenis.',
        },
        {
          id: 8,
          audioText: 'boots',
          language: 'en',
          prompt: '¿Qué es?',
          options: [
            { id: 'sandalias', text: 'Sandalias' },
            { id: 'botas', text: 'Botas' },
            { id: 'medias', text: 'Medias' },
          ],
          correctOptionIds: ['botas'],
          explanation: 'boots = botas.',
        },
        {
          id: 9,
          audioText: 'sandals',
          language: 'en',
          prompt: '¿Qué es?',
          options: [
            { id: 'sandalias', text: 'Sandalias' },
            { id: 'tenis', text: 'Tenis' },
            { id: 'botas', text: 'Botas' },
          ],
          correctOptionIds: ['sandalias'],
          explanation: 'sandals = sandalias.',
        },
        {
          id: 10,
          audioText: 'hat',
          language: 'en',
          prompt: '¿Qué es?',
          options: [
            { id: 'sombrero', text: 'Sombrero' },
            { id: 'lentes', text: 'Lentes' },
            { id: 'cinturón', text: 'Cinturón' },
          ],
          correctOptionIds: ['sombrero'],
          explanation: 'hat = sombrero.',
        },
        {
          id: 11,
          audioText: 'glasses',
          language: 'en',
          prompt: '¿Qué es?',
          options: [
            { id: 'cinturón', text: 'Cinturón' },
            { id: 'lentes', text: 'Lentes' },
            { id: 'reloj', text: 'Reloj' },
          ],
          correctOptionIds: ['lentes'],
          explanation: 'glasses = lentes.',
        },
        {
          id: 12,
          audioText: 'belt',
          language: 'en',
          prompt: '¿Qué es?',
          options: [
            { id: 'reloj', text: 'Reloj' },
            { id: 'sombrero', text: 'Sombrero' },
            { id: 'cinturón', text: 'Cinturón' },
          ],
          correctOptionIds: ['cinturón'],
          explanation: 'belt = cinturón.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Completa los espacios',
      instructions: 'Escribe la palabra que falta.',
      questions: [
        {
          id: 13,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'is', translation: 'es / está' },
          ],
          after: [
            { word: 'a', translation: 'un/una' },
            { word: 'red', translation: 'roja' },
            { word: 'dress.', translation: 'vestido' },
          ],
          answer: 'wearing',
          sentenceTranslation: 'Ella lleva un vestido rojo.',
        },
        {
          id: 14,
          before: [
            { word: 'He’s', translation: 'él está' },
          ],
          after: [
            { word: 'jeans', translation: 'jeans' },
            { word: 'and', translation: 'y' },
            { word: 'a', translation: 'un/una' },
            { word: 'blue', translation: 'azules' },
            { word: 'shirt.', translation: 'camisa' },
          ],
          answer: 'wearing',
          sentenceTranslation: 'Él lleva jeans y una camisa azul.',
        },
        {
          id: 15,
          before: [],
          after: [
            { word: 'are', translation: 'son / estás' },
            { word: 'you', translation: 'tú' },
            { word: 'wearing?', translation: 'llevando' },
          ],
          answer: 'What',
          sentenceTranslation: '¿Qué llevas puesto?',
        },
        {
          id: 16,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'like', translation: 'gustaría' },
            { word: 'your', translation: 'tu' },
          ],
          after: [],
          answer: 'hat',
          sentenceTranslation: 'Me gusta tu sombrero.',
        },
        {
          id: 17,
          before: [
            { word: 'These', translation: 'estos' },
            { word: 'are', translation: 'son / estás' },
            { word: 'my', translation: 'mi' },
          ],
          after: [],
          answer: 'shoes',
          sentenceTranslation: 'Estos son mis zapatos.',
        },
        {
          id: 18,
          before: [
            { word: 'Those', translation: 'esos' },
          ],
          after: [
            { word: 'are', translation: 'son / estás' },
            { word: 'new.', translation: 'nuevos' },
          ],
          answer: 'jeans',
          sentenceTranslation: 'Esos jeans son nuevos.',
        },
        {
          id: 19,
          before: [
            { word: 'Do', translation: 'gustan' },
            { word: 'you', translation: 'tú' },
            { word: 'like', translation: 'gustaría' },
            { word: 'my', translation: 'mi' },
            { word: 'shoes?', translation: 'zapatos' },
            { word: 'Yes,', translation: 'sí' },
            { word: 'I', translation: 'yo' },
          ],
          after: [],
          answer: 'do',
          sentenceTranslation: '¿Te gustan mis zapatos? Sí.',
        },
        {
          id: 20,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'wear', translation: 'llevo' },
            { word: 'a', translation: 'un/una' },
          ],
          after: [],
          answer: 'uniform',
          hint: 'uniforme',
          sentenceTranslation: 'Llevo uniforme.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 21,
          tokens: [
            { id: 'q21-she', word: 'She', translation: 'ella' },
            { id: 'q21-is', word: 'is', translation: 'es / está' },
            { id: 'q21-wearing', word: 'wearing', translation: 'llevando' },
            { id: 'q21-a', word: 'a', translation: 'un/una' },
            { id: 'q21-red', word: 'red', translation: 'roja' },
            { id: 'q21-dress', word: 'dress.', translation: 'vestido' },
          ],
          correctOrder: ['q21-she', 'q21-is', 'q21-wearing', 'q21-a', 'q21-red', 'q21-dress'],
          sentenceTranslation: 'Ella lleva un vestido rojo.',
        },
        {
          id: 22,
          tokens: [
            { id: 'q22-what', word: 'What', translation: 'qué' },
            { id: 'q22-are', word: 'are', translation: 'son / estás' },
            { id: 'q22-you', word: 'you', translation: 'tú' },
            {
              id: 'q22-wearing',
              word: 'wearing?',
              translation: 'llevando',
            },
          ],
          correctOrder: ['q22-what', 'q22-are', 'q22-you', 'q22-wearing'],
          sentenceTranslation: '¿Qué llevas puesto?',
        },
        {
          id: 23,
          tokens: [
            { id: 'q23-i', word: 'I', translation: 'yo' },
            { id: 'q23-like', word: 'like', translation: 'gustaría' },
            { id: 'q23-your', word: 'your', translation: 'tu' },
            { id: 'q23-hat', word: 'hat.', translation: 'sombrero' },
          ],
          correctOrder: ['q23-i', 'q23-like', 'q23-your', 'q23-hat'],
          sentenceTranslation: 'Me gusta tu sombrero.',
        },
        {
          id: 24,
          tokens: [
            { id: 'q24-these', word: 'These', translation: 'estos' },
            { id: 'q24-are', word: 'are', translation: 'son / estás' },
            { id: 'q24-my', word: 'my', translation: 'mi' },
            { id: 'q24-shoes', word: 'shoes.', translation: 'zapatos' },
          ],
          correctOrder: ['q24-these', 'q24-are', 'q24-my', 'q24-shoes'],
          sentenceTranslation: 'Estos son mis zapatos.',
        },
        {
          id: 25,
          tokens: [
            { id: 'q25-he', word: 'He', translation: 'él' },
            { id: 'q25-is', word: 'is', translation: 'es / está' },
            { id: 'q25-wearing', word: 'wearing', translation: 'llevando' },
            { id: 'q25-blue', word: 'blue', translation: 'azules' },
            { id: 'q25-jeans', word: 'jeans.', translation: 'jeans' },
          ],
          correctOrder: ['q25-he', 'q25-is', 'q25-wearing', 'q25-blue', 'q25-jeans'],
          sentenceTranslation: 'Él lleva jeans azules.',
        },
        {
          id: 26,
          tokens: [
            { id: 'q26-do', word: 'Do', translation: 'gustan' },
            { id: 'q26-you', word: 'you', translation: 'tú' },
            { id: 'q26-like', word: 'like', translation: 'gustaría' },
            { id: 'q26-my', word: 'my', translation: 'mi' },
            { id: 'q26-shoes', word: 'shoes?', translation: 'zapatos' },
          ],
          correctOrder: ['q26-do', 'q26-you', 'q26-like', 'q26-my', 'q26-shoes'],
          sentenceTranslation: '¿Te gustan mis zapatos?',
        },
      ],
    },
  ],
};

export default lessonA1019;
