import type { LessonContent } from '../types';

const lessonA2007: LessonContent = {
  level: 'a2',
  number: 7,
  title: 'Past simple vs past continuous',
  subtitle: 'Aprende a combinar una acción en progreso con otra que la interrumpe, usando when y while.',
  videoTitle: 'Past simple vs past continuous',
  videoDescription: 'En este video verás cuándo usar past simple y cuándo past continuous, y cómo combinarlos con when y while.',
  objective: 'Al terminar, podrás contar qué estaba pasando cuando otra cosa ocurrió, usando past continuous, past simple, when y while.',
  exercises: [
    {
      type: 'fill-in-the-blanks',
      title: 'Acción en progreso (past continuous)',
      instructions: 'Escribe el verbo con ING para la acción que estaba en progreso.',
      questions: [
        {
          id: 1,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'was', translation: 'estaba' },
          ],
          after: [
            { word: 'when', translation: 'cuando' },
            { word: 'the', translation: 'el/la' },
            { word: 'phone', translation: 'teléfono' },
            { word: 'rang.', translation: 'sonó' },
          ],
          answer: 'cooking',
          hint: 'cook',
          sentenceTranslation: 'Estaba cocinando cuando sonó el teléfono.',
        },
        {
          id: 2,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'was', translation: 'estaba' },
          ],
          after: [
            { word: 'when', translation: 'cuando' },
            { word: 'the', translation: 'el/la' },
            { word: 'lights', translation: 'luces' },
            { word: 'went', translation: 'fuimos' },
            { word: 'out.', translation: 'fuera' },
          ],
          answer: 'reading',
          hint: 'read',
          sentenceTranslation: 'Ella estaba leyendo cuando se fue la luz.',
        },
        {
          id: 3,
          before: [
            { word: 'They', translation: 'ellos' },
            { word: 'were', translation: 'estaban' },
          ],
          after: [
            { word: 'soccer', translation: 'fútbol' },
            { word: 'when', translation: 'cuando' },
            { word: 'it', translation: 'eso' },
            { word: 'began', translation: 'empezó' },
            { word: 'to', translation: 'a' },
            { word: 'rain.', translation: 'lluvia' },
          ],
          answer: 'playing',
          hint: 'play',
          sentenceTranslation: 'Ellos estaban jugando fútbol cuando empezó a llover.',
        },
        {
          id: 4,
          before: [
            { word: 'He', translation: 'él' },
            { word: 'was', translation: 'estaba' },
          ],
          after: [
            { word: 'when', translation: 'cuando' },
            { word: 'I', translation: 'yo' },
            { word: 'arrived.', translation: 'llegué' },
          ],
          answer: 'sleeping',
          hint: 'sleep',
          sentenceTranslation: 'Él estaba durmiendo cuando llegué.',
        },
        {
          id: 5,
          before: [
            { word: 'While', translation: 'mientras' },
            { word: 'we', translation: 'nosotros' },
            { word: 'were', translation: 'estaban' },
          ],
          after: [
            { word: 'the', translation: 'el/la' },
            { word: 'phone', translation: 'teléfono' },
            { word: 'rang.', translation: 'sonó' },
          ],
          answer: 'eating',
          hint: 'eat',
          sentenceTranslation: 'Mientras comíamos, sonó el teléfono.',
        },
        {
          id: 6,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'was', translation: 'estaba' },
          ],
          after: [
            { word: 'home', translation: 'a casa' },
            { word: 'when', translation: 'cuando' },
            { word: 'it', translation: 'eso' },
            { word: 'started', translation: 'empezó' },
            { word: 'to', translation: 'a' },
            { word: 'rain.', translation: 'lluvia' },
          ],
          answer: 'walking',
          hint: 'walk',
          sentenceTranslation: 'Estaba caminando a casa cuando empezó a llover.',
        },
        {
          id: 7,
          before: [
            { word: 'While', translation: 'mientras' },
            { word: 'she', translation: 'ella' },
            { word: 'was', translation: 'estaba' },
          ],
          after: [
            { word: 'he', translation: 'él' },
            { word: 'was', translation: 'estaba' },
            { word: 'washing', translation: 'lavando' },
            { word: 'the', translation: 'el/la' },
            { word: 'dishes.', translation: 'platos' },
          ],
          answer: 'cooking',
          hint: 'cook',
          sentenceTranslation: 'Mientras ella cocinaba, él lavaba los platos.',
        },
        {
          id: 8,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'children', translation: 'niños' },
            { word: 'were', translation: 'estaban' },
          ],
          after: [
            { word: 'while', translation: 'mientras' },
            { word: 'I', translation: 'yo' },
            { word: 'was', translation: 'estaba' },
            { word: 'working.', translation: 'trabajando' },
          ],
          answer: 'sleeping',
          hint: 'sleep',
          sentenceTranslation: 'Los niños dormían mientras yo trabajaba.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Acción que interrumpe (past simple)',
      instructions: 'Escribe el verbo en past simple para la acción corta que interrumpió.',
      questions: [
        {
          id: 9,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'was', translation: 'estaba' },
            { word: 'cooking', translation: 'cocinando' },
            { word: 'when', translation: 'cuando' },
            { word: 'the', translation: 'el/la' },
            { word: 'phone', translation: 'teléfono' },
          ],
          after: [],
          answer: 'rang',
          hint: 'ring',
          sentenceTranslation: 'Estaba cocinando cuando sonó el teléfono.',
        },
        {
          id: 10,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'was', translation: 'estaba' },
            { word: 'reading', translation: 'leyendo' },
            { word: 'when', translation: 'cuando' },
            { word: 'the', translation: 'el/la' },
            { word: 'lights', translation: 'luces' },
          ],
          after: [
            { word: 'out.', translation: 'fuera' },
          ],
          answer: 'went',
          hint: 'go',
          sentenceTranslation: 'Ella estaba leyendo cuando se fue la luz.',
        },
        {
          id: 11,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'was', translation: 'estaba' },
            { word: 'walking', translation: 'caminando' },
            { word: 'home', translation: 'a casa' },
            { word: 'when', translation: 'cuando' },
            { word: 'it', translation: 'eso' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'rain.', translation: 'lluvia' },
          ],
          answer: 'started',
          hint: 'start',
          sentenceTranslation: 'Estaba caminando a casa cuando empezó a llover.',
        },
        {
          id: 12,
          before: [
            { word: 'He', translation: 'él' },
            { word: 'was', translation: 'estaba' },
            { word: 'sleeping', translation: 'durmiendo' },
            { word: 'when', translation: 'cuando' },
            { word: 'I', translation: 'yo' },
          ],
          after: [],
          answer: 'arrived',
          hint: 'arrive',
          sentenceTranslation: 'Él estaba durmiendo cuando llegué.',
        },
        {
          id: 13,
          before: [
            { word: 'We', translation: 'nosotros' },
            { word: 'were', translation: 'estaban' },
            { word: 'eating', translation: 'comiendo' },
            { word: 'when', translation: 'cuando' },
            { word: 'she', translation: 'ella' },
          ],
          after: [
            { word: 'in.', translation: 'en' },
          ],
          answer: 'came',
          hint: 'come',
          sentenceTranslation: 'Estábamos comiendo cuando ella entró.',
        },
        {
          id: 14,
          before: [
            { word: 'I', translation: 'yo' },
          ],
          after: [
            { word: 'while', translation: 'mientras' },
            { word: 'I', translation: 'yo' },
            { word: 'was', translation: 'estaba' },
            { word: 'running.', translation: 'corriendo' },
          ],
          answer: 'fell',
          hint: 'fall',
          sentenceTranslation: 'Me caí mientras corría.',
        },
        {
          id: 15,
          before: [
            { word: 'They', translation: 'ellos' },
            { word: 'were', translation: 'estaban' },
            { word: 'playing', translation: 'jugando' },
            { word: 'when', translation: 'cuando' },
            { word: 'the', translation: 'el/la' },
            { word: 'teacher', translation: 'maestra' },
          ],
          after: [
            { word: 'in.', translation: 'en' },
          ],
          answer: 'walked',
          hint: 'walk',
          sentenceTranslation: 'Estaban jugando cuando la maestra entró.',
        },
        {
          id: 16,
          before: [
            { word: 'What', translation: 'qué' },
            { word: 'were', translation: 'estaban' },
            { word: 'you', translation: 'tú' },
            { word: 'doing', translation: 'haciendo' },
            { word: 'when', translation: 'cuando' },
            { word: 'the', translation: 'el/la' },
            { word: 'storm', translation: 'tormenta' },
          ],
          after: [],
          answer: 'started',
          hint: 'start',
          sentenceTranslation: '¿Qué estabas haciendo cuando empezó la tormenta?',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Qué interrumpió?',
      instructions: 'Escucha la oración y elige la acción corta que interrumpió a la otra.',
      questions: [
        {
          id: 17,
          audioText: 'I was cooking when the phone rang.',
          language: 'en',
          prompt: '¿Qué interrumpió?',
          options: [
            { id: 'phone', text: 'El teléfono sonó' },
            { id: 'cook', text: 'Ella cocinó' },
          ],
          correctOptionIds: ['phone'],
          explanation: 'when + past simple marca la acción que interrumpe: the phone rang.',
        },
        {
          id: 18,
          audioText: 'She was reading when the lights went out.',
          language: 'en',
          prompt: '¿Qué interrumpió?',
          options: [
            { id: 'read', text: 'Ella leyó' },
            { id: 'lights', text: 'Se fue la luz' },
          ],
          correctOptionIds: ['lights'],
          explanation: 'La luz se fue (past simple) mientras ella leía (past continuous).',
        },
        {
          id: 19,
          audioText: 'They were playing soccer when it began to rain.',
          language: 'en',
          prompt: '¿Qué interrumpió?',
          options: [
            { id: 'rain', text: 'Empezó a llover' },
            { id: 'soccer', text: 'Jugaron fútbol' },
          ],
          correctOptionIds: ['rain'],
          explanation: 'Began to rain es la acción que interrumpió.',
        },
        {
          id: 20,
          audioText: 'He was sleeping when I arrived.',
          language: 'en',
          prompt: '¿Qué interrumpió?',
          options: [
            { id: 'sleep', text: 'Él durmió' },
            { id: 'arrive', text: 'Yo llegué' },
          ],
          correctOptionIds: ['arrive'],
          explanation: 'I arrived (past simple) interrumpió su sueño.',
        },
        {
          id: 21,
          audioText: 'While she was cooking, he was washing the dishes.',
          language: 'en',
          prompt: '¿Las acciones pasaron al mismo tiempo?',
          options: [
            { id: 'yes', text: 'Sí, al mismo tiempo' },
            { id: 'no', text: 'No, una interrumpió a la otra' },
          ],
          correctOptionIds: ['yes'],
          explanation: 'while + past continuous en las dos partes: pasaron al mismo tiempo.',
        },
        {
          id: 22,
          audioText: 'I fell while I was running.',
          language: 'en',
          prompt: '¿Qué estaba pasando cuando se cayó?',
          options: [
            { id: 'run', text: 'Estaba corriendo' },
            { id: 'sleep', text: 'Estaba durmiendo' },
          ],
          correctOptionIds: ['run'],
          explanation: 'while I was running: estaba corriendo cuando se cayó.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 23,
          tokens: [
            { id: 'q23-i', word: 'I', translation: 'yo' },
            { id: 'q23-was', word: 'was', translation: 'estaba' },
            {
              id: 'q23-cooking',
              word: 'cooking',
              translation: 'cocinando',
            },
            { id: 'q23-when', word: 'when', translation: 'cuando' },
            { id: 'q23-the', word: 'the', translation: 'el/la' },
            { id: 'q23-phone', word: 'phone', translation: 'teléfono' },
            { id: 'q23-rang', word: 'rang.', translation: 'sonó' },
          ],
          correctOrder: ['q23-i', 'q23-was', 'q23-cooking', 'q23-when', 'q23-the', 'q23-phone', 'q23-rang'],
          sentenceTranslation: 'Estaba cocinando cuando sonó el teléfono.',
        },
        {
          id: 24,
          tokens: [
            { id: 'q24-she', word: 'She', translation: 'ella' },
            { id: 'q24-was', word: 'was', translation: 'estaba' },
            { id: 'q24-reading', word: 'reading', translation: 'leyendo' },
            { id: 'q24-when', word: 'when', translation: 'cuando' },
            { id: 'q24-the', word: 'the', translation: 'el/la' },
            { id: 'q24-lights', word: 'lights', translation: 'luces' },
            { id: 'q24-went', word: 'went', translation: 'fuimos' },
            { id: 'q24-out', word: 'out.', translation: 'fuera' },
          ],
          correctOrder: ['q24-she', 'q24-was', 'q24-reading', 'q24-when', 'q24-the', 'q24-lights', 'q24-went', 'q24-out'],
          sentenceTranslation: 'Ella estaba leyendo cuando se fue la luz.',
        },
        {
          id: 25,
          tokens: [
            { id: 'q25-he', word: 'He', translation: 'él' },
            { id: 'q25-was', word: 'was', translation: 'estaba' },
            {
              id: 'q25-sleeping',
              word: 'sleeping',
              translation: 'durmiendo',
            },
            { id: 'q25-when', word: 'when', translation: 'cuando' },
            { id: 'q25-i', word: 'I', translation: 'yo' },
            { id: 'q25-arrived', word: 'arrived.', translation: 'llegué' },
          ],
          correctOrder: ['q25-he', 'q25-was', 'q25-sleeping', 'q25-when', 'q25-i', 'q25-arrived'],
          sentenceTranslation: 'Él estaba durmiendo cuando llegué.',
        },
        {
          id: 26,
          tokens: [
            { id: 'q26-what', word: 'What', translation: 'qué' },
            { id: 'q26-were', word: 'were', translation: 'estaban' },
            { id: 'q26-you', word: 'you', translation: 'tú' },
            { id: 'q26-doing', word: 'doing', translation: 'haciendo' },
            { id: 'q26-when', word: 'when', translation: 'cuando' },
            { id: 'q26-the', word: 'the', translation: 'el/la' },
            { id: 'q26-storm', word: 'storm', translation: 'tormenta' },
            { id: 'q26-started', word: 'started?', translation: 'empezó' },
          ],
          correctOrder: ['q26-what', 'q26-were', 'q26-you', 'q26-doing', 'q26-when', 'q26-the', 'q26-storm', 'q26-started'],
          sentenceTranslation: '¿Qué estabas haciendo cuando empezó la tormenta?',
        },
        {
          id: 27,
          tokens: [
            { id: 'q27-i', word: 'I', translation: 'yo' },
            { id: 'q27-wasnt', word: 'wasn’t', translation: 'no estaba' },
            {
              id: 'q27-sleeping',
              word: 'sleeping',
              translation: 'durmiendo',
            },
            { id: 'q27-when', word: 'when', translation: 'cuando' },
            { id: 'q27-you', word: 'you', translation: 'tú' },
            { id: 'q27-called', word: 'called.', translation: 'llamaste' },
          ],
          correctOrder: ['q27-i', 'q27-wasnt', 'q27-sleeping', 'q27-when', 'q27-you', 'q27-called'],
          sentenceTranslation: 'No estaba durmiendo cuando llamaste.',
        },
        {
          id: 28,
          tokens: [
            { id: 'q28-were', word: 'Were', translation: 'estaban' },
            { id: 'q28-you', word: 'you', translation: 'tú' },
            {
              id: 'q28-working',
              word: 'working',
              translation: 'trabajando',
            },
            { id: 'q28-when', word: 'when', translation: 'cuando' },
            { id: 'q28-i', word: 'I', translation: 'yo' },
            { id: 'q28-called', word: 'called?', translation: 'llamaste' },
          ],
          correctOrder: ['q28-were', 'q28-you', 'q28-working', 'q28-when', 'q28-i', 'q28-called'],
          sentenceTranslation: '¿Estabas trabajando cuando llamé?',
        },
      ],
    },
  ],
};

export default lessonA2007;
