import type { LessonContent } from '../types';

const lessonA2020: LessonContent = {
  level: 'a2',
  number: 20,
  title: 'Direcciones y medios de transporte',
  subtitle: 'Aprende a pedir y dar direcciones, y a comparar medios de transporte.',
  videoTitle: 'Direcciones y medios de transporte',
  videoDescription: 'En este video verás cómo pedir y dar direcciones detalladas y cómo comparar medios de transporte con comparativos.',
  objective: 'Al terminar, podrás pedir y dar direcciones y comparar medios de transporte.',
  exercises: [
    {
      type: 'fill-in-the-blanks',
      title: 'Direcciones',
      instructions: 'Escribe la palabra que falta para pedir o dar direcciones.',
      questions: [
        {
          id: 1,
          before: [
            { word: 'Go', translation: 'voy' },
          ],
          after: [
            { word: 'for', translation: 'para' },
            { word: 'two', translation: 'dos' },
            { word: 'blocks.', translation: 'cuadras' },
          ],
          answer: 'straight',
          sentenceTranslation: 'Sigue derecho por dos cuadras.',
        },
        {
          id: 2,
          before: [],
          after: [
            { word: 'left', translation: 'izquierda' },
            { word: 'at', translation: 'a' },
            { word: 'the', translation: 'el/la' },
            { word: 'corner.', translation: 'esquina' },
          ],
          answer: 'Turn',
          sentenceTranslation: 'Gira a la izquierda en la esquina.',
        },
        {
          id: 3,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'bank', translation: 'banco' },
            { word: 'is', translation: 'es / está' },
          ],
          after: [
            { word: 'the', translation: 'el/la' },
            { word: 'park.', translation: 'parque' },
          ],
          answer: 'opposite',
          sentenceTranslation: 'El banco está frente al parque.',
        },
        {
          id: 4,
          before: [
            { word: 'It’s', translation: 'es' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'the', translation: 'el/la' },
            { word: 'supermarket.', translation: 'supermercado' },
          ],
          answer: 'next',
          sentenceTranslation: 'Está al lado del supermercado.',
        },
        {
          id: 5,
          before: [
            { word: 'Cross', translation: 'cruza' },
            { word: 'the', translation: 'el/la' },
          ],
          after: [],
          answer: 'street',
          sentenceTranslation: 'Cruza la calle.',
        },
        {
          id: 6,
          before: [
            { word: 'Turn', translation: 'gira' },
            { word: 'right', translation: 'derecha' },
            { word: 'at', translation: 'a' },
            { word: 'the', translation: 'el/la' },
            { word: 'traffic', translation: 'semáforo' },
          ],
          after: [],
          answer: 'lights',
          sentenceTranslation: 'Gira a la derecha en el semáforo.',
        },
        {
          id: 7,
          before: [
            { word: 'Is', translation: 'es / está' },
            { word: 'there', translation: 'allí' },
            { word: 'a', translation: 'un/una' },
            { word: 'pharmacy', translation: 'farmacia' },
          ],
          after: [
            { word: 'here?', translation: 'aquí' },
          ],
          answer: 'near',
          sentenceTranslation: '¿Hay una farmacia cerca de aquí?',
        },
        {
          id: 8,
          before: [
            { word: 'How', translation: 'cuánto' },
            { word: 'do', translation: 'gustan' },
            { word: 'I', translation: 'yo' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'the', translation: 'el/la' },
            { word: 'station?', translation: 'estación' },
          ],
          answer: 'get',
          sentenceTranslation: '¿Cómo llego a la estación?',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Compara el transporte',
      instructions: 'Escribe el comparativo o superlativo. El adjetivo aparece entre paréntesis en algunas frases.',
      questions: [
        {
          id: 9,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'train', translation: 'tren' },
            { word: 'is', translation: 'es / está' },
          ],
          after: [
            { word: 'than', translation: 'que' },
            { word: 'the', translation: 'el/la' },
            { word: 'bus.', translation: 'autobús' },
          ],
          answer: 'faster',
          hint: 'fast',
          sentenceTranslation: 'El tren es más rápido que el autobús.',
        },
        {
          id: 10,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'bus', translation: 'autobús' },
            { word: 'is', translation: 'es / está' },
          ],
          after: [
            { word: 'than', translation: 'que' },
            { word: 'a', translation: 'un/una' },
            { word: 'taxi.', translation: 'taxi' },
          ],
          answer: 'cheaper',
          hint: 'cheap',
          sentenceTranslation: 'El autobús es más barato que un taxi.',
        },
        {
          id: 11,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'subway', translation: 'metro' },
            { word: 'is', translation: 'es / está' },
            { word: 'more', translation: 'más' },
          ],
          after: [
            { word: 'than', translation: 'que' },
            { word: 'the', translation: 'el/la' },
            { word: 'bus.', translation: 'autobús' },
          ],
          answer: 'comfortable',
          sentenceTranslation: 'El metro es más cómodo que el autobús.',
        },
        {
          id: 12,
          before: [
            { word: 'Walking', translation: 'caminar' },
            { word: 'is', translation: 'es / está' },
          ],
          after: [
            { word: 'than', translation: 'que' },
            { word: 'driving.', translation: 'manejar' },
          ],
          answer: 'healthier',
          hint: 'healthy',
          sentenceTranslation: 'Caminar es más saludable que manejar.',
        },
        {
          id: 13,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'plane', translation: 'avión' },
            { word: 'is', translation: 'es / está' },
            { word: 'the', translation: 'el/la' },
          ],
          after: [],
          answer: 'fastest',
          hint: 'fast',
          sentenceTranslation: 'El avión es el más rápido.',
        },
        {
          id: 14,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'go', translation: 'voy' },
            { word: 'to', translation: 'a' },
            { word: 'work', translation: 'trabajo' },
          ],
          after: [
            { word: 'bus.', translation: 'autobús' },
          ],
          answer: 'by',
          sentenceTranslation: 'Voy al trabajo en autobús.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Qué debes hacer?',
      instructions: 'Escucha la indicación y elige qué debes hacer.',
      questions: [
        {
          id: 15,
          audioText: 'Turn left at the corner.',
          language: 'en',
          prompt: '¿Qué debes hacer?',
          options: [
            { id: 'left', text: 'Girar a la izquierda' },
            { id: 'right', text: 'Girar a la derecha' },
            { id: 'straight', text: 'Seguir derecho' },
            { id: 'cross', text: 'Cruzar la calle' },
          ],
          correctOptionIds: ['left'],
          explanation: 'turn left = girar a la izquierda.',
        },
        {
          id: 16,
          audioText: 'Turn right at the traffic lights.',
          language: 'en',
          prompt: '¿Qué debes hacer?',
          options: [
            { id: 'left', text: 'Girar a la izquierda' },
            { id: 'right', text: 'Girar a la derecha' },
            { id: 'straight', text: 'Seguir derecho' },
            { id: 'cross', text: 'Cruzar la calle' },
          ],
          correctOptionIds: ['right'],
          explanation: 'turn right = girar a la derecha.',
        },
        {
          id: 17,
          audioText: 'Go straight for two blocks.',
          language: 'en',
          prompt: '¿Qué debes hacer?',
          options: [
            { id: 'left', text: 'Girar a la izquierda' },
            { id: 'right', text: 'Girar a la derecha' },
            { id: 'straight', text: 'Seguir derecho' },
            { id: 'cross', text: 'Cruzar la calle' },
          ],
          correctOptionIds: ['straight'],
          explanation: 'go straight = seguir derecho.',
        },
        {
          id: 18,
          audioText: 'Cross the street.',
          language: 'en',
          prompt: '¿Qué debes hacer?',
          options: [
            { id: 'left', text: 'Girar a la izquierda' },
            { id: 'right', text: 'Girar a la derecha' },
            { id: 'straight', text: 'Seguir derecho' },
            { id: 'cross', text: 'Cruzar la calle' },
          ],
          correctOptionIds: ['cross'],
          explanation: 'cross = cruzar.',
        },
        {
          id: 19,
          audioText: 'Turn left after the bank.',
          language: 'en',
          prompt: '¿Qué debes hacer?',
          options: [
            { id: 'left', text: 'Girar a la izquierda' },
            { id: 'right', text: 'Girar a la derecha' },
            { id: 'straight', text: 'Seguir derecho' },
            { id: 'cross', text: 'Cruzar la calle' },
          ],
          correctOptionIds: ['left'],
          explanation: 'turn left = girar a la izquierda.',
        },
        {
          id: 20,
          audioText: 'Go straight and turn right.',
          language: 'en',
          prompt: '¿Qué debes hacer?',
          options: [
            { id: 'left', text: 'Girar a la izquierda' },
            { id: 'right', text: 'Girar a la derecha' },
            { id: 'straight', text: 'Seguir derecho' },
            { id: 'cross', text: 'Cruzar la calle' },
          ],
          correctOptionIds: ['straight'],
          explanation: 'primero sigue derecho, luego gira.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 21,
          tokens: [
            { id: 'q21-go', word: 'Go', translation: 'voy' },
            {
              id: 'q21-straight',
              word: 'straight',
              translation: 'derecho',
            },
            { id: 'q21-and', word: 'and', translation: 'y' },
            { id: 'q21-turn', word: 'turn', translation: 'gira' },
            { id: 'q21-left', word: 'left.', translation: 'izquierda' },
          ],
          correctOrder: ['q21-go', 'q21-straight', 'q21-and', 'q21-turn', 'q21-left'],
          sentenceTranslation: 'Sigue derecho y gira a la izquierda.',
        },
        {
          id: 22,
          tokens: [
            { id: 'q22-the', word: 'The', translation: 'el/la' },
            { id: 'q22-bank', word: 'bank', translation: 'banco' },
            { id: 'q22-is', word: 'is', translation: 'es / está' },
            {
              id: 'q22-opposite',
              word: 'opposite',
              translation: 'frente a',
            },
            { id: 'q22-the-2', word: 'the', translation: 'el/la' },
            { id: 'q22-park', word: 'park.', translation: 'parque' },
          ],
          correctOrder: ['q22-the', 'q22-bank', 'q22-is', 'q22-opposite', 'q22-the-2', 'q22-park'],
          sentenceTranslation: 'El banco está frente al parque.',
        },
        {
          id: 23,
          tokens: [
            { id: 'q23-is', word: 'Is', translation: 'es / está' },
            { id: 'q23-there', word: 'there', translation: 'allí' },
            { id: 'q23-a', word: 'a', translation: 'un/una' },
            { id: 'q23-bank', word: 'bank', translation: 'banco' },
            { id: 'q23-near', word: 'near', translation: 'cerca de' },
            { id: 'q23-here', word: 'here?', translation: 'aquí' },
          ],
          correctOrder: ['q23-is', 'q23-there', 'q23-a', 'q23-bank', 'q23-near', 'q23-here'],
          sentenceTranslation: '¿Hay un banco cerca de aquí?',
        },
        {
          id: 24,
          tokens: [
            { id: 'q24-the', word: 'The', translation: 'el/la' },
            { id: 'q24-train', word: 'train', translation: 'tren' },
            { id: 'q24-is', word: 'is', translation: 'es / está' },
            { id: 'q24-faster', word: 'faster', translation: 'más rápido' },
            { id: 'q24-than', word: 'than', translation: 'que' },
            { id: 'q24-the-2', word: 'the', translation: 'el/la' },
            { id: 'q24-bus', word: 'bus.', translation: 'autobús' },
          ],
          correctOrder: ['q24-the', 'q24-train', 'q24-is', 'q24-faster', 'q24-than', 'q24-the-2', 'q24-bus'],
          sentenceTranslation: 'El tren es más rápido que el autobús.',
        },
        {
          id: 25,
          tokens: [
            { id: 'q25-i', word: 'I', translation: 'yo' },
            { id: 'q25-go', word: 'go', translation: 'voy' },
            { id: 'q25-to', word: 'to', translation: 'a' },
            { id: 'q25-work', word: 'work', translation: 'trabajo' },
            { id: 'q25-by', word: 'by', translation: 'en' },
            { id: 'q25-bus', word: 'bus.', translation: 'autobús' },
          ],
          correctOrder: ['q25-i', 'q25-go', 'q25-to', 'q25-work', 'q25-by', 'q25-bus'],
          sentenceTranslation: 'Voy al trabajo en autobús.',
        },
        {
          id: 26,
          tokens: [
            { id: 'q26-how', word: 'How', translation: 'cuánto' },
            { id: 'q26-do', word: 'do', translation: 'gustan' },
            { id: 'q26-i', word: 'I', translation: 'yo' },
            { id: 'q26-get', word: 'get', translation: 'llegar' },
            { id: 'q26-to', word: 'to', translation: 'a' },
            { id: 'q26-the', word: 'the', translation: 'el/la' },
            {
              id: 'q26-station',
              word: 'station?',
              translation: 'estación',
            },
          ],
          correctOrder: ['q26-how', 'q26-do', 'q26-i', 'q26-get', 'q26-to', 'q26-the', 'q26-station'],
          sentenceTranslation: '¿Cómo llego a la estación?',
        },
      ],
    },
  ],
};

export default lessonA2020;
