export const lessonTitles: Record<
  string,
  Record<number, string>
> = {
  a1: {
    1: 'Presentarte: I am / My name is (con contracciones I’m / My name’s)',
    2: 'Tu familia: this is my..., mother, father, sister y brother',
    3: 'El alfabeto y sus grupos de sonido: familias /eɪ/, /iː/, /ɛ/, /aɪ/, /oʊ/, /uː/ y /ɑːr/',
    4: 'Vocales cortas y largas: pares clave como /iː/-/ɪ/ y /uː/-/ʊ/',
    5: 'How do you spell it?: deletrear nombre y apellido, correos electrónicos (at, dot) y dictado',
    6: 'Números del 0 al 100 y dictado; decir y comprender números de teléfono',
    7: 'Saludos y despedidas según la hora del día; How are you?: estados y respuestas básicas; preguntar y decir la edad',
    8: 'Colores, formas, tamaños y objetos del aula y de la casa',
    9: 'This is, It is y color + objeto; describir objetos con color, forma y tamaño',
    10: 'Pronombres personales y verbo be afirmativo: I am, you are, he is y contracciones',
    11: 'Verbo be: negativo, preguntas y respuestas cortas; nombre, edad y país en un mini diálogo',
    12: 'Who, what, where y how; preguntas y respuestas de sí o no',
    13: 'Países, nacionalidades, profesiones y ocupaciones',
    14: 'Tu familia, adjetivos posesivos, genitivo sajón y have/has para posesión',
    15: 'Artículos a, an y the; singular y plural; demostrativos this, that, these y those',
    16: 'There is/are: preguntas, negativos, some y any; in, on y under',
    17: 'Habitaciones, muebles y preposiciones de lugar',
    18: 'Partes del cuerpo, animales, características físicas y personalidad',
    19: 'Ropa, calzado y accesorios: describir qué lleva una persona',
    20: 'Comida y bebidas; sustantivos contables e incontables',
    21: 'Likes y dislikes: I like, I don’t like y Do you like...?',
    22: 'How much y how many; cantidades, dinero, precios, tallas y compras',
    23: 'Pedir comida y bebida (Can I have..., I’d like...); need, want y want to',
    24: 'Can y can’t: habilidad, solicitudes y permiso; imperativos',
    25: 'Días, meses, fechas, ordinales, estaciones y clima',
    26: 'La hora, horarios y at/on/in para expresiones de tiempo',
    27: 'Presente simple afirmativo: rutinas, acciones básicas y tercera persona -s/-es',
    28: 'Presente simple: negativo (do/does), preguntas y respuestas cortas',
    29: 'Adverbios de frecuencia; hablar de tu rutina y la de otra persona',
    30: 'Escuela, trabajo, tiempo libre y hobbies; play, go y do',
    31: 'Lugares de la ciudad, direcciones, preposiciones de ubicación y transporte',
    32: 'Present continuous: afirmativo, negativo y preguntas; acciones que ocurren ahora',
    33: 'Presente simple vs present continuous',
    34: 'Should para recomendaciones; salud, síntomas, emociones y because',
    35: 'Conectores and, but y or; orden sujeto + verbo + objeto',
    36: 'Object pronouns, possessive pronouns y Whose...?',
    37: 'Comparativos y superlativos básicos',
    38: 'Pasado de be (was y were) y pasado simple: verbos regulares e irregulares',
    39: 'Pasado simple negativo y preguntas con did; vacaciones y viajes',
    40: 'Planes futuros con be going to; conversaciones de supervivencia y cómo seguir aprendiendo',
  },

  a2: {
    1: 'Hábitos vs acciones temporales',
    2: 'Verbos de estado',
    3: 'Verbos irregulares comunes',
    4: 'Past simple: verbos regulares e irregulares, afirmativo, negativo y preguntas',
    5: 'Past continuous: afirmativo, negativo y preguntas, con ejemplos de la vida diaria',
    6: 'Secuenciadores: first, then, after that, finally; narrar acontecimientos pasados y contar una rutina o historia paso a paso',
    7: 'Past simple vs past continuous; when, while e interrupciones en el pasado',
    8: 'During, for y while: diferencias de uso; contar una historia sencilla',
    9: 'Present perfect: introducción, formación con have/has + participio y participios regulares',
    10: 'Participios irregulares frecuentes: memorización, pronunciación y uso en present perfect',
    11: 'Experiencias con ever y never; Have you ever...?; been y gone; hablar de experiencias personales',
    12: 'Present perfect vs past simple',
    13: 'Just, already, yet, still, any more, recently y lately con present perfect',
    14: 'For y since; How long...? preguntas sobre duración',
    15: 'Futuro con going to',
    16: 'Futuro con will: predicciones, I think y probably',
    17: 'Will para decisiones espontáneas, ofrecimientos, promesas y pedir ayuda',
    18: 'Present continuous para planes futuros; comparar will, going to y present continuous; metas y planes de estudio',
    19: 'Viajes: planear un viaje, hoteles, aeropuerto, vuelos retrasados y billetes',
    20: 'Pedir y dar direcciones detalladas; comparar medios de transporte',
    21: 'Comida y cocina: métodos de cocción y seguir una receta',
    22: 'Restaurantes: pedir recomendaciones, alergias, restricciones y quejarse educadamente',
    23: 'Compras, devoluciones, describir productos, compras por internet y problemas con pedidos',
    24: 'La casa: vivienda, tareas domésticas, problemas en casa y alquiler',
    25: 'Trabajo: profesiones, buscar empleo, experiencia laboral y entrevistas sencillas',
    26: 'Estudios y educación: describir tu experiencia educativa',
    27: 'Tecnología cotidiana, problemas tecnológicos y seguridad básica en internet',
    28: 'Salud y bienestar: síntomas, consulta médica, medicamentos y hábitos saludables',
    29: 'Should y shouldn’t: consejo y recomendaciones',
    30: 'Must, mustn’t, have to y don’t have to: obligación y prohibición',
    31: 'Comparativos avanzados, as...as; too y enough',
    32: 'Relative clauses con who, which y that',
    33: 'Something, anything, nothing, everything; someone, anyone, no one y everyone',
    34: 'Pronombres reflexivos; adjetivos terminados en -ed y -ing',
    35: 'Infinitivo con to y gerundio después de verbos comunes',
    36: 'Zero y first conditional',
    37: 'Modales de posibilidad y habilidad: may, might, can, could y be able to',
    38: 'Phrasal verbs cotidianos básicos',
    39: 'Conectores: because, so, although',
    40: 'Expresar una opinión: I think, in my opinion y dar razones sencillas',
  },

  b1: {
    1: 'Present simple vs present continuous en contexto',
    2: 'Present perfect vs past simple; present perfect con for y since',
    3: 'Present perfect continuous y su contraste con present perfect simple',
    4: 'Past simple vs past continuous; narrar acontecimientos en orden con secuenciadores',
    5: 'Past perfect: formación, uso y contraste con past simple',
    6: 'Past perfect continuous y narrativas con los cuatro tiempos del pasado',
    7: 'Used to, would y past simple para hábitos pasados; hablar de cambios en tu vida',
    8: 'Futuros: will, going to y present continuous; planes, predicciones y grados de certeza',
    9: 'Future continuous: formación y usos',
    10: 'Future perfect: formación, uso y ejemplos con by the time y by then',
    11: 'First conditional y cláusulas futuras con when/if',
    12: 'Second conditional: situaciones hipotéticas; If I were you, I wish I knew',
    13: 'Third conditional: arrepentimientos e hipótesis pasadas; I wish I had known e If only',
    14: 'Mixed conditionals: introducción',
    15: 'Prefer vs would rather',
    16: 'Modales de obligación y consejo: must, have to, should, ought to y had better',
    17: 'Modales de posibilidad y deducción sobre el presente: may, might, could, must y can’t',
    18: 'Modales perfectos: deducciones y críticas sobre el pasado (must have, should have, could have)',
    19: 'Voz pasiva en varios tiempos; be done, been done, being done; active vs passive',
    20: 'Get passive, have something done y passive modals',
    21: 'Reported statements y reported questions',
    22: 'Reported commands, requests, reporting verbs y reported speech avanzado',
    23: 'Defining y non-defining relative clauses',
    24: 'Relative clauses con whose y whom; omisión del pronombre y reduced relative clauses',
    25: 'Gerunds e infinitives; verb + object + to; remember y stop doing/to do',
    26: 'Preposición + gerundio; be/get used to; propósito con to, for y so that; afraid to/of',
    27: 'Cláusulas con -ing y participle adjectives',
    28: 'Adjetivos, verbos y preposiciones frecuentes; phrasal verbs con get, take y put',
    29: 'Formación de palabras con prefijos y sufijos; collocations con make, do, have, take y get',
    30: 'Adverbios de manera y grado; well, fast, late, hard y hardly; intensificadores y mitigadores',
    31: 'So, such, too y enough; comparativos complejos; in case, as, like y as if',
    32: 'By, until, by the time, on time e in time; adverbios de certeza y adverbios oracionales',
    33: 'Trabajo, carrera, entrevistas y comunicación profesional',
    34: 'Educación, tecnología, vida digital, noticias y credibilidad',
    35: 'Salud, bienestar, naturaleza, medio ambiente y consumo sostenible',
    36: 'Sociedad, comunidad, cultura, identidad y diferencias culturales',
    37: 'Expresar opiniones, matices y hedging; debatir ventajas y desventajas',
    38: 'Contraargumentar, persuadir y negociar; reformular, aclarar y resumir',
    39: 'Correos profesionales, textos de opinión y responder preguntas en una presentación',
    40: 'Discourse markers, connected speech y significado implícito; leer y escribir textos argumentativos',
  },

  b2: {
    1: 'Present perfect simple vs continuous avanzado',
    2: 'Past perfect simple vs continuous',
    3: 'Verbos irregulares comunes',
    4: 'Future perfect: formación, uso y ejemplos con by the time',
    5: 'Future perfect continuous: formación, uso y contraste con future perfect',
    6: 'Expresar el futuro desde el pasado',
    7: 'Was going to y would',
    8: 'Condicionales mixtos',
    9: 'Alternativas a if: unless, provided that y as long as',
    10: 'Inversion in conditionals: Were I to..., Had I known... y ejemplos de uso formal',
    11: 'Wish e if only avanzados; would rather; it’s time + past',
    12: 'Modales perfectos: deducción y especulación sobre el pasado, crítica y arrepentimiento',
    13: 'Voz pasiva avanzada',
    14: 'Passive reporting structures: it is said that..., he is said to... y estructuras similares',
    15: 'Causative have y get',
    16: 'Reported speech avanzado',
    17: 'Reporting verbs: deny, admit, insist y recommend',
    18: 'Gerundios e infinitivos complejos; perfect gerunds e infinitives; participle clauses y reduced clauses',
    19: 'Inversion after negative adverbials (Never have I...) y not only... but also',
    20: 'Cleft sentences y énfasis: What I need is..., It was... who... y emphasis con do',
    21: 'Nominalización: transformar verbos en sustantivos y estilo más formal',
    22: 'Discourse markers avanzados: furthermore, moreover, nevertheless, on the other hand, in contrast, consequently y therefore',
    23: 'Conectores para estructurar argumentos',
    24: 'Hedging y boosters: tend to, seem to, it could be argued that y matizar afirmaciones',
    25: 'Collocations B2: adjective + noun, verb + noun y adverb + adjective',
    26: 'Phrasal verbs B2: in, out, on, off, up, down, away y back; formales e informales',
    27: 'Idioms, lenguaje figurado, sinónimos y elección léxica',
    28: 'Registro formal vs informal; lenguaje diplomático, softening requests y disagreement',
    29: 'Expresar opiniones complejas; sustentar una postura con evidencia y ejemplos',
    30: 'Reconocer contraargumentos, refutar argumentos y concluir un argumento',
    31: 'Debates estructurados; interrumpir, recuperar el turno, aclarar y reformular',
    32: 'Persuadir, negociar y llegar a un consenso',
    33: 'Presentaciones profesionales: introducir, organizar puntos y responder preguntas',
    34: 'Reuniones profesionales: proponer ideas, expresar reservas y tomar decisiones en grupo',
    35: 'Trabajo y cultura laboral, liderazgo, motivación y productividad',
    36: 'Conflictos laborales, trabajo remoto y emprendimiento',
    37: 'Educación superior, investigación y pensamiento crítico',
    38: 'Tecnología y sociedad',
    39: 'Escribir ensayos de opinión y de ventajas y desventajas',
    40: 'Escribir un correo formal avanzado',
  },

  c1: {
    1: 'Control avanzado de tiempos verbales',
    2: 'Elección de tiempo verbal según perspectiva',
    3: 'Narración sofisticada',
    4: 'Cambios temporales y aspectuales',
    5: 'Future forms avanzadas',
    6: 'Future in the past',
    7: 'Condicionales avanzados',
    8: 'Inversión en condicionales: Had I known..., Were I to... y Should you need...',
    9: 'Mixed conditionals avanzados',
    10: 'Unreal past: it’s time, would rather y as if/as though',
    11: 'Wish, if only y would rather',
    12: 'Modales avanzados de deducción',
    13: 'Grados de certeza, especulación y modal perfects en contexto complejo',
    14: 'Voz pasiva y elección de agente',
    15: 'Passive reporting avanzado e impersonal passive constructions',
    16: 'Causative structures avanzadas',
    17: 'Reported speech con matices',
    18: 'Reporting verbs avanzados: allege, acknowledge, maintain, claim y verbos de postura',
    19: 'Participle clauses y reduced clauses avanzadas',
    20: 'Absolute clauses: formación, uso y ejemplos en registro formal',
    21: 'Inversión para énfasis: rarely, scarcely, hardly, no sooner... than y under no circumstances...',
    22: 'Cleft y pseudo-cleft sentences; fronting; énfasis mediante estructura',
    23: 'Nominalización avanzada y construcciones impersonales',
    24: 'Subjunctive formal: It is essential that...',
    25: 'Concesión avanzada y conectores académicos: cohesión y coherencia',
    26: 'Referencia y sustitución',
    27: 'Hedging académico, cautela, boosting y convicción',
    28: 'Stance markers y metadiscourse',
    29: 'Registro, estilo, lenguaje coloquial sofisticado, connotación y elección léxica precisa',
    30: 'Collocations C1, colocaciones profesionales y phrasal verbs avanzados e idiomáticos',
    31: 'Idioms, metáforas y lenguaje figurado',
    32: 'Ironía, sarcasmo, understatement, overstatement y humor',
    33: 'Inferencia pragmática, implicatura, presuposición y ambigüedad intencional',
    34: 'Diplomacia lingüística, desacuerdo sofisticado y crítica constructiva',
    35: 'Persuasión avanzada, técnicas retóricas, ethos, pathos, logos y framing',
    36: 'Contraargumentación avanzada, falacias y evaluación de razonamientos',
    37: 'Debates complejos, gestión de turnos y responder bajo presión',
    38: 'Sintetizar posiciones, negociación avanzada, concesión y mediación de conflictos',
    39: 'Escritura académica: estructura y parafrasear',
    40: 'Resumir textos y argumentos',
  },
};

export function getLessonTitle(
  level: string,
  lessonNumber: number,
) {
  return (
    lessonTitles[
      level.toLowerCase()
    ]?.[lessonNumber] ??
    `Lección ${lessonNumber}`
  );
}