export const lessonTitles: Record<
  string,
  Record<number, string>
> = {
  a0: {
    1: 'Presentarte: I am / My name is',
    2: 'Contracciones: I’m / My name’s',
    3: 'A, H, J, K: familia /eɪ/',
    4: 'E, P, G, D: primera familia /iː/',
    5: 'B, C, T, V, Z: segunda familia /iː/',
    6: 'L, M, N: contraste auditivo',
    7: 'F, S, X: familia con vocal /e/',
    8: 'I y Y: contraste y sonido final /aɪ/',
    9: 'Q, U y W: nombres con /juː/',
    10: 'O y R: letras especiales',
    11: 'Alfabeto completo A–Z',
    12: 'Letras fáciles de confundir: B/D/P/T',
    13: 'Letras fáciles de confundir: E/I/G/J',
    14: 'Dictado de letras aisladas',
    15: 'A corta y A larga: cat/cake',
    16: 'E corta y E larga: bed/he',
    17: 'I corta y I larga: sit/five',
    18: 'O corta y O larga: hot/home',
    19: 'U corta y U larga: cup/cute',
    20: 'Comparación de las cinco vocales cortas',
    21: 'Comparación de las cinco vocales largas',
    22: 'Identificar vocal corta o larga al escuchar',
    23: 'How do you spell it?',
    24: 'Deletrear el nombre',
    25: 'Deletrear el apellido',
    26: 'Mayúsculas y minúsculas',
    27: '@ = at y . = dot',
    28: 'Decir un correo electrónico',
    29: 'B as in book: confirmar una letra',
    30: 'Sorry, D, not B: corregir una letra',
    31: 'Dictado de nombres y correos',
    32: 'Hello y Hi',
    33: 'Good morning',
    34: 'Good afternoon y Good evening',
    35: 'Goodbye, Bye y See you',
    36: 'How are you?',
    37: 'I’m fine / good / tired',
    38: 'Please',
    39: 'Thank you / You’re welcome',
    40: 'Sorry',
    41: 'Excuse me',
    42: 'Yes y No',
    43: 'Mini diálogo de saludo',
    44: 'Listen y Repeat',
    45: 'Read y Write',
    46: 'Look y Choose',
    47: 'Match y Complete',
    48: 'Open y Close',
    49: 'I don’t understand',
    50: 'Can you repeat, please?',
    51: 'Can you speak slowly, please?',
    52: 'What does ___ mean?',
    53: 'Correct / Incorrect / Try again',
    54: 'Números 0–5',
    55: 'Números 6–10',
    56: 'Números 11–15',
    57: 'Números 16–20',
    58: 'Dictado de números 0–20',
    59: 'How old are you? como fórmula',
    60: 'I am ___ years old como fórmula',
    61: 'Decir un número de teléfono lentamente',
    62: 'Escuchar un número de teléfono',
    63: 'Colores primarios',
    64: 'Colores básicos adicionales',
    65: 'Circle, square y triangle',
    66: 'Big y small',
    67: 'Book, notebook, pen y pencil',
    68: 'Chair, table, door y window',
    69: 'This is… como fórmula',
    70: 'It is… como fórmula',
    71: 'A blue book: color + objeto',
    72: 'Reconocer objetos mediante instrucciones',
    73: 'One y many: uno y varios',
    74: 'Artículos a y an',
    75: 'Pronombres I, you, he y she',
    76: 'Am, is y are en frases básicas',
    77: 'Nombres, edad y país en un mini diálogo',
    78: 'Objetos básicos del aula',
    79: 'Objetos básicos de la casa',
    80: 'Familia inmediata: mother, father, sister y brother',
    81: 'Comida básica: bread, rice, water y milk',
    82: 'Ropa básica: shirt, pants, dress y shoes',
    83: 'Partes del cuerpo: head, hands, feet y legs',
    84: 'Animales básicos: dog, cat, bird y fish',
    85: 'Días de la semana',
    86: 'Meses del año',
    87: 'Clima básico: sunny, rainy, hot y cold',
    88: 'Acciones básicas: go, come, eat y drink',
    89: 'Can y can’t como fórmulas',
    90: 'I like / I don’t like como fórmulas',
    91: 'There is / There are como fórmulas',
    92: 'In, on y under',
    93: 'Who, what y where',
    94: 'Preguntas básicas de sí o no',
    95: 'Respuestas cortas: Yes, I am / No, I’m not',
    96: 'Describir un objeto con color y tamaño',
    97: 'Escuchar y elegir la palabra correcta',
    98: 'Leer y relacionar palabras con objetos',
    99: 'Mini conversación de supervivencia',
    100: 'Expresiones esenciales para continuar aprendiendo',
  },

  a1: {
    1: 'Saludos y presentaciones',
    2: 'Preguntar y decir el nombre',
    3: 'Preguntar y decir la edad',
    4: 'Países y nacionalidades',
    5: 'Información de contacto',
    6: 'Profesiones y ocupaciones',
    7: 'Pronombres personales sujeto',
    8: 'El verbo be: am, is y are',
    9: 'Contracciones con be',
    10: 'El verbo be en negativo',
    11: 'Preguntas con be',
    12: 'Respuestas cortas con be',
    13: 'Who, What, Where y How',
    14: 'Adjetivos posesivos: my, your, his y her',
    15: 'Genitivo sajón: Laura’s brother',
    16: 'Have y has para posesión',
    17: 'Familia inmediata y extendida',
    18: 'Hablar de tu familia',
    19: 'Artículos a, an y the',
    20: 'Singular y plural',
    21: 'This, that, these y those',
    22: 'There is y there are',
    23: 'Preguntas y negativos con there is / there are',
    24: 'Some y any',
    25: 'Habitaciones, muebles y objetos de la casa',
    26: 'Describir tu casa',
    27: 'Preposiciones de lugar: in, on y under',
    28: 'Next to, between, behind e in front of',
    29: 'El cuerpo humano y la cara',
    30: 'Describir características físicas',
    31: 'Personalidad básica',
    32: 'Ropa, zapatos y accesorios',
    33: 'Describir lo que lleva puesto una persona',
    34: 'Can y can’t para habilidades',
    35: 'Can para solicitudes y permiso',
    36: 'Imperativos e instrucciones sencillas',
    37: 'Animales y acciones básicas',
    38: 'Sustantivos contables',
    39: 'Sustantivos incontables',
    40: 'Frutas, vegetales, proteínas y cereales',
    41: 'Comidas del día y bebidas',
    42: 'I like / I don’t like',
    43: 'Do you like...?',
    44: 'How much?, How many?, much y many',
    45: 'Cantidades y envases básicos',
    46: 'Pedir comida en un café o restaurante',
    47: 'Can I have...? / I’d like...',
    48: 'Dinero y precios',
    49: 'Comprar ropa y preguntar la talla',
    50: 'Need, want y want to',
    51: 'Rutinas diarias',
    52: 'Presente simple afirmativo',
    53: 'Tercera persona y terminaciones -s / -es',
    54: 'Do y does',
    55: 'Presente simple negativo',
    56: 'Preguntas en presente simple',
    57: 'Respuestas cortas con do y does',
    58: 'Adverbios de frecuencia',
    59: 'Posición de los adverbios de frecuencia',
    60: 'Hablar de tu rutina',
    61: 'Hablar de la rutina de otra persona',
    62: 'La hora: horas exactas',
    63: 'Half past, quarter past y quarter to',
    64: 'Horarios: What time do you...?',
    65: 'At, on e in para expresiones de tiempo',
    66: 'Días, meses y fechas',
    67: 'Números ordinales y cumpleaños',
    68: 'Estaciones del año y clima',
    69: 'Escuela: lugares, objetos y asignaturas',
    70: 'Hablar del trabajo y los estudios',
    71: 'Tiempo libre, hobbies y deportes',
    72: 'Play, go y do con actividades',
    73: 'Lugares de la ciudad',
    74: 'Where is...? y dar direcciones',
    75: 'Turn left, turn right y go straight',
    76: 'Across from, on the corner y near',
    77: 'Transporte: by car, by bus y on foot',
    78: 'Hablar de cómo te transportas',
    79: 'Present continuous afirmativo',
    80: 'Present continuous negativo',
    81: 'Preguntas en present continuous',
    82: 'Acciones que ocurren ahora',
    83: 'Presente simple vs present continuous',
    84: 'Describir una imagen',
    85: 'Vacaciones y lugares para viajar',
    86: 'Hotel, aeropuerto y equipaje',
    87: 'Síntomas y dolores comunes',
    88: 'En la farmacia y en el médico',
    89: 'Should para recomendaciones',
    90: 'Emociones y because',
    91: 'Conectores and, but y or',
    92: 'Orden de la oración: sujeto + verbo + objeto',
    93: 'Object pronouns: me, you, him, her, us y them',
    94: 'Possessive pronouns y Whose...?',
    95: 'Comparativos básicos',
    96: 'Superlativos básicos',
    97: 'Pasado de be: was y were',
    98: 'Pasado simple: verbos regulares e irregulares',
    99: 'Pasado simple negativo y preguntas con did',
    100: 'Planes con be going to',
  },

  a2: {
    1: 'Hábitos vs acciones temporales',
    2: 'Verbos de estado',
    3: 'Verbos irregulares de alta frecuencia',
    4: 'Pronunciación de terminaciones -ed',
    5: 'Narrar acontecimientos pasados',
    6: 'Secuenciadores: first, then, after that, finally',
    7: 'Past continuous: introducción',
    8: 'Past continuous afirmativo y negativo',
    9: 'Preguntas en past continuous',
    10: 'Past simple vs past continuous',
    11: 'When y while',
    12: 'During, for y while',
    13: 'Interrupciones en el pasado',
    14: 'Contar una historia sencilla',
    15: 'Present perfect: introducción',
    16: 'Have / has + past participle',
    17: 'Participios irregulares frecuentes',
    18: 'Experiencias con ever y never',
    19: 'Have you ever...?',
    20: 'Been y gone',
    21: 'Present perfect vs past simple',
    22: 'Just, already y yet',
    23: 'Still, any more, yet y already',
    24: 'Recently y lately',
    25: 'For y since: introducción',
    26: 'How long...?',
    27: 'Hablar de experiencias personales',
    28: 'Futuro con going to',
    29: 'Futuro con will',
    30: 'Predicciones con will',
    31: 'Decisiones espontáneas',
    32: 'Promesas y ofrecimientos con will',
    33: 'Present continuous para planes futuros',
    34: 'Comparar will, going to y present continuous',
    35: 'Planes de viaje',
    36: 'Reservar un hotel',
    37: 'Problemas en un hotel',
    38: 'En el aeropuerto',
    39: 'Vuelos retrasados o cancelados',
    40: 'Pedir y dar direcciones detalladas',
    41: 'Comprar billetes',
    42: 'Comparar medios de transporte',
    43: 'Comida y cocina',
    44: 'Métodos de cocción',
    45: 'Seguir una receta sencilla',
    46: 'Pedir recomendaciones en un restaurante',
    47: 'Alergias y restricciones alimentarias',
    48: 'Quejarse educadamente en un restaurante',
    49: 'Compras y devoluciones',
    50: 'Describir productos',
    51: 'Too y enough',
    52: 'Devolver o cambiar un producto',
    53: 'Comprar por internet',
    54: 'Problemas con pedidos y entregas',
    55: 'Casa y vivienda',
    56: 'Describir una vivienda con detalle',
    57: 'Tareas domésticas',
    58: 'Problemas en casa',
    59: 'Llamar a un técnico',
    60: 'Alquilar una vivienda',
    61: 'Trabajo y profesiones',
    62: 'Responsabilidades laborales',
    63: 'Buscar empleo',
    64: 'Leer una oferta de trabajo',
    65: 'Hablar de experiencia laboral',
    66: 'Entrevistas de trabajo sencillas',
    67: 'Estudios y educación',
    68: 'Describir tu experiencia educativa',
    69: 'Planes académicos',
    70: 'Tecnología cotidiana',
    71: 'Aplicaciones y redes sociales',
    72: 'Problemas tecnológicos',
    73: 'Dar instrucciones técnicas sencillas',
    74: 'Seguridad básica en internet',
    75: 'Salud y bienestar',
    76: 'Síntomas comunes',
    77: 'Describir dolor y molestias',
    78: 'En una consulta médica',
    79: 'Medicamentos e instrucciones',
    80: 'Hábitos saludables',
    81: 'Should y shouldn’t',
    82: 'Must y mustn’t',
    83: 'Have to y don’t have to',
    84: 'Obligación, prohibición y consejo',
    85: 'Comparativos avanzados',
    86: 'As...as',
    87: 'Relative clauses con who, which y that',
    88: 'Something, anything, nothing y everything',
    89: 'Someone, anyone, no one y everyone',
    90: 'Pronombres reflexivos: myself, yourself y themselves',
    91: 'Adjetivos terminados en -ed y -ing',
    92: 'Infinitivo con to',
    93: 'Gerundio después de verbos comunes',
    94: 'First conditional: introducción',
    95: 'Zero conditional',
    96: 'Modales de posibilidad: may y might',
    97: 'Can, could y be able to',
    98: 'Phrasal verbs cotidianos básicos',
    99: 'Conectores: because, so, although',
    100: 'Expresar una opinión',
  },

  b1: {
    1: 'Present simple vs present continuous en contexto',
    2: 'Present perfect vs past simple',
    3: 'Present perfect con for y since',
    4: 'Present perfect continuous: introducción',
    5: 'Present perfect simple vs continuous',
    6: 'Past simple vs past continuous',
    7: 'Past perfect: introducción',
    8: 'Past perfect vs past simple',
    9: 'Narrar acontecimientos en orden',
    10: 'Used to para hábitos pasados',
    11: 'Would para hábitos repetidos del pasado',
    12: 'Used to vs past simple',
    13: 'Hablar de cambios en tu vida',
    14: 'Futuros: will, going to y present continuous',
    15: 'Future continuous: introducción',
    16: 'Planes y predicciones futuras',
    17: 'First conditional: consolidación',
    18: 'When and if en cláusulas futuras',
    19: 'Second conditional: introducción',
    20: 'Situaciones hipotéticas',
    21: 'If I knew... / I wish I knew...',
    22: 'If I were you...',
    23: 'If I had known... / I wish I had known...',
    24: 'Zero, first y second conditional',
    25: 'Modales de obligación',
    26: 'Must vs have to',
    27: 'Should, ought to y had better',
    28: 'Modales de posibilidad',
    29: 'May, might y could',
    30: 'Must y can’t para deducción',
    31: 'Deducciones sobre el presente',
    32: 'Voz pasiva: presente simple',
    33: 'Voz pasiva: pasado simple',
    34: 'Be done, been done y being done',
    35: 'Get passive: get hurt, get paid y get married',
    36: 'Active vs passive',
    37: 'Procesos y productos',
    38: 'Reported speech: introducción',
    39: 'Reported statements',
    40: 'Cambios de tiempo verbal en reported speech',
    41: 'Reported questions',
    42: 'Preguntas indirectas: Do you know where...?',
    43: 'Reported commands y requests',
    44: 'Relative clauses: defining',
    45: 'Who, which, that y where',
    46: 'Omitir el pronombre relativo',
    47: 'Non-defining relative clauses: introducción',
    48: 'Relative clauses con whose, whom y where',
    49: 'Gerunds e infinitives',
    50: 'Verbos seguidos de gerundio',
    51: 'Verbos seguidos de infinitivo',
    52: 'Verb + object + to: I want you to...',
    53: 'Verbos con cambio de significado',
    54: 'Try, need y help con gerundio o infinitivo',
    55: 'Remember doing vs remember to do',
    56: 'Stop doing vs stop to do',
    57: 'Preposición + gerundio',
    58: 'Be/get used to + sustantivo o gerundio',
    59: 'Verbo + preposición + gerundio',
    60: 'There’s no point / It’s worth + gerundio',
    61: 'To, for y so that para expresar propósito',
    62: 'Adjetivo + infinitivo',
    63: 'Afraid to do vs afraid of doing',
    64: 'See someone do vs see someone doing',
    65: 'Cláusulas con -ing',
    66: 'Adjetivos y preposiciones',
    67: 'Interested in, good at y afraid of',
    68: 'Verbos y preposiciones',
    69: 'Depend on, belong to y listen to',
    70: 'Phrasal verbs de vida cotidiana',
    71: 'Phrasal verbs separables',
    72: 'Phrasal verbs inseparables',
    73: 'Get on, get off y get along',
    74: 'Find out, give up y carry on',
    75: 'Look after, look forward to y deal with',
    76: 'Formación de palabras: prefijos',
    77: 'Prefijos negativos',
    78: 'Formación de palabras: sufijos',
    79: 'Sustantivos, verbos, adjetivos y adverbios',
    80: 'Adverbios de manera',
    81: 'Adverbios de grado',
    82: 'Orden de los adjetivos',
    83: 'Adjetivos vs adverbios',
    84: 'Well, fast, late, hard y hardly',
    85: 'So vs such',
    86: 'Quite, rather, pretty y extremely',
    87: 'Comparativos complejos',
    88: 'The more..., the more...',
    89: 'Comparar tendencias y cambios',
    90: 'Trabajo y carrera profesional',
    91: 'Entrevistas de trabajo',
    92: 'Tecnología y vida digital',
    93: 'Salud física',
    94: 'Viajes y turismo',
    95: 'Medio ambiente',
    96: 'Relaciones personales',
    97: 'Noticias y medios',
    98: 'Expresar opiniones con claridad',
    99: 'Escribir un correo formal básico',
    100: 'Escribir una opinión estructurada',
  },

  'b1-plus': {
    1: 'Consolidación de tiempos verbales',
    2: 'Present perfect continuous en profundidad',
    3: 'Past perfect continuous: introducción',
    4: 'Narrativas con múltiples tiempos pasados',
    5: 'Future continuous',
    6: 'Future perfect: introducción',
    7: 'Predicciones y grados de certeza',
    8: 'Second conditional: consolidación',
    9: 'Third conditional: introducción',
    10: 'Arrepentimientos e hipótesis pasadas',
    11: 'Mixed conditionals: introducción',
    12: 'Wish + past simple',
    13: 'Wish + past perfect',
    14: 'Prefer vs would rather',
    15: 'If only',
    16: 'Modales de deducción en el pasado',
    17: 'Must have, might have y can’t have',
    18: 'Should have y shouldn’t have',
    19: 'Could have',
    20: 'Voz pasiva con diferentes tiempos',
    21: 'Passive modals',
    22: 'Have something done: introducción',
    23: 'Reported speech avanzado',
    24: 'Reporting verbs básicos',
    25: 'Advise, suggest, promise y warn',
    26: 'Non-defining relative clauses',
    27: 'Reduced relative clauses: introducción',
    28: 'Participle adjectives',
    29: 'Gerunds e infinitives avanzados',
    30: 'Phrasal verbs frecuentes B1+',
    31: 'Phrasal verbs con get',
    32: 'Phrasal verbs con take',
    33: 'Phrasal verbs con put',
    34: 'Collocations cotidianas',
    35: 'Make vs do',
    36: 'Have, take y get en colocaciones',
    37: 'Intensificadores y mitigadores',
    38: 'Quite, pretty, rather y fairly',
    39: 'Highly, deeply y strongly',
    40: 'Slightly, somewhat y relatively',
    41: 'Expresar certeza e incertidumbre',
    42: 'Apparently, probably y definitely',
    43: 'Expresar actitud y postura',
    44: 'Posición de los adverbios en la oración',
    45: 'Even para énfasis y contraste',
    46: 'Fortunately, surprisingly y understandably',
    47: 'Debatir ventajas y desventajas',
    48: 'Construir argumentos más desarrollados',
    49: 'In case para hablar de precauciones',
    50: 'As para acciones simultáneas y causas',
    51: 'Like vs as',
    52: 'As if y as though',
    53: 'By, until y by the time',
    54: 'On time, in time, at the end e in the end',
    55: 'Contraargumentar',
    56: 'Conceder un punto',
    57: 'Persuadir de manera educada',
    58: 'Negociar una solución',
    59: 'Trabajo: problemas y decisiones',
    60: 'Liderazgo y trabajo en equipo',
    61: 'Comunicación profesional',
    62: 'Presentaciones breves',
    63: 'Educación y desarrollo personal',
    64: 'Metas y progreso',
    65: 'Tecnología y cambios sociales',
    66: 'Inteligencia artificial: conversación general',
    67: 'Medios, información y credibilidad',
    68: 'Naturaleza, animales y conservación',
    69: 'Bienestar animal y responsabilidad humana',
    70: 'Cambio climático y soluciones',
    71: 'Consumo sostenible',
    72: 'Sociedad y comunidad',
    73: 'Cambios generacionales',
    74: 'Cultura e identidad',
    75: 'Viajes y diferencias culturales',
    76: 'Expresar matices en opiniones',
    77: 'Hedging: quizá, probablemente y en cierta medida',
    78: 'Reformular y aclarar ideas complejas',
    79: 'Escribir correos profesionales',
    80: 'Escribir un texto de opinión',
    81: 'Registro formal vs informal en B1+',
    82: 'Mensajes profesionales claros y breves',
    83: 'Responder preguntas durante una presentación',
    84: 'Resumir los puntos principales de una conversación',
    85: 'Conectores avanzados de causa y consecuencia',
    86: 'Despite, in spite of y even though',
    87: 'So, such, too y enough en contexto',
    88: 'Artículos y determinantes en contextos complejos',
    89: 'Cuantificadores: few, little, plenty of y a great deal of',
    90: 'Frases nominales más complejas',
    91: 'Relative clauses: consolidación B1+',
    92: 'Condicionales aplicados a situaciones laborales',
    93: 'Voz pasiva y reporting verbs en noticias',
    94: 'Collocations para trabajo y estudios',
    95: 'Idioms frecuentes en conversaciones cotidianas',
    96: 'Pronunciación y connected speech',
    97: 'Discourse markers para mantener una conversación',
    98: 'Identificar significado implícito al escuchar',
    99: 'Leer y analizar un texto argumentativo',
    100: 'Escribir un texto de problema y solución',
  },

  b2: {
    1: 'Present perfect simple vs continuous avanzado',
    2: 'Past perfect simple vs continuous',
    3: 'Narración avanzada del pasado',
    4: 'Future perfect',
    5: 'Future perfect continuous',
    6: 'Expresar el futuro desde el pasado',
    7: 'Was going to y would',
    8: 'Condicionales mixtos',
    9: 'Alternativas a if',
    10: 'Unless, provided that y as long as',
    11: 'Inversion in conditionals: introducción',
    12: 'Wish y if only avanzados',
    13: 'Would rather',
    14: 'It’s time + past',
    15: 'Modales perfectos',
    16: 'Deducción y especulación sobre el pasado',
    17: 'Crítica y arrepentimiento con modales',
    18: 'Voz pasiva avanzada',
    19: 'Passive reporting structures',
    20: 'It is believed that...',
    21: 'He is said to...',
    22: 'Causative have y get',
    23: 'Reported speech avanzado',
    24: 'Reporting verbs',
    25: 'Deny, admit, insist y recommend',
    26: 'Gerundios e infinitivos complejos',
    27: 'Perfect gerunds e infinitives',
    28: 'Participle clauses',
    29: 'Reduced clauses',
    30: 'Inversion after negative adverbials',
    31: 'Never have I...',
    32: 'Not only... but also',
    33: 'Cleft sentences: introducción',
    34: 'What I need is...',
    35: 'It was... who...',
    36: 'Emphasis con do',
    37: 'Nominalización: introducción',
    38: 'Transformar verbos en sustantivos',
    39: 'Estilo más formal mediante nominalización',
    40: 'Discourse markers avanzados',
    41: 'Furthermore, moreover y nevertheless',
    42: 'On the other hand y in contrast',
    43: 'Consequently y therefore',
    44: 'Conectores para estructurar argumentos',
    45: 'Hedging',
    46: 'Tend to, seem to y appear to',
    47: 'It could be argued that...',
    48: 'Boosters: clearly, undoubtedly y certainly',
    49: 'Matizar afirmaciones',
    50: 'Collocations B2',
    51: 'Adjective + noun collocations',
    52: 'Verb + noun collocations',
    53: 'Adverb + adjective collocations',
    54: 'Phrasal verbs B2',
    55: 'Phrasal verbs con in y out',
    56: 'Phrasal verbs con on y off',
    57: 'Phrasal verbs con up y down',
    58: 'Phrasal verbs con away y back',
    59: 'Phrasal verbs formales e informales',
    60: 'Idioms frecuentes y transparentes',
    61: 'Lenguaje figurado básico',
    62: 'Sinónimos y elección léxica',
    63: 'Evitar repetición',
    64: 'Registro formal vs informal',
    65: 'Cambiar el registro según la situación',
    66: 'Lenguaje diplomático',
    67: 'Softening requests y disagreement',
    68: 'Expresar opiniones complejas',
    69: 'Sustentar una postura',
    70: 'Introducir evidencia y ejemplos',
    71: 'Reconocer contraargumentos',
    72: 'Refutar argumentos',
    73: 'Concluir un argumento',
    74: 'Debates estructurados',
    75: 'Interrumpir y recuperar el turno',
    76: 'Aclarar y reformular',
    77: 'Persuadir',
    78: 'Negociar',
    79: 'Llegar a un consenso',
    80: 'Presentaciones profesionales',
    81: 'Introducir una presentación',
    82: 'Organizar puntos principales',
    83: 'Responder preguntas de una audiencia',
    84: 'Reuniones profesionales',
    85: 'Proponer ideas en reuniones',
    86: 'Expresar reservas',
    87: 'Tomar decisiones en grupo',
    88: 'Trabajo y cultura laboral',
    89: 'Liderazgo',
    90: 'Motivación y productividad',
    91: 'Conflictos laborales',
    92: 'Trabajo remoto',
    93: 'Emprendimiento y negocios',
    94: 'Educación superior',
    95: 'Investigación y aprendizaje',
    96: 'Pensamiento crítico',
    97: 'Tecnología y sociedad',
    98: 'Escribir un ensayo de opinión',
    99: 'Escribir un ensayo de ventajas y desventajas',
    100: 'Escribir un correo formal avanzado',
  },

  c1: {
    1: 'Control avanzado de tiempos verbales',
    2: 'Elección de tiempo verbal según perspectiva',
    3: 'Narración sofisticada',
    4: 'Cambios temporales y aspectuales',
    5: 'Future forms avanzadas',
    6: 'Future in the past',
    7: 'Condicionales avanzados',
    8: 'Inversión en condicionales',
    9: 'Had I known...',
    10: 'Were I to...',
    11: 'Should you need...',
    12: 'Mixed conditionals avanzados',
    13: 'Unreal past',
    14: 'Wish, if only y would rather',
    15: 'Modales avanzados de deducción',
    16: 'Grados de certeza y especulación',
    17: 'Modal perfects en contexto complejo',
    18: 'Voz pasiva y elección de agente',
    19: 'Passive reporting avanzado',
    20: 'Impersonal passive constructions',
    21: 'Causative structures avanzadas',
    22: 'Reported speech con matices',
    23: 'Reporting verbs avanzados',
    24: 'Allege, acknowledge, maintain y claim',
    25: 'Verbos de postura',
    26: 'Participle clauses avanzadas',
    27: 'Reduced clauses avanzadas',
    28: 'Absolute clauses: introducción',
    29: 'Inversión para énfasis',
    30: 'Rarely, scarcely y hardly',
    31: 'No sooner... than',
    32: 'Under no circumstances...',
    33: 'Cleft y pseudo-cleft sentences',
    34: 'Fronting',
    35: 'Énfasis mediante estructura',
    36: 'Nominalización avanzada',
    37: 'Densidad informativa en lenguaje formal',
    38: 'Construcciones impersonales',
    39: 'It is widely accepted that...',
    40: 'Subjunctive formal',
    41: 'It is essential that...',
    42: 'Concesión avanzada',
    43: 'Much as..., while..., whereas...',
    44: 'Conectores académicos',
    45: 'Cohesión y coherencia',
    46: 'Referencia y sustitución',
    47: 'Evitar repetición léxica',
    48: 'Hedging académico',
    49: 'Mitigar afirmaciones',
    50: 'Expresar cautela',
    51: 'Boosting académico',
    52: 'Expresar convicción con precisión',
    53: 'Stance markers',
    54: 'Expresar postura del hablante',
    55: 'Metadiscourse: introducción',
    56: 'Guiar al lector u oyente',
    57: 'Registro y estilo',
    58: 'Formalidad y distancia',
    59: 'Lenguaje coloquial sofisticado',
    60: 'Cambio de registro',
    61: 'Connotación',
    62: 'Denotación vs connotación',
    63: 'Matices entre sinónimos',
    64: 'Elección léxica precisa',
    65: 'Collocations C1',
    66: 'Colocaciones académicas',
    67: 'Colocaciones profesionales',
    68: 'Phrasal verbs avanzados',
    69: 'Phrasal verbs idiomáticos',
    70: 'Idioms y expresiones figuradas',
    71: 'Metáforas conceptuales comunes',
    72: 'Lenguaje figurado en conversación',
    73: 'Ironía y sarcasmo',
    74: 'Understatement y overstatement',
    75: 'Humor y significado implícito',
    76: 'Inferencia pragmática',
    77: 'Leer entre líneas',
    78: 'Implicatura',
    79: 'Presuposición',
    80: 'Ambigüedad intencional',
    81: 'Diplomacia lingüística',
    82: 'Desacuerdo sofisticado',
    83: 'Crítica constructiva',
    84: 'Persuasión avanzada',
    85: 'Técnicas retóricas',
    86: 'Ethos, pathos y logos',
    87: 'Framing de argumentos',
    88: 'Contraargumentación avanzada',
    89: 'Detectar falacias comunes',
    90: 'Evaluar razonamientos',
    91: 'Debates complejos',
    92: 'Gestionar turnos en debates',
    93: 'Responder bajo presión',
    94: 'Sintetizar posiciones distintas',
    95: 'Negociación avanzada',
    96: 'Lenguaje de concesión y compromiso',
    97: 'Mediación de conflictos',
    98: 'Escritura académica: estructura',
    99: 'Parafrasear',
    100: 'Resumir',
  },
};