export const lessonTitles: Record<string, Record<number, string>> = {
  a0: {
    1: 'Presentarte: I am / My name is',
    2: 'Contracciones: I’m / My name’s',
    3: 'A, H, J, K: familia /eɪ/',
    4: 'E, P, G, D: primera familia /iː/',
    5: 'B, C, T, V, Z: segunda familia /iː/',
    6: 'L, M, N: contraste auditivo',
    7: 'F, S, X: familia con vocal /e/',
    8: 'I y Y: contraste y sonido final /aɪ/',
    9: 'Q, U y W: nombres con /juː/',
    10: 'O y R: letras especiales',
    11: 'Alfabeto completo A–Z',
    12: 'Letras fáciles de confundir: B/D/P/T',
    13: 'Letras fáciles de confundir: E/I/G/J',
    14: 'Dictado de letras aisladas',
    15: 'A corta y A larga: cat/cake',
    16: 'E corta y E larga: bed/he',
    17: 'I corta y I larga: sit/five',
    18: 'O corta y O larga: hot/home',
    19: 'U corta y U larga: cup/cute',
    20: 'Comparación de las cinco vocales cortas',
    21: 'Comparación de las cinco vocales largas',
    22: 'Identificar vocal corta o larga al escuchar',
    23: 'How do you spell it?',
    24: 'Deletrear el nombre',
    25: 'Deletrear el apellido',
    26: 'Mayúsculas y minúsculas',
    27: '@ = at y . = dot',
    28: 'Decir un correo electrónico',
    29: 'B as in book: confirmar una letra',
    30: 'Sorry, D, not B: corregir una letra',
    31: 'Dictado de nombres y correos',
    32: 'Hello y Hi',
    33: 'Good morning',
    34: 'Good afternoon y Good evening',
    35: 'Goodbye, Bye y See you',
    36: 'How are you?',
    37: 'I’m fine / good / tired',
    38: 'Please',
    39: 'Thank you / You’re welcome',
    40: 'Sorry',
    41: 'Excuse me',
    42: 'Yes y No',
    43: 'Mini diálogo de saludo',
    44: 'Listen y Repeat',
    45: 'Read y Write',
    46: 'Look y Choose',
    47: 'Match y Complete',
    48: 'Open y Close',
    49: 'I don’t understand',
    50: 'Can you repeat, please?',
    51: 'Can you speak slowly, please?',
    52: 'What does ___ mean?',
    53: 'Correct / Incorrect / Try again',
    54: 'Números 0–5',
    55: 'Números 6–10',
    56: 'Números 11–15',
    57: 'Números 16–20',
    58: 'Dictado de números 0–20',
    59: 'How old are you? como fórmula',
    60: 'I am ___ years old como fórmula',
    61: 'Decir un número de teléfono lentamente',
    62: 'Escuchar un número de teléfono',
    63: 'Colores primarios',
    64: 'Colores básicos adicionales',
    65: 'Circle, square y triangle',
    66: 'Big y small',
    67: 'Book, notebook, pen y pencil',
    68: 'Chair, table, door y window',
    69: 'This is… como fórmula',
    70: 'It is… como fórmula',
    71: 'A blue book: color + objeto',
    72: 'Reconocer objetos mediante instrucciones',
    73: 'Comprensión auditiva A0',
    74: 'Lectura visual A0',
    75: 'Presentación final de 30–45 segundos',
  },

  a1: {
    1: 'Saludos y presentaciones',
    2: 'Preguntar y decir el nombre',
    3: 'Preguntar y decir la edad',
    4: 'Países y nacionalidades',
    5: 'Where are you from?',
    6: 'El verbo be: am, is y are',
    7: 'Contracciones con be',
    8: 'Pronombres personales sujeto',
    9: 'Adjetivos posesivos: my, your, his, her',
    10: 'Información personal básica',
    11: 'Profesiones y ocupaciones',
    12: 'What do you do?',
    13: 'Números 20–100',
    14: 'Números mayores de 100',
    15: 'Direcciones y números de teléfono',
    16: 'Correo electrónico y datos de contacto',
    17: 'Formularios con información personal',
    18: 'Preguntas con be',
    19: 'Respuestas cortas con be',
    20: 'Who, What, Where y How',
    21: 'Familia inmediata',
    22: 'Familia extendida',
    23: 'Hablar de tu familia',
    24: 'Have got / has got',
    25: 'Posesión con have y has',
    26: 'Genitivo sajón: Laura’s brother',
    27: 'Describir relaciones familiares',
    28: 'Estado civil y relaciones',
    29: 'This, that, these y those',
    30: 'Objetos personales',
    31: 'Artículos a y an',
    32: 'El artículo the',
    33: 'Singular y plural',
    34: 'Plurales regulares',
    35: 'Plurales irregulares básicos',
    36: 'There is y there are',
    37: 'Preguntas con there is / there are',
    38: 'Some y any',
    39: 'La casa: habitaciones',
    40: 'Sala y comedor',
    41: 'Dormitorio',
    42: 'Baño',
    43: 'Cocina',
    44: 'Muebles de la casa',
    45: 'Electrodomésticos básicos',
    46: 'Objetos cotidianos del hogar',
    47: 'Describir tu casa',
    48: 'Preposiciones de lugar: in, on, under',
    49: 'Next to, between y behind',
    50: 'In front of, near y opposite',
    51: '¿Dónde están las cosas?',
    52: 'Describir una habitación',
    53: 'Animales domésticos y mascotas',
    54: 'Animales de granja',
    55: 'Animales salvajes comunes',
    56: 'Partes básicas del cuerpo de los animales',
    57: 'Describir un animal',
    58: 'Hablar de tus mascotas',
    59: 'What animal is it?',
    60: 'Can para habilidades',
    61: 'Can’t para habilidades',
    62: 'Lo que los animales pueden hacer',
    63: 'Acciones básicas: run, jump, swim, fly',
    64: 'El cuerpo humano',
    65: 'La cara',
    66: 'Partes externas del cuerpo',
    67: 'Describir características físicas',
    68: 'Tall, short, young y old',
    69: 'Hair y eyes',
    70: 'Adjetivos básicos de apariencia',
    71: 'Describir a una persona',
    72: 'Personalidad básica',
    73: 'Friendly, shy, funny y kind',
    74: 'Ropa básica',
    75: 'Zapatos y accesorios',
    76: 'Colores para describir ropa',
    77: 'What are you wearing?',
    78: 'Wear en presente simple',
    79: 'Describir la ropa de otra persona',
    80: 'Comida: frutas',
    81: 'Comida: vegetales',
    82: 'Carnes y proteínas',
    83: 'Arroz, pasta, pan y cereales',
    84: 'Desayuno',
    85: 'Almuerzo',
    86: 'Cena',
    87: 'Snacks y postres',
    88: 'Bebidas',
    89: 'Comidas favoritas',
    90: 'I like / I don’t like',
    91: 'Do you like...?',
    92: 'Like, love y hate',
    93: 'Countable nouns',
    94: 'Uncountable nouns',
    95: 'A, an y some con comida',
    96: 'How much? y How many?',
    97: 'Much, many y a lot of',
    98: 'Pedir comida de manera básica',
    99: 'En un café',
    100: 'En un restaurante',
    101: 'Can I have...?',
    102: 'I’d like... como fórmula',
    103: 'La cuenta: Can I have the bill?',
    104: 'Rutinas diarias',
    105: 'Wake up y get up',
    106: 'Get dressed y have breakfast',
    107: 'Go to work / go to school',
    108: 'Have lunch y have dinner',
    109: 'Go home y go to bed',
    110: 'Presente simple afirmativo',
    111: 'Tercera persona: he, she, it',
    112: 'Terminaciones -s y -es',
    113: 'Do y does',
    114: 'Presente simple negativo',
    115: 'Preguntas en presente simple',
    116: 'Respuestas cortas con do y does',
    117: 'Adverbios de frecuencia',
    118: 'Always, usually y often',
    119: 'Sometimes, rarely y never',
    120: 'Posición de los adverbios de frecuencia',
    121: 'Hablar de tu rutina',
    122: 'Hablar de la rutina de otra persona',
    123: 'La hora: horas exactas',
    124: 'Half past',
    125: 'Quarter past y quarter to',
    126: 'Minutos con past y to',
    127: 'What time is it?',
    128: 'What time do you...?',
    129: 'Partes del día',
    130: 'Días de la semana',
    131: 'Meses del año',
    132: 'Fechas básicas',
    133: 'Números ordinales',
    134: 'Cumpleaños',
    135: 'Estaciones del año',
    136: 'El clima básico',
    137: 'Sunny, cloudy y rainy',
    138: 'Hot, warm, cool y cold',
    139: 'Windy, snowy y stormy',
    140: 'What’s the weather like?',
    141: 'Ropa según el clima',
    142: 'Actividades según la estación',
    143: 'Escuela: lugares',
    144: 'Objetos escolares',
    145: 'Asignaturas escolares',
    146: 'Hablar de la escuela',
    147: 'Instrucciones del aula',
    148: 'Trabajo: lugares de trabajo',
    149: 'Profesiones comunes',
    150: 'Hablar de tu trabajo',
    151: 'Presente simple para trabajo y estudio',
    152: 'Tiempo libre',
    153: 'Hobbies',
    154: 'Deportes',
    155: 'Música',
    156: 'Películas y televisión',
    157: 'Leer y escribir como pasatiempos',
    158: 'Play, go y do con actividades',
    159: 'Hablar de lo que haces en tu tiempo libre',
    160: 'Can para pedir permiso',
    161: 'Can para hacer solicitudes',
    162: 'Imperativos',
    163: 'Instrucciones sencillas',
    164: 'Lugares de la ciudad',
    165: 'Supermercado',
    166: 'Farmacia',
    167: 'Banco',
    168: 'Hospital',
    169: 'Escuela y universidad',
    170: 'Restaurante y café',
    171: 'Parque y gimnasio',
    172: 'Tiendas',
    173: 'Where is...?',
    174: 'Dar direcciones básicas',
    175: 'Turn left y turn right',
    176: 'Go straight',
    177: 'Across from y on the corner',
    178: 'Preguntar cómo llegar a un lugar',
    179: 'Transporte básico',
    180: 'Car, bus, train y taxi',
    181: 'Bicycle, motorcycle y subway',
    182: 'By car, by bus, on foot',
    183: 'Hablar de cómo te transportas',
    184: 'Compras: tipos de tiendas',
    185: 'Dinero y precios',
    186: 'How much is it?',
    187: 'Tallas de ropa',
    188: 'Comprar ropa',
    189: 'Can I try it on?',
    190: 'This one / that one',
    191: 'Comprar alimentos',
    192: 'Cantidades y envases básicos',
    193: 'A bottle of, a bag of, a box of',
    194: 'Necesidades básicas con need',
    195: 'Want para deseos',
    196: 'Want to + verbo',
    197: 'Present continuous: introducción',
    198: 'Present continuous afirmativo',
    199: 'Present continuous negativo',
    200: 'Preguntas en present continuous',
    201: 'Acciones que ocurren ahora',
    202: 'What are you doing?',
    203: 'Presente simple vs present continuous',
    204: 'Actividades en casa ahora',
    205: 'Actividades fuera de casa ahora',
    206: 'Describir una imagen',
    207: 'Naturaleza: árboles, flores y plantas',
    208: 'Montañas, ríos, playas y océanos',
    209: 'Campo y ciudad',
    210: 'Describir un lugar natural',
    211: 'Vacaciones básicas',
    212: 'Playa, montaña y ciudad',
    213: 'Hotel',
    214: 'Aeropuerto',
    215: 'Equipaje',
    216: 'Pasaporte y boleto',
    217: 'Frases básicas para viajar',
    218: 'Salud: partes del cuerpo en contexto',
    219: 'Dolor: headache, stomachache y toothache',
    220: 'I feel sick / tired / well',
    221: 'En la farmacia',
    222: 'En el médico: frases básicas',
    223: 'Should como recomendación básica',
    224: 'Emociones básicas',
    225: 'Happy, sad, angry y afraid',
    226: 'Excited, bored y worried',
    227: 'How do you feel?',
    228: 'Because para dar una razón sencilla',
    229: 'Conectores and, but y or',
    230: 'Formar oraciones más largas',
    231: 'Object pronouns: me, you, him, her',
    232: 'Us, them e it',
    233: 'Possessive pronouns básicos',
    234: 'Mine, yours, his y hers',
    235: 'Whose...?',
    236: 'Comparativos básicos',
    237: 'Bigger, smaller, older y younger',
    238: 'More expensive / cheaper',
    239: 'Comparar dos personas',
    240: 'Comparar dos objetos',
    241: 'Superlativos básicos',
    242: 'The biggest / the smallest',
    243: 'The best / the worst',
    244: 'Hablar de favoritos',
    245: 'Pasado de be: was y were',
    246: 'Wasn’t y weren’t',
    247: 'Preguntas con was y were',
    248: 'Yesterday, last night y last week',
    249: 'Hablar de dónde estabas',
    250: 'Pasado simple: introducción',
    251: 'Verbos regulares en pasado',
    252: 'Pronunciación básica de -ed',
    253: 'Verbos irregulares frecuentes',
    254: 'Went, had, did, saw y got',
    255: 'Pasado simple negativo',
    256: 'Did en preguntas',
    257: 'Hablar de ayer',
    258: 'Hablar del fin de semana',
    259: 'Planes con be going to',
    260: 'Going to afirmativo',
    261: 'Going to negativo',
    262: 'Preguntas con going to',
    263: 'Hablar de planes del fin de semana',
    264: 'Comprensión integrada A1',
    265: 'Proyecto final A1: hablar de tu vida',
  },

  a2: {
    1: 'Hábitos vs acciones temporales',
    2: 'Verbos de estado',
    3: 'Verbos irregulares de alta frecuencia',
    4: 'Pronunciación de terminaciones -ed',
    5: 'Narrar acontecimientos pasados',
    6: 'Secuenciadores: first, then, after that, finally',
    7: 'Past continuous: introducción',
    8: 'Past continuous afirmativo y negativo',
    9: 'Preguntas en past continuous',
    10: 'Past simple vs past continuous',
    11: 'When y while',
    12: 'Interrupciones en el pasado',
    13: 'Contar una historia sencilla',
    14: 'Present perfect: introducción',
    15: 'Have / has + past participle',
    16: 'Participios irregulares frecuentes',
    17: 'Experiencias con ever y never',
    18: 'Have you ever...?',
    19: 'Been y gone',
    20: 'Present perfect vs past simple',
    21: 'Just, already y yet',
    22: 'Recently y lately',
    23: 'For y since: introducción',
    24: 'How long...?',
    25: 'Hablar de experiencias personales',
    26: 'Futuro con going to',
    27: 'Futuro con will',
    28: 'Predicciones con will',
    29: 'Decisiones espontáneas',
    30: 'Promesas y ofrecimientos con will',
    31: 'Present continuous para planes futuros',
    32: 'Comparar will, going to y present continuous',
    33: 'Planes de viaje',
    34: 'Organizar unas vacaciones',
    35: 'Reservar un hotel',
    36: 'Check-in y check-out',
    37: 'Problemas en un hotel',
    38: 'En el aeropuerto',
    39: 'Facturación y seguridad',
    40: 'Preguntar por una puerta de embarque',
    41: 'Vuelos retrasados o cancelados',
    42: 'Transporte durante un viaje',
    43: 'Pedir y dar direcciones detalladas',
    44: 'Viajar en transporte público',
    45: 'Comprar billetes',
    46: 'Comparar medios de transporte',
    47: 'Comida y cocina',
    48: 'Ingredientes',
    49: 'Utensilios de cocina',
    50: 'Métodos de cocción',
    51: 'Seguir una receta sencilla',
    52: 'Imperativos en recetas',
    53: 'Sequencing en recetas',
    54: 'Comer fuera',
    55: 'Pedir recomendaciones en un restaurante',
    56: 'Expresar preferencias alimentarias',
    57: 'Alergias y restricciones alimentarias',
    58: 'Quejarse educadamente en un restaurante',
    59: 'Compras y devoluciones',
    60: 'Describir productos',
    61: 'Tallas, materiales y colores',
    62: 'Too y enough',
    63: 'This is too expensive',
    64: 'Devolver o cambiar un producto',
    65: 'Comprar por internet',
    66: 'Problemas con pedidos y entregas',
    67: 'Casa y vivienda',
    68: 'Tipos de vivienda',
    69: 'Describir una vivienda con detalle',
    70: 'Electrodomésticos y tecnología del hogar',
    71: 'Tareas domésticas',
    72: 'Problemas en casa',
    73: 'Llamar a un técnico',
    74: 'Mudarse de casa',
    75: 'Alquilar una vivienda',
    76: 'Trabajo y profesiones',
    77: 'Responsabilidades laborales',
    78: 'Horarios y condiciones de trabajo',
    79: 'Buscar empleo',
    80: 'Leer una oferta de trabajo',
    81: 'Hablar de experiencia laboral',
    82: 'Entrevistas de trabajo sencillas',
    83: 'Estudios y educación',
    84: 'Cursos y asignaturas',
    85: 'Describir tu experiencia educativa',
    86: 'Planes académicos',
    87: 'Tecnología cotidiana',
    88: 'Dispositivos electrónicos',
    89: 'Aplicaciones y redes sociales',
    90: 'Problemas tecnológicos',
    91: 'Dar instrucciones técnicas sencillas',
    92: 'Seguridad básica en internet',
    93: 'Salud y bienestar',
    94: 'Síntomas comunes',
    95: 'Describir dolor y molestias',
    96: 'En una consulta médica',
    97: 'Medicamentos e instrucciones',
    98: 'Hábitos saludables',
    99: 'Ejercicio y actividad física',
    100: 'Sueño y descanso',
    101: 'Should y shouldn’t',
    102: 'Must y mustn’t',
    103: 'Have to y don’t have to',
    104: 'Obligación, prohibición y consejo',
    105: 'Animales y mascotas: cuidados',
    106: 'Alimentación y rutinas de mascotas',
    107: 'Describir comportamiento animal',
    108: 'Hábitats de animales',
    109: 'Animales en peligro: introducción',
    110: 'Naturaleza y medio ambiente',
    111: 'Paisajes y accidentes geográficos',
    112: 'Clima y fenómenos meteorológicos',
    113: 'Describir el clima con mayor detalle',
    114: 'Problemas ambientales cotidianos',
    115: 'Reciclaje y hábitos sostenibles',
    116: 'Comparativos avanzados',
    117: 'Much bigger / a little cheaper',
    118: 'As...as',
    119: 'Not as...as',
    120: 'Superlativos y experiencias',
    121: 'The best place I’ve visited',
    122: 'Relative clauses con who, which y that',
    123: 'Describir personas con relative clauses',
    124: 'Describir objetos y lugares',
    125: 'Something, anything, nothing y everything',
    126: 'Someone, anyone, no one y everyone',
    127: 'Adjetivos terminados en -ed y -ing',
    128: 'Bored vs boring',
    129: 'Interested vs interesting',
    130: 'Infinitivo con to',
    131: 'Gerundio después de verbos comunes',
    132: 'Like doing vs would like to do',
    133: 'First conditional: introducción',
    134: 'If + present, will + verb',
    135: 'Situaciones futuras posibles',
    136: 'Unless: introducción',
    137: 'Zero conditional',
    138: 'Hechos y verdades generales',
    139: 'Modales de posibilidad: may y might',
    140: 'Could para posibilidad',
    141: 'Expresar grados de certeza',
    142: 'Phrasal verbs cotidianos básicos',
    143: 'Turn on, turn off y put on',
    144: 'Take off, pick up y look for',
    145: 'Get up, go out y come back',
    146: 'Conectores: because, so, although',
    147: 'However como conector básico',
    148: 'Dar razones y resultados',
    149: 'Expresar una opinión',
    150: 'I think / I don’t think',
    151: 'Agreeing y disagreeing',
    152: 'Explicar preferencias',
    153: 'Invitar y responder invitaciones',
    154: 'Hacer sugerencias',
    155: 'Let’s, shall we y why don’t we',
    156: 'Aceptar y rechazar educadamente',
    157: 'Pedir favores',
    158: 'Ofrecer ayuda',
    159: 'Disculparse y explicar un problema',
    160: 'Hacer una queja sencilla',
    161: 'Resolver un malentendido',
    162: 'Conversaciones telefónicas',
    163: 'Dejar un mensaje',
    164: 'Escribir mensajes y correos informales',
    165: 'Comprensión auditiva integrada A2',
    166: 'Lectura integrada A2',
    167: 'Proyecto final A2: experiencias y planes',
  },

  b1: {
    1: 'Present simple vs present continuous en contexto',
    2: 'Present perfect vs past simple',
    3: 'Present perfect con for y since',
    4: 'Present perfect continuous: introducción',
    5: 'Present perfect simple vs continuous',
    6: 'Past simple vs past continuous',
    7: 'Past perfect: introducción',
    8: 'Past perfect vs past simple',
    9: 'Narrar acontecimientos en orden',
    10: 'Used to para hábitos pasados',
    11: 'Would para hábitos repetidos del pasado',
    12: 'Used to vs past simple',
    13: 'Hablar de cambios en tu vida',
    14: 'Futuros: will, going to y present continuous',
    15: 'Future continuous: introducción',
    16: 'Planes y predicciones futuras',
    17: 'First conditional: consolidación',
    18: 'Second conditional: introducción',
    19: 'Situaciones hipotéticas',
    20: 'If I were you...',
    21: 'Zero, first y second conditional',
    22: 'Modales de obligación',
    23: 'Must vs have to',
    24: 'Should, ought to y had better',
    25: 'Modales de posibilidad',
    26: 'May, might y could',
    27: 'Must y can’t para deducción',
    28: 'Deducciones sobre el presente',
    29: 'Voz pasiva: presente simple',
    30: 'Voz pasiva: pasado simple',
    31: 'Active vs passive',
    32: 'Procesos y productos',
    33: 'Reported speech: introducción',
    34: 'Reported statements',
    35: 'Cambios de tiempo verbal en reported speech',
    36: 'Reported questions',
    37: 'Reported commands y requests',
    38: 'Relative clauses: defining',
    39: 'Who, which, that y where',
    40: 'Omitir el pronombre relativo',
    41: 'Non-defining relative clauses: introducción',
    42: 'Gerunds e infinitives',
    43: 'Verbos seguidos de gerundio',
    44: 'Verbos seguidos de infinitivo',
    45: 'Verbos con cambio de significado',
    46: 'Remember doing vs remember to do',
    47: 'Stop doing vs stop to do',
    48: 'Adjetivos y preposiciones',
    49: 'Interested in, good at y afraid of',
    50: 'Verbos y preposiciones',
    51: 'Depend on, belong to y listen to',
    52: 'Phrasal verbs de vida cotidiana',
    53: 'Phrasal verbs separables',
    54: 'Phrasal verbs inseparables',
    55: 'Get on, get off y get along',
    56: 'Find out, give up y carry on',
    57: 'Look after, look forward to y deal with',
    58: 'Formación de palabras: prefijos',
    59: 'Prefijos negativos',
    60: 'Formación de palabras: sufijos',
    61: 'Sustantivos, verbos, adjetivos y adverbios',
    62: 'Adverbios de manera',
    63: 'Adverbios de grado',
    64: 'Quite, rather, pretty y extremely',
    65: 'Comparativos complejos',
    66: 'The more..., the more...',
    67: 'Comparar tendencias y cambios',
    68: 'Trabajo y carrera profesional',
    69: 'Describir habilidades profesionales',
    70: 'CV y experiencia laboral',
    71: 'Entrevistas de trabajo',
    72: 'Fortalezas y áreas de mejora',
    73: 'Comunicarse con compañeros de trabajo',
    74: 'Reuniones sencillas',
    75: 'Expresar acuerdo y desacuerdo profesional',
    76: 'Educación y aprendizaje',
    77: 'Métodos de estudio',
    78: 'Describir fortalezas académicas',
    79: 'Aprendizaje presencial vs en línea',
    80: 'Tecnología y vida digital',
    81: 'Ventajas y desventajas de la tecnología',
    82: 'Redes sociales y comunicación',
    83: 'Privacidad digital',
    84: 'Problemas tecnológicos y soluciones',
    85: 'Salud física',
    86: 'Hábitos saludables y poco saludables',
    87: 'Ejercicio y estilo de vida',
    88: 'Estrés y bienestar',
    89: 'Dar consejos detallados',
    90: 'Comida, nutrición y hábitos',
    91: 'Dietas y preferencias alimentarias',
    92: 'Cocinar y describir recetas',
    93: 'Cultura gastronómica',
    94: 'Viajes y turismo',
    95: 'Experiencias de viaje',
    96: 'Problemas durante un viaje',
    97: 'Turismo responsable',
    98: 'Comparar destinos',
    99: 'Animales y comportamiento',
    100: 'Mascotas y responsabilidad',
    101: 'Animales salvajes y hábitats',
    102: 'Conservación de especies',
    103: 'Relación entre humanos y animales',
    104: 'Medio ambiente',
    105: 'Cambio climático: vocabulario esencial',
    106: 'Contaminación',
    107: 'Reciclaje y consumo',
    108: 'Energías renovables: introducción',
    109: 'Proponer soluciones ambientales',
    110: 'Ciudad y vida urbana',
    111: 'Ventajas y desventajas de vivir en una ciudad',
    112: 'Vida rural',
    113: 'Servicios públicos',
    114: 'Transporte y movilidad',
    115: 'Vivienda y comunidad',
    116: 'Problemas de vivienda',
    117: 'Relaciones personales',
    118: 'Amistad',
    119: 'Familia y generaciones',
    120: 'Resolver conflictos',
    121: 'Expresar sentimientos complejos',
    122: 'Entretenimiento y cultura',
    123: 'Películas y series',
    124: 'Libros y lectura',
    125: 'Música y conciertos',
    126: 'Describir y recomendar entretenimiento',
    127: 'Noticias y medios',
    128: 'Tipos de medios de comunicación',
    129: 'Distinguir hechos y opiniones',
    130: 'Hablar de noticias recientes',
    131: 'Publicidad',
    132: 'Compras y comportamiento del consumidor',
    133: 'Dinero y presupuesto personal',
    134: 'Ahorrar y gastar',
    135: 'Servicios bancarios cotidianos',
    136: 'Expresar opiniones con claridad',
    137: 'Dar razones y ejemplos',
    138: 'Organizar un argumento sencillo',
    139: 'Conectores de contraste',
    140: 'Although, even though y despite',
    141: 'Conectores de causa y consecuencia',
    142: 'Therefore, as a result y because of',
    143: 'Hacer sugerencias y negociar',
    144: 'Resolver problemas en conversación',
    145: 'Pedir aclaraciones',
    146: 'Reformular una idea',
    147: 'Interrumpir educadamente',
    148: 'Mantener una conversación',
    149: 'Escribir un correo formal básico',
    150: 'Escribir una opinión estructurada',
    151: 'Comprensión auditiva integrada B1',
    152: 'Lectura integrada B1',
    153: 'Proyecto final B1: defender una opinión',
  },

  'b1-plus': {
    1: 'Consolidación de tiempos verbales',
    2: 'Present perfect continuous en profundidad',
    3: 'Past perfect continuous: introducción',
    4: 'Narrativas con múltiples tiempos pasados',
    5: 'Future continuous',
    6: 'Future perfect: introducción',
    7: 'Predicciones y grados de certeza',
    8: 'Second conditional: consolidación',
    9: 'Third conditional: introducción',
    10: 'Arrepentimientos e hipótesis pasadas',
    11: 'Mixed conditionals: introducción',
    12: 'Wish + past simple',
    13: 'Wish + past perfect',
    14: 'If only',
    15: 'Modales de deducción en el pasado',
    16: 'Must have, might have y can’t have',
    17: 'Should have y shouldn’t have',
    18: 'Could have',
    19: 'Voz pasiva con diferentes tiempos',
    20: 'Passive modals',
    21: 'Have something done: introducción',
    22: 'Reported speech avanzado',
    23: 'Reporting verbs básicos',
    24: 'Advise, suggest, promise y warn',
    25: 'Non-defining relative clauses',
    26: 'Reduced relative clauses: introducción',
    27: 'Participle adjectives',
    28: 'Gerunds e infinitives avanzados',
    29: 'Phrasal verbs frecuentes B1+',
    30: 'Phrasal verbs con get',
    31: 'Phrasal verbs con take',
    32: 'Phrasal verbs con put',
    33: 'Collocations cotidianas',
    34: 'Make vs do',
    35: 'Have, take y get en colocaciones',
    36: 'Intensificadores y mitigadores',
    37: 'Highly, deeply y strongly',
    38: 'Slightly, somewhat y relatively',
    39: 'Expresar certeza e incertidumbre',
    40: 'Apparently, probably y definitely',
    41: 'Expresar actitud y postura',
    42: 'Fortunately, surprisingly y understandably',
    43: 'Debatir ventajas y desventajas',
    44: 'Construir argumentos más desarrollados',
    45: 'Contraargumentar',
    46: 'Conceder un punto',
    47: 'Persuadir de manera educada',
    48: 'Negociar una solución',
    49: 'Trabajo: problemas y decisiones',
    50: 'Liderazgo y trabajo en equipo',
    51: 'Comunicación profesional',
    52: 'Presentaciones breves',
    53: 'Educación y desarrollo personal',
    54: 'Metas y progreso',
    55: 'Tecnología y cambios sociales',
    56: 'Inteligencia artificial: conversación general',
    57: 'Medios, información y credibilidad',
    58: 'Naturaleza, animales y conservación',
    59: 'Bienestar animal y responsabilidad humana',
    60: 'Cambio climático y soluciones',
    61: 'Consumo sostenible',
    62: 'Sociedad y comunidad',
    63: 'Cambios generacionales',
    64: 'Cultura e identidad',
    65: 'Viajes y diferencias culturales',
    66: 'Expresar matices en opiniones',
    67: 'Hedging: quizá, probablemente y en cierta medida',
    68: 'Reformular y aclarar ideas complejas',
    69: 'Escribir correos profesionales',
    70: 'Escribir un texto de opinión',
    71: 'Comprensión auditiva integrada B1+',
    72: 'Lectura integrada B1+',
    73: 'Proyecto final B1+: debate estructurado',
  },

  b2: {
    1: 'Revisión avanzada del sistema verbal',
    2: 'Present perfect simple vs continuous avanzado',
    3: 'Past perfect simple vs continuous',
    4: 'Narración avanzada del pasado',
    5: 'Future perfect',
    6: 'Future perfect continuous',
    7: 'Expresar el futuro desde el pasado',
    8: 'Was going to y would',
    9: 'Condicionales mixtos',
    10: 'Alternativas a if',
    11: 'Unless, provided that y as long as',
    12: 'Inversion in conditionals: introducción',
    13: 'Wish y if only avanzados',
    14: 'Would rather',
    15: 'It’s time + past',
    16: 'Modales perfectos',
    17: 'Deducción y especulación sobre el pasado',
    18: 'Crítica y arrepentimiento con modales',
    19: 'Voz pasiva avanzada',
    20: 'Passive reporting structures',
    21: 'It is believed that...',
    22: 'He is said to...',
    23: 'Causative have y get',
    24: 'Reported speech avanzado',
    25: 'Reporting verbs',
    26: 'Deny, admit, insist y recommend',
    27: 'Gerundios e infinitivos complejos',
    28: 'Perfect gerunds e infinitives',
    29: 'Participle clauses',
    30: 'Reduced clauses',
    31: 'Inversion after negative adverbials',
    32: 'Never have I...',
    33: 'Not only... but also',
    34: 'Cleft sentences: introducción',
    35: 'What I need is...',
    36: 'It was... who...',
    37: 'Emphasis con do',
    38: 'Nominalización: introducción',
    39: 'Transformar verbos en sustantivos',
    40: 'Estilo más formal mediante nominalización',
    41: 'Discourse markers avanzados',
    42: 'Furthermore, moreover y nevertheless',
    43: 'On the other hand y in contrast',
    44: 'Consequently y therefore',
    45: 'Conectores para estructurar argumentos',
    46: 'Hedging',
    47: 'Tend to, seem to y appear to',
    48: 'It could be argued that...',
    49: 'Boosters: clearly, undoubtedly y certainly',
    50: 'Matizar afirmaciones',
    51: 'Collocations B2',
    52: 'Adjective + noun collocations',
    53: 'Verb + noun collocations',
    54: 'Adverb + adjective collocations',
    55: 'Phrasal verbs B2',
    56: 'Phrasal verbs formales e informales',
    57: 'Idioms frecuentes y transparentes',
    58: 'Lenguaje figurado básico',
    59: 'Sinónimos y elección léxica',
    60: 'Evitar repetición',
    61: 'Registro formal vs informal',
    62: 'Cambiar el registro según la situación',
    63: 'Lenguaje diplomático',
    64: 'Softening requests y disagreement',
    65: 'Expresar opiniones complejas',
    66: 'Sustentar una postura',
    67: 'Introducir evidencia y ejemplos',
    68: 'Reconocer contraargumentos',
    69: 'Refutar argumentos',
    70: 'Concluir un argumento',
    71: 'Debates estructurados',
    72: 'Interrumpir y recuperar el turno',
    73: 'Aclarar y reformular',
    74: 'Persuadir',
    75: 'Negociar',
    76: 'Llegar a un consenso',
    77: 'Presentaciones profesionales',
    78: 'Introducir una presentación',
    79: 'Organizar puntos principales',
    80: 'Responder preguntas de una audiencia',
    81: 'Reuniones profesionales',
    82: 'Proponer ideas en reuniones',
    83: 'Expresar reservas',
    84: 'Tomar decisiones en grupo',
    85: 'Trabajo y cultura laboral',
    86: 'Liderazgo',
    87: 'Motivación y productividad',
    88: 'Conflictos laborales',
    89: 'Trabajo remoto',
    90: 'Emprendimiento y negocios',
    91: 'Educación superior',
    92: 'Investigación y aprendizaje',
    93: 'Pensamiento crítico',
    94: 'Evaluar argumentos',
    95: 'Tecnología y sociedad',
    96: 'Inteligencia artificial',
    97: 'Privacidad y datos',
    98: 'Automatización y empleo',
    99: 'Redes sociales y comportamiento',
    100: 'Medios y desinformación',
    101: 'Identificar sesgo',
    102: 'Evaluar fuentes',
    103: 'Publicidad y persuasión',
    104: 'Salud pública y estilo de vida',
    105: 'Salud mental y bienestar',
    106: 'Sistemas de salud',
    107: 'Ciencia y medicina en los medios',
    108: 'Medio ambiente y sostenibilidad',
    109: 'Cambio climático',
    110: 'Biodiversidad',
    111: 'Conservación de animales y hábitats',
    112: 'Bienestar animal y ética',
    113: 'Energía y recursos naturales',
    114: 'Ciudades sostenibles',
    115: 'Sociedad y desigualdad',
    116: 'Educación y oportunidades',
    117: 'Cambios demográficos',
    118: 'Migración y movilidad',
    119: 'Cultura e identidad',
    120: 'Tradiciones y cambio cultural',
    121: 'Globalización',
    122: 'Comunicación intercultural',
    123: 'Arte y creatividad',
    124: 'Literatura y narrativa',
    125: 'Cine y análisis',
    126: 'Música y cultura',
    127: 'Turismo y patrimonio',
    128: 'Ética del turismo',
    129: 'Economía cotidiana',
    130: 'Consumo y finanzas personales',
    131: 'Escribir un ensayo de opinión',
    132: 'Escribir un ensayo de ventajas y desventajas',
    133: 'Escribir un correo formal avanzado',
    134: 'Proyecto final B2: presentación y debate',
  },

  c1: {
    1: 'Control avanzado de tiempos verbales',
    2: 'Elección de tiempo verbal según perspectiva',
    3: 'Narración sofisticada',
    4: 'Cambios temporales y aspectuales',
    5: 'Future forms avanzadas',
    6: 'Future in the past',
    7: 'Condicionales avanzados',
    8: 'Inversión en condicionales',
    9: 'Had I known...',
    10: 'Were I to...',
    11: 'Should you need...',
    12: 'Mixed conditionals avanzados',
    13: 'Unreal past',
    14: 'Wish, if only y would rather',
    15: 'Modales avanzados de deducción',
    16: 'Grados de certeza y especulación',
    17: 'Modal perfects en contexto complejo',
    18: 'Voz pasiva y elección de agente',
    19: 'Passive reporting avanzado',
    20: 'Impersonal passive constructions',
    21: 'Causative structures avanzadas',
    22: 'Reported speech con matices',
    23: 'Reporting verbs avanzados',
    24: 'Allege, acknowledge, maintain y claim',
    25: 'Verbos de postura',
    26: 'Participle clauses avanzadas',
    27: 'Reduced clauses avanzadas',
    28: 'Absolute clauses: introducción',
    29: 'Inversión para énfasis',
    30: 'Rarely, scarcely y hardly',
    31: 'No sooner... than',
    32: 'Under no circumstances...',
    33: 'Cleft y pseudo-cleft sentences',
    34: 'Fronting',
    35: 'Énfasis mediante estructura',
    36: 'Nominalización avanzada',
    37: 'Densidad informativa en lenguaje formal',
    38: 'Construcciones impersonales',
    39: 'It is widely accepted that...',
    40: 'Subjunctive formal',
    41: 'It is essential that...',
    42: 'Concesión avanzada',
    43: 'Much as..., while..., whereas...',
    44: 'Conectores académicos',
    45: 'Cohesión y coherencia',
    46: 'Referencia y sustitución',
    47: 'Evitar repetición léxica',
    48: 'Hedging académico',
    49: 'Mitigar afirmaciones',
    50: 'Expresar cautela',
    51: 'Boosting académico',
    52: 'Expresar convicción con precisión',
    53: 'Stance markers',
    54: 'Expresar postura del hablante',
    55: 'Metadiscourse: introducción',
    56: 'Guiar al lector u oyente',
    57: 'Registro y estilo',
    58: 'Formalidad y distancia',
    59: 'Lenguaje coloquial sofisticado',
    60: 'Cambio de registro',
    61: 'Connotación',
    62: 'Denotación vs connotación',
    63: 'Matices entre sinónimos',
    64: 'Elección léxica precisa',
    65: 'Collocations C1',
    66: 'Colocaciones académicas',
    67: 'Colocaciones profesionales',
    68: 'Phrasal verbs avanzados',
    69: 'Phrasal verbs idiomáticos',
    70: 'Idioms y expresiones figuradas',
    71: 'Metáforas conceptuales comunes',
    72: 'Lenguaje figurado en conversación',
    73: 'Ironía y sarcasmo',
    74: 'Understatement y overstatement',
    75: 'Humor y significado implícito',
    76: 'Inferencia pragmática',
    77: 'Leer entre líneas',
    78: 'Implicatura',
    79: 'Presuposición',
    80: 'Ambigüedad intencional',
    81: 'Diplomacia lingüística',
    82: 'Desacuerdo sofisticado',
    83: 'Crítica constructiva',
    84: 'Persuasión avanzada',
    85: 'Técnicas retóricas',
    86: 'Ethos, pathos y logos',
    87: 'Framing de argumentos',
    88: 'Contraargumentación avanzada',
    89: 'Detectar falacias comunes',
    90: 'Evaluar razonamientos',
    91: 'Debates complejos',
    92: 'Gestionar turnos en debates',
    93: 'Responder bajo presión',
    94: 'Sintetizar posiciones distintas',
    95: 'Negociación avanzada',
    96: 'Lenguaje de concesión y compromiso',
    97: 'Mediación de conflictos',
    98: 'Reformular para terceros',
    99: 'Presentaciones de alto nivel',
    100: 'Storytelling en presentaciones',
    101: 'Persuadir a una audiencia',
    102: 'Responder preguntas difíciles',
    103: 'Comunicación profesional avanzada',
    104: 'Reuniones complejas',
    105: 'Liderazgo comunicativo',
    106: 'Feedback profesional',
    107: 'Negociaciones laborales',
    108: 'Comunicación intercultural profesional',
    109: 'Escritura académica: estructura',
    110: 'Introducciones académicas',
    111: 'Desarrollar párrafos argumentativos',
    112: 'Conclusiones académicas',
    113: 'Parafrasear',
    114: 'Resumir',
    115: 'Sintetizar múltiples ideas',
    116: 'Integrar evidencia',
    117: 'Citar y atribuir ideas en lenguaje',
    118: 'Evitar afirmaciones absolutas',
    119: 'Escritura profesional avanzada',
    120: 'Correos delicados',
    121: 'Informes',
    122: 'Propuestas',
    123: 'Resúmenes ejecutivos',
    124: 'Tecnología, IA y ética',
    125: 'Automatización y futuro del trabajo',
    126: 'Privacidad, vigilancia y datos',
    127: 'Desinformación y confianza digital',
    128: 'Ciencia y pensamiento crítico',
    129: 'Comunicar incertidumbre científica',
    130: 'Salud, medicina y sociedad',
    131: 'Bioética: discusión general',
    132: 'Medio ambiente y políticas sostenibles',
    133: 'Crisis climática y adaptación',
    134: 'Biodiversidad y pérdida de hábitats',
    135: 'Conservación y bienestar animal',
    136: 'Relación ética entre humanos y animales',
    137: 'Economía y desigualdad',
    138: 'Trabajo y cambios económicos',
    139: 'Educación y movilidad social',
    140: 'Sociedad, identidad y pertenencia',
    141: 'Diversidad cultural',
    142: 'Globalización e identidad',
    143: 'Lengua y cultura',
    144: 'Arte como comentario social',
    145: 'Literatura y perspectiva',
    146: 'Cine y representación',
    147: 'Medios, narrativa y opinión pública',
    148: 'Viajes, cultura y ética',
    149: 'Analizar un texto complejo',
    150: 'Identificar tono y postura',
    151: 'Identificar intención e implicación',
    152: 'Sintetizar información oral compleja',
    153: 'Conversación espontánea C1',
    154: 'Defender una postura compleja',
    155: 'Reformular cuando falta una palabra',
    156: 'Comprensión integrada C1',
    157: 'Proyecto final C1: presentación, debate y síntesis',
  },
};

export function getLessonTitle(
  level: string,
  lessonNumber: number,
) {
  return (
    lessonTitles[level.toLowerCase()]?.[lessonNumber] ??
    `Lección ${lessonNumber}`
  );
}