import type { LessonContent } from '../types';

const lessonB2004: LessonContent = {
  level: 'b2',
  number: 4,
  title: 'Future perfect',
  subtitle: 'Aprende a hablar de acciones que estarán completadas antes de un momento en el futuro, con by y by the time.',
  videoTitle: 'Future perfect',
  videoDescription: 'En este video verás la formación del future perfect (will have + participio) en afirmativo, negativo y preguntas, y cómo usar by y by the time.',
  objective: 'Al terminar, podrás decir qué habrá pasado antes de un momento futuro y hacer oraciones negativas y preguntas con future perfect.',
  exercises: [
    {
      type: 'fill-in-the-blanks',
      title: 'Completa con el participio',
      instructions: 'Escribe el verbo en participio (V3). Recuerda que los verbos irregulares tienen su propia forma.',
      questions: [
        {
          id: 1,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'my', translation: 'mi' },
            { word: 'homework', translation: 'tarea' },
            { word: 'by', translation: 'para / antes de' },
            { word: '8:00.', translation: 'las 8:00' },
          ],
          answer: 'finished',
          hint: 'finish',
          sentenceTranslation: 'Habré terminado mi tarea a las 8:00.',
        },
        {
          id: 2,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'by', translation: 'para / antes de' },
            { word: 'the', translation: 'el/la' },
            { word: 'time', translation: 'hora' },
            { word: 'we', translation: 'nosotros' },
            { word: 'arrive.', translation: 'llegar' },
          ],
          answer: 'left',
          hint: 'leave',
          sentenceTranslation: 'Ella se habrá ido para cuando lleguemos.',
        },
        {
          id: 3,
          before: [
            { word: 'We', translation: 'nosotros' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'enough', translation: 'suficiente' },
            { word: 'money', translation: 'dinero' },
            { word: 'by', translation: 'para / antes de' },
            { word: 'December.', translation: 'diciembre' },
          ],
          answer: 'saved',
          hint: 'save',
          sentenceTranslation: 'Habremos ahorrado suficiente dinero para diciembre.',
        },
        {
          id: 4,
          before: [
            { word: 'They', translation: 'ellos' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'the', translation: 'el/la' },
            { word: 'house', translation: 'casa' },
            { word: 'by', translation: 'para / antes de' },
            { word: 'next', translation: 'próximo' },
            { word: 'year.', translation: 'año' },
          ],
          answer: 'built',
          hint: 'build',
          sentenceTranslation: 'Habrán construido la casa para el próximo año.',
        },
        {
          id: 5,
          before: [
            { word: 'He', translation: 'él' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'the', translation: 'el/la' },
            { word: 'book', translation: 'libro' },
            { word: 'by', translation: 'para / antes de' },
            { word: 'Friday.', translation: 'viernes' },
          ],
          answer: 'read',
          hint: 'read',
          sentenceTranslation: 'Él habrá leído el libro para el viernes.',
        },
        {
          id: 6,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: '2030,', translation: '2030' },
            { word: 'I', translation: 'yo' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'three', translation: 'tres' },
            { word: 'languages.', translation: 'idiomas' },
          ],
          answer: 'learned',
          hint: 'learn',
          sentenceTranslation: 'Para 2030, habré aprendido tres idiomas.',
        },
        {
          id: 7,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: 'the', translation: 'el/la' },
            { word: 'time', translation: 'hora' },
            { word: 'you', translation: 'tú' },
            { word: 'arrive,', translation: 'llegar' },
            { word: 'I', translation: 'yo' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'dinner.', translation: 'cena' },
          ],
          answer: 'cooked',
          hint: 'cook',
          sentenceTranslation: 'Para cuando llegues, habré cocinado la cena.',
        },
        {
          id: 8,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'by', translation: 'para / antes de' },
            { word: 'next', translation: 'próximo' },
            { word: 'year.', translation: 'año' },
          ],
          answer: 'graduated',
          hint: 'graduate',
          sentenceTranslation: 'Ella se habrá graduado para el próximo año.',
        },
        {
          id: 9,
          before: [
            { word: 'They', translation: 'ellos' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'before', translation: 'antes de' },
            { word: 'the', translation: 'el/la' },
            { word: 'meeting', translation: 'reunión' },
            { word: 'starts.', translation: 'empieza' },
          ],
          answer: 'eaten',
          hint: 'eat',
          sentenceTranslation: 'Habrán comido antes de que empiece la reunión.',
        },
        {
          id: 10,
          before: [
            { word: 'We', translation: 'nosotros' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'all', translation: 'todos' },
            { word: 'the', translation: 'el/la' },
            { word: 'exercises', translation: 'ejercicios' },
            { word: 'by', translation: 'para / antes de' },
            { word: 'noon.', translation: 'mediodía' },
          ],
          answer: 'done',
          hint: 'do',
          sentenceTranslation: 'Habremos hecho todos los ejercicios para el mediodía.',
        },
        {
          id: 11,
          before: [
            { word: 'He', translation: 'él' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'a', translation: 'un/una' },
            { word: 'doctor', translation: 'doctor' },
            { word: 'by', translation: 'para / antes de' },
            { word: '2030.', translation: '2030' },
          ],
          answer: 'become',
          hint: 'become',
          sentenceTranslation: 'Él se habrá convertido en doctor para 2030.',
        },
        {
          id: 12,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'store', translation: 'tienda' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'by', translation: 'para / antes de' },
            { word: 'the', translation: 'el/la' },
            { word: 'time', translation: 'hora' },
            { word: 'we', translation: 'nosotros' },
            { word: 'get', translation: 'lleguemos' },
            { word: 'there.', translation: 'allá' },
          ],
          answer: 'closed',
          hint: 'close',
          sentenceTranslation: 'La tienda habrá cerrado para cuando lleguemos allá.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Will, have o not',
      instructions: 'Escribe la palabra que falta para formar el future perfect: will + have + participio.',
      questions: [
        {
          id: 13,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'will', translation: 'auxiliar de futuro' },
          ],
          after: [
            { word: 'arrived', translation: 'llegado' },
            { word: 'by', translation: 'para / antes de' },
            { word: '6:00.', translation: 'las 6:00' },
          ],
          answer: 'have',
          sentenceTranslation: 'Ella habrá llegado para las 6:00.',
        },
        {
          id: 14,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'will', translation: 'auxiliar de futuro' },
          ],
          after: [
            { word: 'have', translation: 'haber' },
            { word: 'finished', translation: 'terminado' },
            { word: 'my', translation: 'mi' },
            { word: 'report', translation: 'informe' },
            { word: 'by', translation: 'para / antes de' },
            { word: 'noon.', translation: 'mediodía' },
          ],
          answer: 'not',
          sentenceTranslation: 'No habré terminado mi informe para el mediodía.',
        },
        {
          id: 15,
          before: [],
          after: [
            { word: 'you', translation: 'tú' },
            { word: 'have', translation: 'haber' },
            { word: 'finished', translation: 'terminado' },
            { word: 'the', translation: 'el/la' },
            { word: 'laundry', translation: 'ropa sucia' },
            { word: 'by', translation: 'para / antes de' },
            { word: 'the', translation: 'el/la' },
            { word: 'time', translation: 'hora' },
            { word: 'he', translation: 'él' },
            { word: 'comes', translation: 'llega' },
            { word: 'home?', translation: 'a casa' },
          ],
          answer: 'Will',
          sentenceTranslation: '¿Habrás terminado la ropa para cuando él llegue a casa?',
        },
        {
          id: 16,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: 'the', translation: 'el/la' },
            { word: 'time', translation: 'hora' },
            { word: 'he', translation: 'él' },
            { word: 'wakes', translation: 'despierta' },
            { word: 'up,', translation: 'arriba' },
            { word: 'we', translation: 'nosotros' },
            { word: 'will', translation: 'auxiliar de futuro' },
          ],
          after: [
            { word: 'left.', translation: 'salido' },
          ],
          answer: 'have',
          sentenceTranslation: 'Para cuando él despierte, nos habremos ido.',
        },
        {
          id: 17,
          before: [
            { word: 'They', translation: 'ellos' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'not', translation: 'no' },
          ],
          after: [
            { word: 'cleaned', translation: 'limpiado' },
            { word: 'the', translation: 'el/la' },
            { word: 'house', translation: 'casa' },
            { word: 'before', translation: 'antes de' },
            { word: 'the', translation: 'el/la' },
            { word: 'guests', translation: 'invitados' },
            { word: 'arrive.', translation: 'llegar' },
          ],
          answer: 'have',
          sentenceTranslation: 'No habrán limpiado la casa antes de que lleguen los invitados.',
        },
        {
          id: 18,
          before: [],
          after: [
            { word: 'she', translation: 'ella' },
            { word: 'have', translation: 'haber' },
            { word: 'arrived', translation: 'llegado' },
            { word: 'by', translation: 'para / antes de' },
            { word: '6:00?', translation: 'las 6:00' },
          ],
          answer: 'Will',
          sentenceTranslation: '¿Habrá llegado ella para las 6:00?',
        },
        {
          id: 19,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: 'next', translation: 'próximo' },
            { word: 'year,', translation: 'año' },
            { word: 'I', translation: 'yo' },
            { word: 'will', translation: 'auxiliar de futuro' },
          ],
          after: [
            { word: 'finished', translation: 'terminado' },
            { word: 'my', translation: 'mi' },
            { word: 'degree.', translation: 'carrera' },
          ],
          answer: 'have',
          sentenceTranslation: 'Para el próximo año, habré terminado mi carrera.',
        },
        {
          id: 20,
          before: [
            { word: 'We', translation: 'nosotros' },
          ],
          after: [
            { word: 'have', translation: 'haber' },
            { word: 'saved', translation: 'ahorrado' },
            { word: 'enough', translation: 'suficiente' },
            { word: 'money', translation: 'dinero' },
            { word: 'by', translation: 'para / antes de' },
            { word: 'December.', translation: 'diciembre' },
          ],
          answer: 'will',
          sentenceTranslation: 'Habremos ahorrado suficiente dinero para diciembre.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 21,
          tokens: [
            { id: 'q21-i', word: 'I', translation: 'yo' },
            {
              id: 'q21-will',
              word: 'will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q21-have', word: 'have', translation: 'haber' },
            {
              id: 'q21-finished',
              word: 'finished',
              translation: 'terminado',
            },
            { id: 'q21-my', word: 'my', translation: 'mi' },
            { id: 'q21-homework', word: 'homework', translation: 'tarea' },
            { id: 'q21-by', word: 'by', translation: 'para / antes de' },
            { id: 'q21-800', word: '8:00.', translation: 'las 8:00' },
          ],
          correctOrder: ['q21-i', 'q21-will', 'q21-have', 'q21-finished', 'q21-my', 'q21-homework', 'q21-by', 'q21-800'],
          sentenceTranslation: 'Habré terminado mi tarea a las 8:00.',
        },
        {
          id: 22,
          tokens: [
            { id: 'q22-she', word: 'She', translation: 'ella' },
            {
              id: 'q22-will',
              word: 'will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q22-have', word: 'have', translation: 'haber' },
            { id: 'q22-left', word: 'left', translation: 'salido' },
            { id: 'q22-by', word: 'by', translation: 'para / antes de' },
            { id: 'q22-the', word: 'the', translation: 'el/la' },
            { id: 'q22-time', word: 'time', translation: 'hora' },
            { id: 'q22-we', word: 'we', translation: 'nosotros' },
            { id: 'q22-arrive', word: 'arrive.', translation: 'llegar' },
          ],
          correctOrder: ['q22-she', 'q22-will', 'q22-have', 'q22-left', 'q22-by', 'q22-the', 'q22-time', 'q22-we', 'q22-arrive'],
          sentenceTranslation: 'Ella se habrá ido para cuando lleguemos.',
        },
        {
          id: 23,
          tokens: [
            { id: 'q23-they', word: 'They', translation: 'ellos' },
            { id: 'q23-wont', word: 'won’t', translation: 'no (futuro)' },
            { id: 'q23-have', word: 'have', translation: 'haber' },
            { id: 'q23-cleaned', word: 'cleaned', translation: 'limpiado' },
            { id: 'q23-the', word: 'the', translation: 'el/la' },
            { id: 'q23-house', word: 'house', translation: 'casa' },
            { id: 'q23-before', word: 'before', translation: 'antes de' },
            { id: 'q23-noon', word: 'noon.', translation: 'mediodía' },
          ],
          correctOrder: ['q23-they', 'q23-wont', 'q23-have', 'q23-cleaned', 'q23-the', 'q23-house', 'q23-before', 'q23-noon'],
          sentenceTranslation: 'No habrán limpiado la casa antes del mediodía.',
        },
        {
          id: 24,
          tokens: [
            {
              id: 'q24-will',
              word: 'Will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q24-you', word: 'you', translation: 'tú' },
            { id: 'q24-have', word: 'have', translation: 'haber' },
            {
              id: 'q24-finished',
              word: 'finished',
              translation: 'terminado',
            },
            { id: 'q24-the', word: 'the', translation: 'el/la' },
            { id: 'q24-project', word: 'project', translation: 'proyecto' },
            { id: 'q24-by', word: 'by', translation: 'para / antes de' },
            { id: 'q24-monday', word: 'Monday?', translation: 'lunes' },
          ],
          correctOrder: ['q24-will', 'q24-you', 'q24-have', 'q24-finished', 'q24-the', 'q24-project', 'q24-by', 'q24-monday'],
          sentenceTranslation: '¿Habrás terminado el proyecto para el lunes?',
        },
        {
          id: 25,
          tokens: [
            { id: 'q25-by', word: 'By', translation: 'para / antes de' },
            { id: 'q25-next', word: 'next', translation: 'próximo' },
            { id: 'q25-year', word: 'year,', translation: 'año' },
            { id: 'q25-she', word: 'she', translation: 'ella' },
            {
              id: 'q25-will',
              word: 'will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q25-have', word: 'have', translation: 'haber' },
            {
              id: 'q25-graduated',
              word: 'graduated.',
              translation: 'graduado',
            },
          ],
          correctOrder: ['q25-by', 'q25-next', 'q25-year', 'q25-she', 'q25-will', 'q25-have', 'q25-graduated'],
          sentenceTranslation: 'Para el próximo año, ella se habrá graduado.',
        },
        {
          id: 26,
          tokens: [
            { id: 'q26-by', word: 'By', translation: 'para / antes de' },
            { id: 'q26-the', word: 'the', translation: 'el/la' },
            { id: 'q26-time', word: 'time', translation: 'hora' },
            { id: 'q26-you', word: 'you', translation: 'tú' },
            { id: 'q26-arrive', word: 'arrive,', translation: 'llegar' },
            { id: 'q26-i', word: 'I', translation: 'yo' },
            {
              id: 'q26-will',
              word: 'will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q26-have', word: 'have', translation: 'haber' },
            { id: 'q26-cooked', word: 'cooked', translation: 'cocinado' },
            { id: 'q26-dinner', word: 'dinner.', translation: 'cena' },
          ],
          correctOrder: ['q26-by', 'q26-the', 'q26-time', 'q26-you', 'q26-arrive', 'q26-i', 'q26-will', 'q26-have', 'q26-cooked', 'q26-dinner'],
          sentenceTranslation: 'Para cuando llegues, habré cocinado la cena.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Future perfect o future simple?',
      instructions: 'Escucha la oración. Decide si la acción estará completada antes de un momento futuro (future perfect) o si simplemente sucederá en el futuro (future simple).',
      questions: [
        {
          id: 27,
          audioText: 'I will have finished by noon.',
          language: 'en',
          prompt: '¿Qué tiempo escuchaste?',
          options: [
            {
              id: 'perfect',
              text: 'Ya estará completada (future perfect)',
            },
            { id: 'simple', text: 'Sucederá en el futuro (future simple)' },
          ],
          correctOptionIds: ['perfect'],
          explanation: 'will have finished: estará completada antes del mediodía (future perfect).',
        },
        {
          id: 28,
          audioText: 'I will finish at noon.',
          language: 'en',
          prompt: '¿Qué tiempo escuchaste?',
          options: [
            {
              id: 'perfect',
              text: 'Ya estará completada (future perfect)',
            },
            { id: 'simple', text: 'Sucederá en el futuro (future simple)' },
          ],
          correctOptionIds: ['simple'],
          explanation: 'will finish: sucederá al mediodía (future simple).',
        },
        {
          id: 29,
          audioText: 'She will have arrived by 6:00.',
          language: 'en',
          prompt: '¿Qué tiempo escuchaste?',
          options: [
            {
              id: 'perfect',
              text: 'Ya estará completada (future perfect)',
            },
            { id: 'simple', text: 'Sucederá en el futuro (future simple)' },
          ],
          correctOptionIds: ['perfect'],
          explanation: 'will have arrived: ya habrá llegado antes de las 6:00 (future perfect).',
        },
        {
          id: 30,
          audioText: 'She will arrive at 6:00.',
          language: 'en',
          prompt: '¿Qué tiempo escuchaste?',
          options: [
            {
              id: 'perfect',
              text: 'Ya estará completada (future perfect)',
            },
            { id: 'simple', text: 'Sucederá en el futuro (future simple)' },
          ],
          correctOptionIds: ['simple'],
          explanation: 'will arrive: llegará a las 6:00 (future simple).',
        },
        {
          id: 31,
          audioText: 'They will have left before the party starts.',
          language: 'en',
          prompt: '¿Qué tiempo escuchaste?',
          options: [
            {
              id: 'perfect',
              text: 'Ya estará completada (future perfect)',
            },
            { id: 'simple', text: 'Sucederá en el futuro (future simple)' },
          ],
          correctOptionIds: ['perfect'],
          explanation: 'will have left: ya se habrán ido antes de la fiesta (future perfect).',
        },
        {
          id: 32,
          audioText: 'They will leave after the party.',
          language: 'en',
          prompt: '¿Qué tiempo escuchaste?',
          options: [
            {
              id: 'perfect',
              text: 'Ya estará completada (future perfect)',
            },
            { id: 'simple', text: 'Sucederá en el futuro (future simple)' },
          ],
          correctOptionIds: ['simple'],
          explanation: 'will leave: se irán después de la fiesta (future simple).',
        },
      ],
    },
  ],
};

export default lessonB2004;
