import type { LessonContent } from '../types';

const lessonB2005: LessonContent = {
  level: 'b2',
  number: 5,
  title: 'Future perfect continuous',
  subtitle: 'Aprende a decir cuánto tiempo llevará una acción en progreso hasta un momento futuro, y cuándo usar future perfect simple o continuous.',
  videoTitle: 'Future perfect continuous',
  videoDescription: 'En este video verás la formación del future perfect continuous (will have been + verbo con ING) y su contraste con el future perfect simple.',
  objective: 'Al terminar, podrás usar el future perfect continuous para hablar de duración, y elegir entre simple y continuous según el mensaje.',
  exercises: [
    {
      type: 'fill-in-the-blanks',
      title: 'Completa con ING',
      instructions: 'Escribe el verbo con ING para formar el future perfect continuous (will have been + verbo con ING).',
      questions: [
        {
          id: 1,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: 'June,', translation: 'junio' },
            { word: 'I', translation: 'yo' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
            { word: 'been', translation: 'estado' },
          ],
          after: [
            { word: 'English', translation: 'inglés' },
            { word: 'for', translation: 'por / durante' },
            { word: 'two', translation: 'dos' },
            { word: 'years.', translation: 'años' },
          ],
          answer: 'studying',
          hint: 'study',
          sentenceTranslation: 'Para junio, tendré dos años estudiando inglés.',
        },
        {
          id: 2,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: '6:00,', translation: 'las 6:00' },
            { word: 'she', translation: 'ella' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
            { word: 'been', translation: 'estado' },
          ],
          after: [
            { word: 'for', translation: 'por / durante' },
            { word: 'eight', translation: 'ocho' },
            { word: 'hours.', translation: 'horas' },
          ],
          answer: 'working',
          hint: 'work',
          sentenceTranslation: 'Para las 6:00, ella tendrá ocho horas trabajando.',
        },
        {
          id: 3,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: 'next', translation: 'próximo' },
            { word: 'month,', translation: 'mes' },
            { word: 'we', translation: 'nosotros' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
            { word: 'been', translation: 'estado' },
          ],
          after: [
            { word: 'here', translation: 'aquí' },
            { word: 'for', translation: 'por / durante' },
            { word: 'a', translation: 'un/una' },
            { word: 'year.', translation: 'año' },
          ],
          answer: 'living',
          hint: 'live',
          sentenceTranslation: 'Para el próximo mes, tendremos un año viviendo aquí.',
        },
        {
          id: 4,
          before: [
            { word: 'They', translation: 'ellos' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
            { word: 'been', translation: 'estado' },
          ],
          after: [
            { word: 'for', translation: 'por / durante' },
            { word: 'an', translation: 'un/una' },
            { word: 'hour', translation: 'hora' },
            { word: 'by', translation: 'para / antes de' },
            { word: 'the', translation: 'el/la' },
            { word: 'time', translation: 'hora' },
            { word: 'the', translation: 'el/la' },
            { word: 'bus', translation: 'autobús' },
            { word: 'arrives.', translation: 'llega' },
          ],
          answer: 'waiting',
          hint: 'wait',
          sentenceTranslation: 'Tendrán una hora esperando para cuando llegue el autobús.',
        },
        {
          id: 5,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: 'December,', translation: 'diciembre' },
            { word: 'he', translation: 'él' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
            { word: 'been', translation: 'estado' },
          ],
          after: [
            { word: 'for', translation: 'por / durante' },
            { word: 'ten', translation: 'diez' },
            { word: 'years.', translation: 'años' },
          ],
          answer: 'teaching',
          hint: 'teach',
          sentenceTranslation: 'Para diciembre, él tendrá diez años enseñando.',
        },
        {
          id: 6,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: 'tonight,', translation: 'esta noche' },
            { word: 'it', translation: 'eso' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
            { word: 'been', translation: 'estado' },
          ],
          after: [
            { word: 'all', translation: 'todos' },
            { word: 'day.', translation: 'día' },
          ],
          answer: 'raining',
          hint: 'rain',
          sentenceTranslation: 'Para esta noche, habrá estado lloviendo todo el día.',
        },
        {
          id: 7,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
            { word: 'been', translation: 'estado' },
          ],
          after: [
            { word: 'for', translation: 'por / durante' },
            { word: 'two', translation: 'dos' },
            { word: 'hours', translation: 'horas' },
            { word: 'by', translation: 'para / antes de' },
            { word: 'then.', translation: 'entonces' },
          ],
          answer: 'running',
          hint: 'run',
          sentenceTranslation: 'Para entonces, tendré dos horas corriendo.',
        },
        {
          id: 8,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
            { word: 'been', translation: 'estado' },
          ],
          after: [
            { word: 'all', translation: 'todos' },
            { word: 'morning', translation: 'mañana' },
            { word: 'by', translation: 'para / antes de' },
            { word: 'the', translation: 'el/la' },
            { word: 'time', translation: 'hora' },
            { word: 'we', translation: 'nosotros' },
            { word: 'arrive.', translation: 'llegar' },
          ],
          answer: 'cooking',
          hint: 'cook',
          sentenceTranslation: 'Ella habrá estado cocinando toda la mañana para cuando lleguemos.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: '¿Simple o continuous?',
      instructions: 'Si la oración habla de un resultado o una cantidad, usa el participio (simple). Si habla de duración, usa been + ING (continuous). Escribe solo la palabra que falta.',
      questions: [
        {
          id: 9,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: 'December,', translation: 'diciembre' },
            { word: 'we', translation: 'nosotros' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'ten', translation: 'diez' },
            { word: 'countries.', translation: 'países' },
          ],
          answer: 'visited',
          hint: 'visit',
          sentenceTranslation: 'Para diciembre, habremos visitado diez países.',
        },
        {
          id: 10,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: 'December,', translation: 'diciembre' },
            { word: 'we', translation: 'nosotros' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
            { word: 'been', translation: 'estado' },
          ],
          after: [
            { word: 'for', translation: 'por / durante' },
            { word: 'six', translation: 'seis' },
            { word: 'months.', translation: 'meses' },
          ],
          answer: 'traveling',
          hint: 'travel',
          sentenceTranslation: 'Para diciembre, tendremos seis meses viajando.',
        },
        {
          id: 11,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: 'Friday,', translation: 'viernes' },
            { word: 'she', translation: 'ella' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'all', translation: 'todos' },
            { word: 'her', translation: 'su' },
            { word: 'exams.', translation: 'exámenes' },
          ],
          answer: 'finished',
          hint: 'finish',
          sentenceTranslation: 'Para el viernes, ella habrá terminado todos sus exámenes.',
        },
        {
          id: 12,
          before: [
            { word: 'By', translation: 'para / antes de' },
            { word: 'Friday,', translation: 'viernes' },
            { word: 'she', translation: 'ella' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
            { word: 'been', translation: 'estado' },
          ],
          after: [
            { word: 'for', translation: 'por / durante' },
            { word: 'a', translation: 'un/una' },
            { word: 'week.', translation: 'semana' },
          ],
          answer: 'studying',
          hint: 'study',
          sentenceTranslation: 'Para el viernes, ella tendrá una semana estudiando.',
        },
        {
          id: 13,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
          ],
          after: [
            { word: 'five', translation: 'cinco' },
            { word: 'books', translation: 'libros' },
            { word: 'by', translation: 'para / antes de' },
            { word: 'June.', translation: 'junio' },
          ],
          answer: 'read',
          hint: 'read',
          sentenceTranslation: 'Habré leído cinco libros para junio.',
        },
        {
          id: 14,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'have', translation: 'haber' },
            { word: 'been', translation: 'estado' },
          ],
          after: [
            { word: 'for', translation: 'por / durante' },
            { word: 'two', translation: 'dos' },
            { word: 'hours', translation: 'horas' },
            { word: 'by', translation: 'para / antes de' },
            { word: '9:00.', translation: 'las 9:00' },
          ],
          answer: 'reading',
          hint: 'read',
          sentenceTranslation: 'Tendré dos horas leyendo para las 9:00.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 15,
          tokens: [
            { id: 'q15-by', word: 'By', translation: 'para / antes de' },
            { id: 'q15-june', word: 'June,', translation: 'junio' },
            { id: 'q15-i', word: 'I', translation: 'yo' },
            {
              id: 'q15-will',
              word: 'will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q15-have', word: 'have', translation: 'haber' },
            { id: 'q15-been', word: 'been', translation: 'estado' },
            {
              id: 'q15-studying',
              word: 'studying',
              translation: 'estudiando',
            },
            { id: 'q15-english', word: 'English', translation: 'inglés' },
            { id: 'q15-for', word: 'for', translation: 'por / durante' },
            { id: 'q15-two', word: 'two', translation: 'dos' },
            { id: 'q15-years', word: 'years.', translation: 'años' },
          ],
          correctOrder: ['q15-by', 'q15-june', 'q15-i', 'q15-will', 'q15-have', 'q15-been', 'q15-studying', 'q15-english', 'q15-for', 'q15-two', 'q15-years'],
          sentenceTranslation: 'Para junio, tendré dos años estudiando inglés.',
        },
        {
          id: 16,
          tokens: [
            { id: 'q16-she', word: 'She', translation: 'ella' },
            { id: 'q16-wont', word: 'won’t', translation: 'no (futuro)' },
            { id: 'q16-have', word: 'have', translation: 'haber' },
            { id: 'q16-been', word: 'been', translation: 'estado' },
            {
              id: 'q16-working',
              word: 'working',
              translation: 'trabajando',
            },
            { id: 'q16-here', word: 'here', translation: 'aquí' },
            { id: 'q16-for', word: 'for', translation: 'por / durante' },
            { id: 'q16-long', word: 'long', translation: 'mucho tiempo' },
            { id: 'q16-by', word: 'by', translation: 'para / antes de' },
            {
              id: 'q16-december',
              word: 'December.',
              translation: 'diciembre',
            },
          ],
          correctOrder: ['q16-she', 'q16-wont', 'q16-have', 'q16-been', 'q16-working', 'q16-here', 'q16-for', 'q16-long', 'q16-by', 'q16-december'],
          sentenceTranslation: 'Ella no llevará mucho tiempo trabajando aquí para diciembre.',
        },
        {
          id: 17,
          tokens: [
            { id: 'q17-they', word: 'They', translation: 'ellos' },
            {
              id: 'q17-will',
              word: 'will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q17-have', word: 'have', translation: 'haber' },
            { id: 'q17-been', word: 'been', translation: 'estado' },
            {
              id: 'q17-waiting',
              word: 'waiting',
              translation: 'esperando',
            },
            { id: 'q17-for', word: 'for', translation: 'por / durante' },
            { id: 'q17-an', word: 'an', translation: 'un/una' },
            { id: 'q17-hour', word: 'hour.', translation: 'hora' },
          ],
          correctOrder: ['q17-they', 'q17-will', 'q17-have', 'q17-been', 'q17-waiting', 'q17-for', 'q17-an', 'q17-hour'],
          sentenceTranslation: 'Tendrán una hora esperando.',
        },
        {
          id: 18,
          tokens: [
            {
              id: 'q18-will',
              word: 'Will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q18-she', word: 'she', translation: 'ella' },
            { id: 'q18-have', word: 'have', translation: 'haber' },
            { id: 'q18-been', word: 'been', translation: 'estado' },
            {
              id: 'q18-working',
              word: 'working',
              translation: 'trabajando',
            },
            { id: 'q18-here', word: 'here', translation: 'aquí' },
            { id: 'q18-for', word: 'for', translation: 'por / durante' },
            { id: 'q18-five', word: 'five', translation: 'cinco' },
            { id: 'q18-years', word: 'years', translation: 'años' },
            { id: 'q18-by', word: 'by', translation: 'para / antes de' },
            { id: 'q18-june', word: 'June?', translation: 'junio' },
          ],
          correctOrder: ['q18-will', 'q18-she', 'q18-have', 'q18-been', 'q18-working', 'q18-here', 'q18-for', 'q18-five', 'q18-years', 'q18-by', 'q18-june'],
          sentenceTranslation: '¿Tendrá ella cinco años trabajando aquí para junio?',
        },
        {
          id: 19,
          tokens: [
            { id: 'q19-i', word: 'I', translation: 'yo' },
            { id: 'q19-wont', word: 'won’t', translation: 'no (futuro)' },
            { id: 'q19-have', word: 'have', translation: 'haber' },
            { id: 'q19-been', word: 'been', translation: 'estado' },
            {
              id: 'q19-sleeping',
              word: 'sleeping',
              translation: 'durmiendo',
            },
            { id: 'q19-much', word: 'much', translation: 'mucho' },
            { id: 'q19-by', word: 'by', translation: 'para / antes de' },
            { id: 'q19-noon', word: 'noon.', translation: 'mediodía' },
          ],
          correctOrder: ['q19-i', 'q19-wont', 'q19-have', 'q19-been', 'q19-sleeping', 'q19-much', 'q19-by', 'q19-noon'],
          sentenceTranslation: 'No habré estado durmiendo mucho para el mediodía.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Resultado o duración?',
      instructions: 'Escucha la oración y decide si habla de un resultado o cantidad (future perfect simple) o de duración (future perfect continuous).',
      questions: [
        {
          id: 20,
          audioText: 'By 9:00, I will have finished the report.',
          language: 'en',
          prompt: '¿Resultado o duración?',
          options: [
            { id: 'simple', text: 'Resultado o cantidad (simple)' },
            { id: 'continuous', text: 'Duración (continuous)' },
          ],
          correctOptionIds: ['simple'],
          explanation: 'will have finished: resultado, la acción estará terminada (simple).',
        },
        {
          id: 21,
          audioText: 'By 9:00, I will have been working for six hours.',
          language: 'en',
          prompt: '¿Resultado o duración?',
          options: [
            { id: 'simple', text: 'Resultado o cantidad (simple)' },
            { id: 'continuous', text: 'Duración (continuous)' },
          ],
          correctOptionIds: ['continuous'],
          explanation: 'will have been working: duración, cuánto tiempo llevará trabajando (continuous).',
        },
        {
          id: 22,
          audioText: 'She will have read twenty books by December.',
          language: 'en',
          prompt: '¿Resultado o duración?',
          options: [
            { id: 'simple', text: 'Resultado o cantidad (simple)' },
            { id: 'continuous', text: 'Duración (continuous)' },
          ],
          correctOptionIds: ['simple'],
          explanation: 'will have read twenty books: cantidad (simple).',
        },
        {
          id: 23,
          audioText: 'She will have been reading all afternoon.',
          language: 'en',
          prompt: '¿Resultado o duración?',
          options: [
            { id: 'simple', text: 'Resultado o cantidad (simple)' },
            { id: 'continuous', text: 'Duración (continuous)' },
          ],
          correctOptionIds: ['continuous'],
          explanation: 'will have been reading: duración (continuous).',
        },
        {
          id: 24,
          audioText: 'They will have built the house by next year.',
          language: 'en',
          prompt: '¿Resultado o duración?',
          options: [
            { id: 'simple', text: 'Resultado o cantidad (simple)' },
            { id: 'continuous', text: 'Duración (continuous)' },
          ],
          correctOptionIds: ['simple'],
          explanation: 'will have built: resultado terminado (simple).',
        },
        {
          id: 25,
          audioText: 'They will have been building the house for a year.',
          language: 'en',
          prompt: '¿Resultado o duración?',
          options: [
            { id: 'simple', text: 'Resultado o cantidad (simple)' },
            { id: 'continuous', text: 'Duración (continuous)' },
          ],
          correctOptionIds: ['continuous'],
          explanation: 'will have been building: duración, llevarán un año construyendo (continuous).',
        },
      ],
    },
  ],
};

export default lessonB2005;
