import type { LessonContent } from '../types';

const lessonB2006: LessonContent = {
  level: 'b2',
  number: 6,
  title: 'Expresar el futuro desde el pasado',
  subtitle: 'Aprende a hablar de planes e intenciones que tenías en el pasado con was/were going to y was/were about to.',
  videoTitle: 'Expresar el futuro desde el pasado',
  videoDescription: 'En este video verás cómo usar was/were going to y was/were about to para hablar de planes pasados y acciones a punto de ocurrir.',
  objective: 'Al terminar, podrás hablar de planes que no se cumplieron y de acciones que estaban a punto de suceder en el pasado.',
  exercises: [
    {
      type: 'fill-in-the-blanks',
      title: '¿Was o were?',
      instructions: 'Escribe was o were según el sujeto para formar was/were going to o was/were about to.',
      questions: [
        {
          id: 1,
          before: [
            { word: 'I', translation: 'yo' },
          ],
          after: [
            { word: 'going', translation: 'yendo / voy a' },
            { word: 'to', translation: 'a' },
            { word: 'call', translation: 'llamar' },
            { word: 'you,', translation: 'tú' },
            { word: 'but', translation: 'pero' },
            { word: 'I', translation: 'yo' },
            { word: 'forgot.', translation: 'olvidé' },
          ],
          answer: 'was',
          sentenceTranslation: 'Iba a llamarte, pero se me olvidó.',
        },
        {
          id: 2,
          before: [
            { word: 'They', translation: 'ellos' },
          ],
          after: [
            { word: 'going', translation: 'yendo / voy a' },
            { word: 'to', translation: 'a' },
            { word: 'travel', translation: 'viajar' },
            { word: 'to', translation: 'a' },
            { word: 'Spain', translation: 'España' },
            { word: 'last', translation: 'pasado' },
            { word: 'summer.', translation: 'verano' },
          ],
          answer: 'were',
          sentenceTranslation: 'Iban a viajar a España el verano pasado.',
        },
        {
          id: 3,
          before: [
            { word: 'She', translation: 'ella' },
          ],
          after: [
            { word: 'going', translation: 'yendo / voy a' },
            { word: 'to', translation: 'a' },
            { word: 'be', translation: 'ser / estar' },
            { word: 'a', translation: 'un/una' },
            { word: 'doctor.', translation: 'doctora' },
          ],
          answer: 'was',
          sentenceTranslation: 'Ella iba a ser doctora.',
        },
        {
          id: 4,
          before: [
            { word: 'We', translation: 'nosotros' },
          ],
          after: [
            { word: 'going', translation: 'yendo / voy a' },
            { word: 'to', translation: 'a' },
            { word: 'visit', translation: 'visitar' },
            { word: 'my', translation: 'mi' },
            { word: 'aunt.', translation: 'tía' },
          ],
          answer: 'were',
          sentenceTranslation: 'Íbamos a visitar a mi tía.',
        },
        {
          id: 5,
          before: [],
          after: [
            { word: 'you', translation: 'tú' },
            { word: 'going', translation: 'yendo / voy a' },
            { word: 'to', translation: 'a' },
            { word: 'call', translation: 'llamar' },
            { word: 'me?', translation: 'me / a mí' },
          ],
          answer: 'Were',
          sentenceTranslation: '¿Ibas a llamarme?',
        },
        {
          id: 6,
          before: [],
          after: [
            { word: 'she', translation: 'ella' },
            { word: 'going', translation: 'yendo / voy a' },
            { word: 'to', translation: 'a' },
            { word: 'move', translation: 'mudarse' },
            { word: 'to', translation: 'a' },
            { word: 'Miami?', translation: 'Miami' },
          ],
          answer: 'Was',
          sentenceTranslation: '¿Iba ella a mudarse a Miami?',
        },
        {
          id: 7,
          before: [
            { word: 'He', translation: 'él' },
          ],
          after: [
            { word: 'about', translation: 'a punto de' },
            { word: 'to', translation: 'a' },
            { word: 'leave', translation: 'irse' },
            { word: 'when', translation: 'cuando' },
            { word: 'the', translation: 'el/la' },
            { word: 'phone', translation: 'teléfono' },
            { word: 'rang.', translation: 'sonó' },
          ],
          answer: 'was',
          sentenceTranslation: 'Él estaba a punto de irse cuando sonó el teléfono.',
        },
        {
          id: 8,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'bus', translation: 'autobús' },
          ],
          after: [
            { word: 'about', translation: 'a punto de' },
            { word: 'to', translation: 'a' },
            { word: 'leave.', translation: 'irse' },
          ],
          answer: 'was',
          sentenceTranslation: 'El autobús estaba a punto de irse.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Going, about, to o but',
      instructions: 'Escribe la palabra que falta: going, about, to o but.',
      questions: [
        {
          id: 9,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'was', translation: 'estaba' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'study', translation: 'estudiar' },
            { word: 'last', translation: 'pasado' },
            { word: 'night.', translation: 'noche' },
          ],
          answer: 'going',
          sentenceTranslation: 'Iba a estudiar anoche.',
        },
        {
          id: 10,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'wasn’t', translation: 'no estaba' },
            { word: 'going', translation: 'yendo / voy a' },
          ],
          after: [
            { word: 'accept', translation: 'aceptar' },
            { word: 'the', translation: 'el/la' },
            { word: 'offer.', translation: 'oferta' },
          ],
          answer: 'to',
          sentenceTranslation: 'Ella no iba a aceptar la oferta.',
        },
        {
          id: 11,
          before: [
            { word: 'We', translation: 'nosotros' },
            { word: 'weren’t', translation: 'no estaban' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'stay', translation: 'quedarse' },
            { word: 'long.', translation: 'mucho tiempo' },
          ],
          answer: 'going',
          sentenceTranslation: 'No íbamos a quedarnos mucho tiempo.',
        },
        {
          id: 12,
          before: [
            { word: 'I', translation: 'yo' },
            { word: 'was', translation: 'estaba' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'leave', translation: 'irse' },
            { word: 'when', translation: 'cuando' },
            { word: 'it', translation: 'eso' },
            { word: 'rained.', translation: 'llovió' },
          ],
          answer: 'about',
          sentenceTranslation: 'Estaba a punto de irme cuando llovió.',
        },
        {
          id: 13,
          before: [
            { word: 'They', translation: 'ellos' },
            { word: 'were', translation: 'estaban' },
            { word: 'going', translation: 'yendo / voy a' },
            { word: 'to', translation: 'a' },
            { word: 'start', translation: 'empezar' },
            { word: 'a', translation: 'un/una' },
            { word: 'business,', translation: 'negocio' },
          ],
          after: [
            { word: 'they', translation: 'ellos' },
            { word: 'had', translation: 'tuve' },
            { word: 'no', translation: 'no' },
            { word: 'money.', translation: 'dinero' },
          ],
          answer: 'but',
          sentenceTranslation: 'Iban a empezar un negocio, pero no tenían dinero.',
        },
        {
          id: 14,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'was', translation: 'estaba' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'cry.', translation: 'llorar' },
          ],
          answer: 'about',
          sentenceTranslation: 'Ella estaba a punto de llorar.',
        },
        {
          id: 15,
          before: [
            { word: 'Were', translation: 'estaban' },
            { word: 'they', translation: 'ellos' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'sell', translation: 'vender' },
            { word: 'the', translation: 'el/la' },
            { word: 'house?', translation: 'casa' },
          ],
          answer: 'going',
          sentenceTranslation: '¿Iban a vender la casa?',
        },
        {
          id: 16,
          before: [
            { word: 'He', translation: 'él' },
            { word: 'was', translation: 'estaba' },
            { word: 'going', translation: 'yendo / voy a' },
          ],
          after: [
            { word: 'tell', translation: 'decir' },
            { word: 'you', translation: 'tú' },
            { word: 'the', translation: 'el/la' },
            { word: 'news.', translation: 'las noticias' },
          ],
          answer: 'to',
          sentenceTranslation: 'Él iba a darte la noticia.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 17,
          tokens: [
            { id: 'q17-i', word: 'I', translation: 'yo' },
            { id: 'q17-was', word: 'was', translation: 'estaba' },
            {
              id: 'q17-going',
              word: 'going',
              translation: 'yendo / voy a',
            },
            { id: 'q17-to', word: 'to', translation: 'a' },
            { id: 'q17-study', word: 'study', translation: 'estudiar' },
            { id: 'q17-last', word: 'last', translation: 'pasado' },
            { id: 'q17-night', word: 'night.', translation: 'noche' },
          ],
          correctOrder: ['q17-i', 'q17-was', 'q17-going', 'q17-to', 'q17-study', 'q17-last', 'q17-night'],
          sentenceTranslation: 'Iba a estudiar anoche.',
        },
        {
          id: 18,
          tokens: [
            { id: 'q18-she', word: 'She', translation: 'ella' },
            { id: 'q18-wasnt', word: 'wasn’t', translation: 'no estaba' },
            {
              id: 'q18-going',
              word: 'going',
              translation: 'yendo / voy a',
            },
            { id: 'q18-to', word: 'to', translation: 'a' },
            { id: 'q18-accept', word: 'accept', translation: 'aceptar' },
            { id: 'q18-the', word: 'the', translation: 'el/la' },
            { id: 'q18-offer', word: 'offer.', translation: 'oferta' },
          ],
          correctOrder: ['q18-she', 'q18-wasnt', 'q18-going', 'q18-to', 'q18-accept', 'q18-the', 'q18-offer'],
          sentenceTranslation: 'Ella no iba a aceptar la oferta.',
        },
        {
          id: 19,
          tokens: [
            { id: 'q19-were', word: 'Were', translation: 'estaban' },
            { id: 'q19-you', word: 'you', translation: 'tú' },
            {
              id: 'q19-going',
              word: 'going',
              translation: 'yendo / voy a',
            },
            { id: 'q19-to', word: 'to', translation: 'a' },
            { id: 'q19-call', word: 'call', translation: 'llamar' },
            { id: 'q19-me', word: 'me?', translation: 'me / a mí' },
          ],
          correctOrder: ['q19-were', 'q19-you', 'q19-going', 'q19-to', 'q19-call', 'q19-me'],
          sentenceTranslation: '¿Ibas a llamarme?',
        },
        {
          id: 20,
          tokens: [
            { id: 'q20-we', word: 'We', translation: 'nosotros' },
            { id: 'q20-were', word: 'were', translation: 'estaban' },
            {
              id: 'q20-going',
              word: 'going',
              translation: 'yendo / voy a',
            },
            { id: 'q20-to', word: 'to', translation: 'a' },
            { id: 'q20-visit', word: 'visit', translation: 'visitar' },
            { id: 'q20-my', word: 'my', translation: 'mi' },
            { id: 'q20-aunt', word: 'aunt.', translation: 'tía' },
          ],
          correctOrder: ['q20-we', 'q20-were', 'q20-going', 'q20-to', 'q20-visit', 'q20-my', 'q20-aunt'],
          sentenceTranslation: 'Íbamos a visitar a mi tía.',
        },
        {
          id: 21,
          tokens: [
            { id: 'q21-i', word: 'I', translation: 'yo' },
            { id: 'q21-was', word: 'was', translation: 'estaba' },
            { id: 'q21-about', word: 'about', translation: 'a punto de' },
            { id: 'q21-to', word: 'to', translation: 'a' },
            { id: 'q21-leave', word: 'leave', translation: 'irse' },
            { id: 'q21-when', word: 'when', translation: 'cuando' },
            { id: 'q21-the', word: 'the', translation: 'el/la' },
            { id: 'q21-phone', word: 'phone', translation: 'teléfono' },
            { id: 'q21-rang', word: 'rang.', translation: 'sonó' },
          ],
          correctOrder: ['q21-i', 'q21-was', 'q21-about', 'q21-to', 'q21-leave', 'q21-when', 'q21-the', 'q21-phone', 'q21-rang'],
          sentenceTranslation: 'Estaba a punto de irme cuando sonó el teléfono.',
        },
        {
          id: 22,
          tokens: [
            { id: 'q22-where', word: 'Where', translation: 'dónde' },
            { id: 'q22-was', word: 'was', translation: 'estaba' },
            { id: 'q22-she', word: 'she', translation: 'ella' },
            {
              id: 'q22-going',
              word: 'going',
              translation: 'yendo / voy a',
            },
            { id: 'q22-to', word: 'to', translation: 'a' },
            { id: 'q22-live', word: 'live?', translation: 'vivir' },
          ],
          correctOrder: ['q22-where', 'q22-was', 'q22-she', 'q22-going', 'q22-to', 'q22-live'],
          sentenceTranslation: '¿Dónde iba a vivir ella?',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: 'Planes y acciones a punto de ocurrir',
      instructions: 'Escucha la oración y elige la respuesta correcta.',
      questions: [
        {
          id: 23,
          audioText: 'I was going to call you, but I forgot.',
          language: 'en',
          prompt: '¿Se cumplió el plan?',
          options: [
            { id: 'yes', text: 'Sí, lo hizo' },
            { id: 'no', text: 'No, no lo hizo' },
          ],
          correctOptionIds: ['no'],
          explanation: 'was going to ..., but ... indica un plan que no se cumplió.',
        },
        {
          id: 24,
          audioText: 'We were going to go to the beach, but it rained.',
          language: 'en',
          prompt: '¿Se cumplió el plan?',
          options: [
            { id: 'yes', text: 'Sí, lo hicieron' },
            { id: 'no', text: 'No, no lo hicieron' },
          ],
          correctOptionIds: ['no'],
          explanation: 'La lluvia impidió el plan: no se cumplió.',
        },
        {
          id: 25,
          audioText: 'She was going to help, but she had no time.',
          language: 'en',
          prompt: '¿Se cumplió el plan?',
          options: [
            { id: 'yes', text: 'Sí, lo hizo' },
            { id: 'no', text: 'No, no lo hizo' },
          ],
          correctOptionIds: ['no'],
          explanation: 'She had no time: el plan no se cumplió.',
        },
        {
          id: 26,
          audioText: 'I was about to leave when the phone rang.',
          language: 'en',
          prompt: '¿Qué estaba a punto de hacer?',
          options: [
            { id: 'leave', text: 'Irse' },
            { id: 'call', text: 'Llamar' },
          ],
          correctOptionIds: ['leave'],
          explanation: 'was about to leave = estaba a punto de irse.',
        },
        {
          id: 27,
          audioText: 'She was about to cry.',
          language: 'en',
          prompt: '¿Qué estaba a punto de hacer?',
          options: [
            { id: 'cry', text: 'Llorar' },
            { id: 'laugh', text: 'Reírse' },
          ],
          correctOptionIds: ['cry'],
          explanation: 'was about to cry = estaba a punto de llorar.',
        },
        {
          id: 28,
          audioText: 'The movie was about to start.',
          language: 'en',
          prompt: '¿Qué estaba a punto de pasar?',
          options: [
            { id: 'start', text: 'Empezar la película' },
            { id: 'end', text: 'Terminar la película' },
          ],
          correctOptionIds: ['start'],
          explanation: 'was about to start = estaba a punto de empezar.',
        },
      ],
    },
  ],
};

export default lessonB2006;
