import type { LessonContent } from '../types';

const lessonB2008: LessonContent = {
  level: 'b2',
  number: 8,
  title: 'Condicionales mixtos',
  subtitle: 'Aprende a combinar tiempos distintos en el condicional: una condición pasada con un resultado presente, y viceversa.',
  videoTitle: 'Condicionales mixtos',
  videoDescription: 'En este video verás los dos tipos de condicionales mixtos: if + past perfect, would + verbo, e if + past simple, would have + participio.',
  objective: 'Al terminar, podrás usar condicionales mixtos para hablar de cómo el pasado afecta el presente, y del pasado que no ocurrió por una condición presente.',
  exercises: [
    {
      type: 'fill-in-the-blanks',
      title: 'Had, were, would o have',
      instructions: 'Escribe la palabra que falta: had, were, would o have.',
      questions: [
        {
          id: 1,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'I', translation: 'yo' },
          ],
          after: [
            { word: 'studied', translation: 'estudié' },
            { word: 'harder,', translation: 'más duro' },
            { word: 'I', translation: 'yo' },
            { word: 'would', translation: 'sería' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'a', translation: 'un/una' },
            { word: 'better', translation: 'mejor' },
            { word: 'job', translation: 'trabajo' },
            { word: 'now.', translation: 'ahora' },
          ],
          answer: 'had',
          sentenceTranslation: 'Si hubiera estudiado más, ahora tendría un mejor trabajo.',
        },
        {
          id: 2,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'she', translation: 'ella' },
          ],
          after: [
            { word: 'taken', translation: 'tomado' },
            { word: 'the', translation: 'el/la' },
            { word: 'bus,', translation: 'autobús' },
            { word: 'she', translation: 'ella' },
            { word: 'would', translation: 'sería' },
            { word: 'be', translation: 'ser' },
            { word: 'here', translation: 'aquí' },
            { word: 'now.', translation: 'ahora' },
          ],
          answer: 'had',
          sentenceTranslation: 'Si hubiera tomado el autobús, estaría aquí ahora.',
        },
        {
          id: 3,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'we', translation: 'nosotros' },
            { word: 'had', translation: 'hubiera' },
            { word: 'saved', translation: 'ahorrado' },
            { word: 'money,', translation: 'dinero' },
            { word: 'we', translation: 'nosotros' },
          ],
          after: [
            { word: 'be', translation: 'ser' },
            { word: 'rich', translation: 'rico' },
            { word: 'today.', translation: 'hoy' },
          ],
          answer: 'would',
          sentenceTranslation: 'Si hubiéramos ahorrado dinero, seríamos ricos hoy.',
        },
        {
          id: 4,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'she', translation: 'ella' },
          ],
          after: [
            { word: 'taller,', translation: 'más alto' },
            { word: 'she', translation: 'ella' },
            { word: 'would', translation: 'sería' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'joined', translation: 'unido' },
            { word: 'the', translation: 'el/la' },
            { word: 'team.', translation: 'equipo' },
          ],
          answer: 'were',
          sentenceTranslation: 'Si fuera más alta, se habría unido al equipo.',
        },
        {
          id: 5,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'I', translation: 'yo' },
          ],
          after: [
            { word: 'you,', translation: 'tú' },
            { word: 'I', translation: 'yo' },
            { word: 'would', translation: 'sería' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'accepted', translation: 'aceptado' },
            { word: 'the', translation: 'el/la' },
            { word: 'job.', translation: 'trabajo' },
          ],
          answer: 'were',
          sentenceTranslation: 'Si yo fuera tú, habría aceptado el trabajo.',
        },
        {
          id: 6,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'he', translation: 'él' },
            { word: 'had', translation: 'hubiera' },
            { word: 'slept', translation: 'dormí' },
            { word: 'well,', translation: 'bien' },
            { word: 'he', translation: 'él' },
          ],
          after: [
            { word: 'feel', translation: 'sentiría' },
            { word: 'better', translation: 'mejor' },
            { word: 'now.', translation: 'ahora' },
          ],
          answer: 'would',
          sentenceTranslation: 'Si hubiera dormido bien, se sentiría mejor ahora.',
        },
        {
          id: 7,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'they', translation: 'ellos' },
            { word: 'hadn’t', translation: 'no hubiera' },
            { word: 'met,', translation: 'conoció' },
            { word: 'they', translation: 'ellos' },
            { word: 'wouldn’t', translation: 'no sería' },
          ],
          after: [
            { word: 'married', translation: 'casó' },
            { word: 'now.', translation: 'ahora' },
          ],
          answer: 'be',
          sentenceTranslation: 'Si no se hubieran conocido, no estarían casados ahora.',
        },
        {
          id: 8,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'I', translation: 'yo' },
            { word: 'spoke', translation: 'hablara' },
            { word: 'Italian,', translation: 'italiano' },
            { word: 'I', translation: 'yo' },
            { word: 'would', translation: 'sería' },
          ],
          after: [
            { word: 'moved', translation: 'mudado' },
            { word: 'to', translation: 'a' },
            { word: 'Rome.', translation: 'Roma' },
          ],
          answer: 'have',
          sentenceTranslation: 'Si hablara italiano, me habría mudado a Roma.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Completa con el participio',
      instructions: 'En este tipo, la condición es del presente (past simple) y el resultado es del pasado (would have + participio). Escribe el participio.',
      questions: [
        {
          id: 9,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'she', translation: 'ella' },
            { word: 'were', translation: 'fuera' },
            { word: 'taller,', translation: 'más alto' },
            { word: 'she', translation: 'ella' },
            { word: 'would', translation: 'sería' },
            { word: 'have', translation: 'he / hemos' },
          ],
          after: [
            { word: 'volleyball.', translation: 'voleibol' },
          ],
          answer: 'played',
          hint: 'play',
          sentenceTranslation: 'Si fuera más alta, habría jugado voleibol.',
        },
        {
          id: 10,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'he', translation: 'él' },
            { word: 'spoke', translation: 'hablara' },
            { word: 'Italian,', translation: 'italiano' },
            { word: 'he', translation: 'él' },
            { word: 'would', translation: 'sería' },
            { word: 'have', translation: 'he / hemos' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'Rome.', translation: 'Roma' },
          ],
          answer: 'moved',
          hint: 'move',
          sentenceTranslation: 'Si hablara italiano, se habría mudado a Roma.',
        },
        {
          id: 11,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'I', translation: 'yo' },
            { word: 'were', translation: 'fuera' },
            { word: 'you,', translation: 'tú' },
            { word: 'I', translation: 'yo' },
            { word: 'would', translation: 'sería' },
            { word: 'have', translation: 'he / hemos' },
          ],
          after: [
            { word: 'her.', translation: 'ella' },
          ],
          answer: 'called',
          hint: 'call',
          sentenceTranslation: 'Si yo fuera tú, la habría llamado.',
        },
        {
          id: 12,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'they', translation: 'ellos' },
            { word: 'weren’t', translation: 'no estaban' },
            { word: 'so', translation: 'tanto' },
            { word: 'busy,', translation: 'ocupados' },
            { word: 'they', translation: 'ellos' },
            { word: 'would', translation: 'sería' },
            { word: 'have', translation: 'he / hemos' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'the', translation: 'el/la' },
            { word: 'party.', translation: 'fiesta' },
          ],
          answer: 'come',
          hint: 'come',
          sentenceTranslation: 'Si no estuvieran tan ocupados, habrían venido a la fiesta.',
        },
        {
          id: 13,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'I', translation: 'yo' },
            { word: 'weren’t', translation: 'no estaban' },
            { word: 'so', translation: 'tanto' },
            { word: 'shy,', translation: 'tímido' },
            { word: 'I', translation: 'yo' },
            { word: 'would', translation: 'sería' },
            { word: 'have', translation: 'he / hemos' },
          ],
          after: [
            { word: 'to', translation: 'a' },
            { word: 'her.', translation: 'ella' },
          ],
          answer: 'talked',
          hint: 'talk',
          sentenceTranslation: 'Si no fuera tan tímido, habría hablado con ella.',
        },
        {
          id: 14,
          before: [
            { word: 'If', translation: 'si' },
            { word: 'he', translation: 'él' },
            { word: 'were', translation: 'fuera' },
            { word: 'braver,', translation: 'más valiente' },
            { word: 'he', translation: 'él' },
            { word: 'would', translation: 'sería' },
            { word: 'have', translation: 'he / hemos' },
          ],
          after: [],
          answer: 'jumped',
          hint: 'jump',
          sentenceTranslation: 'Si fuera más valiente, habría saltado.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 15,
          tokens: [
            { id: 'q15-if', word: 'If', translation: 'si' },
            { id: 'q15-ana', word: 'Ana', translation: 'Ana' },
            { id: 'q15-had', word: 'had', translation: 'hubiera' },
            { id: 'q15-studied', word: 'studied', translation: 'estudié' },
            {
              id: 'q15-medicine',
              word: 'medicine,',
              translation: 'medicina',
            },
            { id: 'q15-she', word: 'she', translation: 'ella' },
            { id: 'q15-would', word: 'would', translation: 'sería' },
            { id: 'q15-be', word: 'be', translation: 'ser' },
            { id: 'q15-a', word: 'a', translation: 'un/una' },
            { id: 'q15-doctor', word: 'doctor.', translation: 'doctora' },
          ],
          correctOrder: ['q15-if', 'q15-ana', 'q15-had', 'q15-studied', 'q15-medicine', 'q15-she', 'q15-would', 'q15-be', 'q15-a', 'q15-doctor'],
          sentenceTranslation: 'Si Ana hubiera estudiado medicina, sería doctora.',
        },
        {
          id: 16,
          tokens: [
            { id: 'q16-if', word: 'If', translation: 'si' },
            { id: 'q16-tom', word: 'Tom', translation: 'Tom' },
            { id: 'q16-were', word: 'were', translation: 'fuera' },
            { id: 'q16-taller', word: 'taller,', translation: 'más alto' },
            { id: 'q16-he', word: 'he', translation: 'él' },
            { id: 'q16-would', word: 'would', translation: 'sería' },
            { id: 'q16-have', word: 'have', translation: 'he / hemos' },
            { id: 'q16-played', word: 'played', translation: 'jugado' },
            {
              id: 'q16-basketball',
              word: 'basketball.',
              translation: 'baloncesto',
            },
          ],
          correctOrder: ['q16-if', 'q16-tom', 'q16-were', 'q16-taller', 'q16-he', 'q16-would', 'q16-have', 'q16-played', 'q16-basketball'],
          sentenceTranslation: 'Si Tom fuera más alto, habría jugado baloncesto.',
        },
        {
          id: 17,
          tokens: [
            { id: 'q17-if', word: 'If', translation: 'si' },
            { id: 'q17-sam', word: 'Sam', translation: 'Sam' },
            { id: 'q17-had', word: 'had', translation: 'hubiera' },
            { id: 'q17-left', word: 'left', translation: 'salido' },
            { id: 'q17-earlier', word: 'earlier,', translation: 'antes' },
            { id: 'q17-we', word: 'we', translation: 'nosotros' },
            {
              id: 'q17-wouldnt',
              word: 'wouldn’t',
              translation: 'no sería',
            },
            { id: 'q17-be', word: 'be', translation: 'ser' },
            { id: 'q17-late', word: 'late', translation: 'tarde' },
            { id: 'q17-now', word: 'now.', translation: 'ahora' },
          ],
          correctOrder: ['q17-if', 'q17-sam', 'q17-had', 'q17-left', 'q17-earlier', 'q17-we', 'q17-wouldnt', 'q17-be', 'q17-late', 'q17-now'],
          sentenceTranslation: 'Si Sam hubiera salido antes, no llegaríamos tarde ahora.',
        },
        {
          id: 18,
          tokens: [
            { id: 'q18-if', word: 'If', translation: 'si' },
            { id: 'q18-lisa', word: 'Lisa', translation: 'Lisa' },
            { id: 'q18-spoke', word: 'spoke', translation: 'hablara' },
            { id: 'q18-french', word: 'French,', translation: 'francés' },
            { id: 'q18-she', word: 'she', translation: 'ella' },
            { id: 'q18-would', word: 'would', translation: 'sería' },
            { id: 'q18-have', word: 'have', translation: 'he / hemos' },
            { id: 'q18-got', word: 'got', translation: 'conseguido' },
            { id: 'q18-the', word: 'the', translation: 'el/la' },
            { id: 'q18-job', word: 'job.', translation: 'trabajo' },
          ],
          correctOrder: ['q18-if', 'q18-lisa', 'q18-spoke', 'q18-french', 'q18-she', 'q18-would', 'q18-have', 'q18-got', 'q18-the', 'q18-job'],
          sentenceTranslation: 'Si Lisa hablara francés, habría conseguido el trabajo.',
        },
        {
          id: 19,
          tokens: [
            { id: 'q19-if', word: 'If', translation: 'si' },
            { id: 'q19-max', word: 'Max', translation: 'Max' },
            { id: 'q19-hadnt', word: 'hadn’t', translation: 'no hubiera' },
            { id: 'q19-eaten', word: 'eaten', translation: 'comido' },
            { id: 'q19-so', word: 'so', translation: 'tanto' },
            { id: 'q19-much', word: 'much,', translation: 'mucho' },
            { id: 'q19-he', word: 'he', translation: 'él' },
            {
              id: 'q19-wouldnt',
              word: 'wouldn’t',
              translation: 'no sería',
            },
            { id: 'q19-feel', word: 'feel', translation: 'sentiría' },
            { id: 'q19-sick', word: 'sick.', translation: 'enfermo' },
          ],
          correctOrder: ['q19-if', 'q19-max', 'q19-hadnt', 'q19-eaten', 'q19-so', 'q19-much', 'q19-he', 'q19-wouldnt', 'q19-feel', 'q19-sick'],
          sentenceTranslation: 'Si Max no hubiera comido tanto, no se sentiría mal.',
        },
        {
          id: 20,
          tokens: [
            { id: 'q20-would', word: 'Would', translation: 'sería' },
            { id: 'q20-ana', word: 'Ana', translation: 'Ana' },
            { id: 'q20-be', word: 'be', translation: 'ser' },
            {
              id: 'q20-happier',
              word: 'happier',
              translation: 'más feliz',
            },
            { id: 'q20-if', word: 'if', translation: 'si' },
            { id: 'q20-she', word: 'she', translation: 'ella' },
            { id: 'q20-had', word: 'had', translation: 'hubiera' },
            { id: 'q20-studied', word: 'studied', translation: 'estudié' },
            {
              id: 'q20-medicine',
              word: 'medicine?',
              translation: 'medicina',
            },
          ],
          correctOrder: ['q20-would', 'q20-ana', 'q20-be', 'q20-happier', 'q20-if', 'q20-she', 'q20-had', 'q20-studied', 'q20-medicine'],
          sentenceTranslation: '¿Sería Ana más feliz si hubiera estudiado medicina?',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Qué tipo de condicional mixto?',
      instructions: 'Escucha la oración. Tipo 1: condición en el pasado, resultado en el presente. Tipo 2: condición en el presente, resultado en el pasado.',
      questions: [
        {
          id: 21,
          audioText: 'If I had studied medicine, I would be a doctor now.',
          language: 'en',
          prompt: '¿Qué tipo es?',
          options: [
            { id: 't1', text: 'Condición pasada → resultado presente' },
            { id: 't2', text: 'Condición presente → resultado pasado' },
          ],
          correctOptionIds: ['t1'],
          explanation: 'had studied (pasado) → would be now (presente).',
        },
        {
          id: 22,
          audioText: 'If she were taller, she would have joined the team.',
          language: 'en',
          prompt: '¿Qué tipo es?',
          options: [
            { id: 't1', text: 'Condición pasada → resultado presente' },
            { id: 't2', text: 'Condición presente → resultado pasado' },
          ],
          correctOptionIds: ['t2'],
          explanation: 'were (presente) → would have joined (pasado).',
        },
        {
          id: 23,
          audioText: 'If we had left earlier, we wouldn’t be late now.',
          language: 'en',
          prompt: '¿Qué tipo es?',
          options: [
            { id: 't1', text: 'Condición pasada → resultado presente' },
            { id: 't2', text: 'Condición presente → resultado pasado' },
          ],
          correctOptionIds: ['t1'],
          explanation: 'had left (pasado) → wouldn’t be now (presente).',
        },
        {
          id: 24,
          audioText: 'If he spoke Italian, he would have moved to Rome.',
          language: 'en',
          prompt: '¿Qué tipo es?',
          options: [
            { id: 't1', text: 'Condición pasada → resultado presente' },
            { id: 't2', text: 'Condición presente → resultado pasado' },
          ],
          correctOptionIds: ['t2'],
          explanation: 'spoke (presente) → would have moved (pasado).',
        },
        {
          id: 25,
          audioText: 'If they hadn’t met, they wouldn’t be married now.',
          language: 'en',
          prompt: '¿Qué tipo es?',
          options: [
            { id: 't1', text: 'Condición pasada → resultado presente' },
            { id: 't2', text: 'Condición presente → resultado pasado' },
          ],
          correctOptionIds: ['t1'],
          explanation: 'hadn’t met (pasado) → wouldn’t be married now (presente).',
        },
        {
          id: 26,
          audioText: 'If I weren’t so shy, I would have talked to her.',
          language: 'en',
          prompt: '¿Qué tipo es?',
          options: [
            { id: 't1', text: 'Condición pasada → resultado presente' },
            { id: 't2', text: 'Condición presente → resultado pasado' },
          ],
          correctOptionIds: ['t2'],
          explanation: 'weren’t (presente) → would have talked (pasado).',
        },
      ],
    },
  ],
};

export default lessonB2008;
