import type { LessonContent } from '../types';

const lessonB2009: LessonContent = {
  level: 'b2',
  number: 9,
  title: 'Alternativas a if: unless, provided that y as long as',
  subtitle: 'Aprende a expresar condiciones con unless, provided that y as long as en lugar de if.',
  videoTitle: 'Alternativas a if',
  videoDescription: 'En este video verás cuándo usar unless (a menos que) y provided that / as long as (siempre que) en lugar de if.',
  objective: 'Al terminar, podrás usar unless, provided that y as long as para expresar condiciones con precisión.',
  exercises: [
    {
      type: 'fill-in-the-blanks',
      title: 'Unless, provided o as long as',
      instructions: 'Escribe la palabra que falta. Unless = if not. Provided (that) y as long as = solo si.',
      questions: [
        {
          id: 1,
          before: [],
          after: [
            { word: 'you', translation: 'tú' },
            { word: 'hurry,', translation: 'apúrate' },
            { word: 'you', translation: 'tú' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'miss', translation: 'perderá' },
            { word: 'the', translation: 'el/la' },
            { word: 'train.', translation: 'tren' },
          ],
          answer: 'Unless',
          sentenceTranslation: 'A menos que te apures, perderás el tren.',
        },
        {
          id: 2,
          before: [
            { word: 'I’ll', translation: 'yo (futuro)' },
            { word: 'go', translation: 'iré' },
          ],
          after: [
            { word: 'it', translation: 'eso' },
            { word: 'rains.', translation: 'llueve' },
          ],
          answer: 'unless',
          sentenceTranslation: 'Iré a menos que llueva.',
        },
        {
          id: 3,
          before: [
            { word: 'Anna', translation: 'Anna' },
            { word: 'can', translation: 'puede' },
            { word: 'borrow', translation: 'pedir prestado' },
            { word: 'my', translation: 'mi' },
            { word: 'car', translation: 'carro' },
          ],
          after: [
            { word: 'she', translation: 'ella' },
            { word: 'drives', translation: 'maneja' },
            { word: 'carefully.', translation: 'con cuidado' },
          ],
          answer: 'provided',
          sentenceTranslation: 'Anna puede usar mi carro siempre que maneje con cuidado.',
        },
        {
          id: 4,
          before: [],
          after: [
            { word: 'long', translation: 'tiempo' },
            { word: 'as', translation: 'mientras' },
            { word: 'Sam', translation: 'Sam' },
            { word: 'studies,', translation: 'estudia' },
            { word: 'he', translation: 'él' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'pass.', translation: 'aprobará' },
          ],
          answer: 'As',
          sentenceTranslation: 'Mientras Sam estudie, aprobará.',
        },
        {
          id: 5,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'won’t', translation: 'no (futuro)' },
            { word: 'come', translation: 'venir' },
          ],
          after: [
            { word: 'you', translation: 'tú' },
            { word: 'ask', translation: 'pides' },
            { word: 'her.', translation: 'ella' },
          ],
          answer: 'unless',
          sentenceTranslation: 'Ella no vendrá a menos que se lo pidas.',
        },
        {
          id: 6,
          before: [
            { word: 'I’ll', translation: 'yo (futuro)' },
            { word: 'help', translation: 'ayudar' },
            { word: 'you', translation: 'tú' },
            { word: 'as', translation: 'mientras' },
          ],
          after: [
            { word: 'as', translation: 'mientras' },
            { word: 'you', translation: 'tú' },
            { word: 'tell', translation: 'decir' },
            { word: 'the', translation: 'el/la' },
            { word: 'truth.', translation: 'verdad' },
          ],
          answer: 'long',
          sentenceTranslation: 'Te ayudaré siempre que digas la verdad.',
        },
        {
          id: 7,
          before: [
            { word: 'They', translation: 'ellos' },
            { word: 'can', translation: 'puede' },
            { word: 'stay', translation: 'quedarse' },
          ],
          after: [
            { word: 'long', translation: 'tiempo' },
            { word: 'as', translation: 'mientras' },
            { word: 'it', translation: 'eso' },
            { word: 'is', translation: 'es' },
            { word: 'quiet.', translation: 'tranquilo' },
          ],
          answer: 'as',
          sentenceTranslation: 'Pueden quedarse siempre que haya silencio.',
        },
        {
          id: 8,
          before: [
            { word: 'We’ll', translation: 'nosotros (futuro)' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'the', translation: 'el/la' },
            { word: 'picnic', translation: 'picnic' },
          ],
          after: [
            { word: 'it', translation: 'eso' },
            { word: 'rains.', translation: 'llueve' },
          ],
          answer: 'unless',
          sentenceTranslation: 'Haremos el picnic a menos que llueva.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Reescribe con if',
      instructions: 'Escribe la palabra que falta para decir lo mismo con if. Recuerda: unless = if ... not.',
      questions: [
        {
          id: 9,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'won’t', translation: 'no (futuro)' },
            { word: 'come', translation: 'venir' },
            { word: 'unless', translation: 'a menos que' },
            { word: 'you', translation: 'tú' },
            { word: 'ask', translation: 'pides' },
            { word: 'her.', translation: 'ella' },
            { word: '=', translation: 'es decir' },
            { word: 'She', translation: 'ella' },
            { word: 'won’t', translation: 'no (futuro)' },
            { word: 'come', translation: 'venir' },
            { word: 'if', translation: 'si' },
            { word: 'you', translation: 'tú' },
            { word: 'do', translation: 'hacer' },
          ],
          after: [
            { word: 'ask', translation: 'pides' },
            { word: 'her.', translation: 'ella' },
          ],
          answer: 'not',
          sentenceTranslation: 'Ella no vendrá si tú no se lo pides.',
        },
        {
          id: 10,
          before: [
            { word: 'Unless', translation: 'a menos que' },
            { word: 'you', translation: 'tú' },
            { word: 'study,', translation: 'estudiar' },
            { word: 'you', translation: 'tú' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'fail.', translation: 'reprobar' },
            { word: '=', translation: 'es decir' },
            { word: 'If', translation: 'si' },
            { word: 'you', translation: 'tú' },
            { word: 'do', translation: 'hacer' },
          ],
          after: [
            { word: 'study,', translation: 'estudiar' },
            { word: 'you', translation: 'tú' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'fail.', translation: 'reprobar' },
          ],
          answer: 'not',
          sentenceTranslation: 'Si no estudias, reprobarás.',
        },
        {
          id: 11,
          before: [
            { word: 'I’ll', translation: 'yo (futuro)' },
            { word: 'go', translation: 'iré' },
            { word: 'unless', translation: 'a menos que' },
            { word: 'it', translation: 'eso' },
            { word: 'rains.', translation: 'llueve' },
            { word: '=', translation: 'es decir' },
            { word: 'I’ll', translation: 'yo (futuro)' },
            { word: 'go', translation: 'iré' },
            { word: 'if', translation: 'si' },
            { word: 'it', translation: 'eso' },
            { word: 'does', translation: 'hace' },
          ],
          after: [
            { word: 'rain.', translation: 'llover' },
          ],
          answer: 'not',
          sentenceTranslation: 'Iré si no llueve.',
        },
        {
          id: 12,
          before: [
            { word: 'You', translation: 'tú' },
            { word: 'can', translation: 'puede' },
            { word: 'go', translation: 'iré' },
            { word: 'out', translation: 'salir' },
            { word: 'provided', translation: 'siempre que' },
            { word: 'you', translation: 'tú' },
            { word: 'finish', translation: 'terminar' },
            { word: 'your', translation: 'tu' },
            { word: 'homework.', translation: 'tarea' },
            { word: '=', translation: 'es decir' },
            { word: 'You', translation: 'tú' },
            { word: 'can', translation: 'puede' },
            { word: 'go', translation: 'iré' },
            { word: 'out', translation: 'salir' },
          ],
          after: [
            { word: 'if', translation: 'si' },
            { word: 'you', translation: 'tú' },
            { word: 'finish', translation: 'terminar' },
            { word: 'your', translation: 'tu' },
            { word: 'homework.', translation: 'tarea' },
          ],
          answer: 'only',
          sentenceTranslation: 'Puedes salir solo si terminas la tarea.',
        },
        {
          id: 13,
          before: [
            { word: 'As', translation: 'mientras' },
            { word: 'long', translation: 'tiempo' },
            { word: 'as', translation: 'mientras' },
            { word: 'you', translation: 'tú' },
            { word: 'try,', translation: 'intentar' },
            { word: 'you', translation: 'tú' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'improve.', translation: 'mejorar' },
            { word: '=', translation: 'es decir' },
          ],
          after: [
            { word: 'you', translation: 'tú' },
            { word: 'try,', translation: 'intentar' },
            { word: 'you', translation: 'tú' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'improve.', translation: 'mejorar' },
          ],
          answer: 'If',
          sentenceTranslation: 'Si lo intentas, mejorarás.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 14,
          tokens: [
            {
              id: 'q14-unless',
              word: 'Unless',
              translation: 'a menos que',
            },
            { id: 'q14-tom', word: 'Tom', translation: 'Tom' },
            {
              id: 'q14-hurries',
              word: 'hurries,',
              translation: 'se apura',
            },
            { id: 'q14-he', word: 'he', translation: 'él' },
            {
              id: 'q14-will',
              word: 'will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q14-miss', word: 'miss', translation: 'perderá' },
            { id: 'q14-the', word: 'the', translation: 'el/la' },
            { id: 'q14-train', word: 'train.', translation: 'tren' },
          ],
          correctOrder: ['q14-unless', 'q14-tom', 'q14-hurries', 'q14-he', 'q14-will', 'q14-miss', 'q14-the', 'q14-train'],
          sentenceTranslation: 'A menos que Tom se apure, perderá el tren.',
        },
        {
          id: 15,
          tokens: [
            { id: 'q15-i', word: 'I', translation: 'yo' },
            {
              id: 'q15-will',
              word: 'will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q15-go', word: 'go', translation: 'iré' },
            {
              id: 'q15-unless',
              word: 'unless',
              translation: 'a menos que',
            },
            { id: 'q15-it', word: 'it', translation: 'eso' },
            { id: 'q15-rains', word: 'rains.', translation: 'llueve' },
          ],
          correctOrder: ['q15-i', 'q15-will', 'q15-go', 'q15-unless', 'q15-it', 'q15-rains'],
          sentenceTranslation: 'Iré a menos que llueva.',
        },
        {
          id: 16,
          tokens: [
            { id: 'q16-anna', word: 'Anna', translation: 'Anna' },
            { id: 'q16-can', word: 'can', translation: 'puede' },
            {
              id: 'q16-borrow',
              word: 'borrow',
              translation: 'pedir prestado',
            },
            { id: 'q16-my', word: 'my', translation: 'mi' },
            { id: 'q16-car', word: 'car', translation: 'carro' },
            {
              id: 'q16-provided',
              word: 'provided',
              translation: 'siempre que',
            },
            { id: 'q16-she', word: 'she', translation: 'ella' },
            { id: 'q16-drives', word: 'drives', translation: 'maneja' },
            {
              id: 'q16-carefully',
              word: 'carefully.',
              translation: 'con cuidado',
            },
          ],
          correctOrder: ['q16-anna', 'q16-can', 'q16-borrow', 'q16-my', 'q16-car', 'q16-provided', 'q16-she', 'q16-drives', 'q16-carefully'],
          sentenceTranslation: 'Anna puede usar mi carro siempre que maneje con cuidado.',
        },
        {
          id: 17,
          tokens: [
            { id: 'q17-as', word: 'As', translation: 'mientras' },
            { id: 'q17-long', word: 'long', translation: 'tiempo' },
            { id: 'q17-as-2', word: 'as', translation: 'mientras' },
            { id: 'q17-sam', word: 'Sam', translation: 'Sam' },
            { id: 'q17-studies', word: 'studies,', translation: 'estudia' },
            { id: 'q17-he', word: 'he', translation: 'él' },
            {
              id: 'q17-will',
              word: 'will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q17-pass', word: 'pass.', translation: 'aprobará' },
          ],
          correctOrder: ['q17-as', 'q17-long', 'q17-as-2', 'q17-sam', 'q17-studies', 'q17-he', 'q17-will', 'q17-pass'],
          sentenceTranslation: 'Mientras Sam estudie, aprobará.',
        },
        {
          id: 18,
          tokens: [
            { id: 'q18-she', word: 'She', translation: 'ella' },
            { id: 'q18-wont', word: 'won’t', translation: 'no (futuro)' },
            { id: 'q18-come', word: 'come', translation: 'venir' },
            {
              id: 'q18-unless',
              word: 'unless',
              translation: 'a menos que',
            },
            { id: 'q18-you', word: 'you', translation: 'tú' },
            { id: 'q18-ask', word: 'ask', translation: 'pides' },
            { id: 'q18-her', word: 'her.', translation: 'ella' },
          ],
          correctOrder: ['q18-she', 'q18-wont', 'q18-come', 'q18-unless', 'q18-you', 'q18-ask', 'q18-her'],
          sentenceTranslation: 'Ella no vendrá a menos que se lo pidas.',
        },
        {
          id: 19,
          tokens: [
            { id: 'q19-they', word: 'They', translation: 'ellos' },
            { id: 'q19-can', word: 'can', translation: 'puede' },
            { id: 'q19-stay', word: 'stay', translation: 'quedarse' },
            { id: 'q19-as', word: 'as', translation: 'mientras' },
            { id: 'q19-long', word: 'long', translation: 'tiempo' },
            { id: 'q19-as-2', word: 'as', translation: 'mientras' },
            { id: 'q19-it', word: 'it', translation: 'eso' },
            { id: 'q19-is', word: 'is', translation: 'es' },
            { id: 'q19-quiet', word: 'quiet.', translation: 'tranquilo' },
          ],
          correctOrder: ['q19-they', 'q19-can', 'q19-stay', 'q19-as', 'q19-long', 'q19-as-2', 'q19-it', 'q19-is', 'q19-quiet'],
          sentenceTranslation: 'Pueden quedarse siempre que haya silencio.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Cuándo ocurre?',
      instructions: 'Escucha la oración y elige en qué caso ocurre la acción.',
      questions: [
        {
          id: 20,
          audioText: 'I’ll go unless it rains.',
          language: 'en',
          prompt: '¿Cuándo irá?',
          options: [
            { id: 'a', text: 'Si no llueve' },
            { id: 'b', text: 'Si llueve' },
          ],
          correctOptionIds: ['a'],
          explanation: 'unless it rains = si no llueve.',
        },
        {
          id: 21,
          audioText: 'She won’t come unless you ask her.',
          language: 'en',
          prompt: '¿Cuándo vendrá?',
          options: [
            { id: 'a', text: 'Si se lo piden' },
            { id: 'b', text: 'Si no se lo piden' },
          ],
          correctOptionIds: ['a'],
          explanation: 'won’t come unless you ask = solo vendrá si se lo pides.',
        },
        {
          id: 22,
          audioText: 'You can go out as long as you finish your homework.',
          language: 'en',
          prompt: '¿Cuándo puede salir?',
          options: [
            { id: 'a', text: 'Solo si termina la tarea' },
            { id: 'b', text: 'Aunque no termine la tarea' },
          ],
          correctOptionIds: ['a'],
          explanation: 'as long as = solo si.',
        },
        {
          id: 23,
          audioText: 'You can borrow my car provided you drive carefully.',
          language: 'en',
          prompt: '¿Cuál es la condición?',
          options: [
            { id: 'a', text: 'Manejar con cuidado' },
            { id: 'b', text: 'Devolverlo rápido' },
          ],
          correctOptionIds: ['a'],
          explanation: 'provided you drive carefully = siempre que manejes con cuidado.',
        },
        {
          id: 24,
          audioText: 'Unless you hurry, you will miss the train.',
          language: 'en',
          prompt: '¿Qué pasa si no se apura?',
          options: [
            { id: 'a', text: 'Perderá el tren' },
            { id: 'b', text: 'Llegará a tiempo' },
          ],
          correctOptionIds: ['a'],
          explanation: 'unless you hurry = si no te apuras: perderás el tren.',
        },
        {
          id: 25,
          audioText: 'They can stay as long as it is quiet.',
          language: 'en',
          prompt: '¿Qué deben hacer?',
          options: [
            { id: 'a', text: 'Mantener silencio' },
            { id: 'b', text: 'Irse temprano' },
          ],
          correctOptionIds: ['a'],
          explanation: 'as long as it is quiet = siempre que haya silencio.',
        },
      ],
    },
  ],
};

export default lessonB2009;
