import type { LessonContent } from '../types';

const lessonB2010: LessonContent = {
  level: 'b2',
  number: 10,
  title: 'Inversion in conditionals',
  subtitle: 'Aprende a reemplazar if por Had, Were y Should para condicionales más formales.',
  videoTitle: 'Inversion in conditionals',
  videoDescription: 'En este video verás Had I known..., Were I to... y Should you need..., y cuándo usarlas en registro formal.',
  objective: 'Al terminar, podrás formar condicionales con inversión y reconocer su equivalente con if.',
  exercises: [
    {
      type: 'fill-in-the-blanks',
      title: 'Had, were o should',
      instructions: 'Escribe Had, Were, Should o not para formar la condicional con inversión.',
      questions: [
        {
          id: 1,
          before: [],
          after: [
            { word: 'I', translation: 'yo' },
            { word: 'known,', translation: 'conocido' },
            { word: 'I', translation: 'yo' },
            { word: 'would', translation: 'habría / haría' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'called', translation: 'llamado' },
            { word: 'you.', translation: 'tú' },
          ],
          answer: 'Had',
          sentenceTranslation: 'De haberlo sabido, te habría llamado.',
        },
        {
          id: 2,
          before: [],
          after: [
            { word: 'she', translation: 'ella' },
            { word: 'to', translation: 'con' },
            { word: 'win,', translation: 'ganar' },
            { word: 'she', translation: 'ella' },
            { word: 'would', translation: 'habría / haría' },
            { word: 'buy', translation: 'comprar' },
            { word: 'a', translation: 'un/una' },
            { word: 'house.', translation: 'casa' },
          ],
          answer: 'Were',
          sentenceTranslation: 'Si ella ganara, compraría una casa.',
        },
        {
          id: 3,
          before: [],
          after: [
            { word: 'you', translation: 'tú' },
            { word: 'need', translation: 'necesitas' },
            { word: 'help,', translation: 'ayuda' },
            { word: 'call', translation: 'llamar' },
            { word: 'me.', translation: 'me' },
          ],
          answer: 'Should',
          sentenceTranslation: 'Si necesitas ayuda, llámame.',
        },
        {
          id: 4,
          before: [],
          after: [
            { word: 'she', translation: 'ella' },
            { word: 'studied,', translation: 'estudiado' },
            { word: 'she', translation: 'ella' },
            { word: 'would', translation: 'habría / haría' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'passed.', translation: 'aprobado' },
          ],
          answer: 'Had',
          sentenceTranslation: 'De haber estudiado, habría aprobado.',
        },
        {
          id: 5,
          before: [],
          after: [
            { word: 'they', translation: 'ellos' },
            { word: 'to', translation: 'con' },
            { word: 'agree,', translation: 'estar de acuerdo' },
            { word: 'the', translation: 'el/la' },
            { word: 'deal', translation: 'trato' },
            { word: 'would', translation: 'habría / haría' },
            { word: 'close.', translation: 'cerraría' },
          ],
          answer: 'Were',
          sentenceTranslation: 'Si ellos aceptaran, el trato se cerraría.',
        },
        {
          id: 6,
          before: [],
          after: [
            { word: 'it', translation: 'eso' },
            { word: 'rain,', translation: 'llueve' },
            { word: 'the', translation: 'el/la' },
            { word: 'event', translation: 'evento' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'be', translation: 'ser / estar' },
            { word: 'moved.', translation: 'trasladado' },
          ],
          answer: 'Should',
          sentenceTranslation: 'Si llueve, el evento se trasladará.',
        },
        {
          id: 7,
          before: [
            { word: 'Had', translation: 'tenido' },
            { word: 'I', translation: 'yo' },
          ],
          after: [
            { word: 'seen', translation: 'visto' },
            { word: 'it,', translation: 'eso' },
            { word: 'I', translation: 'yo' },
            { word: 'wouldn’t', translation: 'no habría' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'believed', translation: 'creído' },
            { word: 'it.', translation: 'eso' },
          ],
          answer: 'not',
          sentenceTranslation: 'De no haberlo visto, no lo habría creído.',
        },
        {
          id: 8,
          before: [],
          after: [
            { word: 'it', translation: 'eso' },
            { word: 'not', translation: 'no' },
            { word: 'for', translation: 'por' },
            { word: 'the', translation: 'el/la' },
            { word: 'noise,', translation: 'ruido' },
            { word: 'I', translation: 'yo' },
            { word: 'would', translation: 'habría / haría' },
            { word: 'sleep.', translation: 'dormiría' },
          ],
          answer: 'Were',
          sentenceTranslation: 'De no ser por el ruido, dormiría.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Completa con el participio',
      instructions: 'Escribe el participio del verbo entre paréntesis para completar el condicional tipo 3 con Had.',
      questions: [
        {
          id: 9,
          before: [
            { word: 'Had', translation: 'tenido' },
            { word: 'we', translation: 'nosotros' },
          ],
          after: [
            { word: 'earlier,', translation: 'antes' },
            { word: 'we', translation: 'nosotros' },
            { word: 'wouldn’t', translation: 'no habría' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'missed', translation: 'perdido' },
            { word: 'the', translation: 'el/la' },
            { word: 'flight.', translation: 'vuelo' },
          ],
          answer: 'left',
          hint: 'leave',
          sentenceTranslation: 'De haber salido antes, no habríamos perdido el vuelo.',
        },
        {
          id: 10,
          before: [
            { word: 'Had', translation: 'tenido' },
            { word: 'they', translation: 'ellos' },
          ],
          after: [
            { word: 'they', translation: 'ellos' },
            { word: 'would', translation: 'habría / haría' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'understood.', translation: 'entendido' },
          ],
          answer: 'listened',
          hint: 'listen',
          sentenceTranslation: 'De haber escuchado, habrían entendido.',
        },
        {
          id: 11,
          before: [
            { word: 'Had', translation: 'tenido' },
            { word: 'he', translation: 'él' },
          ],
          after: [
            { word: 'there,', translation: 'allí' },
            { word: 'he', translation: 'él' },
            { word: 'would', translation: 'habría / haría' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'helped.', translation: 'ayudado' },
          ],
          answer: 'been',
          hint: 'be',
          sentenceTranslation: 'De haber estado allí, habría ayudado.',
        },
        {
          id: 12,
          before: [
            { word: 'Had', translation: 'tenido' },
            { word: 'you', translation: 'tú' },
          ],
          after: [
            { word: 'me,', translation: 'me' },
            { word: 'I', translation: 'yo' },
            { word: 'would', translation: 'habría / haría' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'come.', translation: 'venido' },
          ],
          answer: 'told',
          hint: 'tell',
          sentenceTranslation: 'De habérmelo dicho, habría venido.',
        },
        {
          id: 13,
          before: [
            { word: 'Had', translation: 'tenido' },
            { word: 'she', translation: 'ella' },
          ],
          after: [
            { word: 'the', translation: 'el/la' },
            { word: 'risks,', translation: 'riesgos' },
            { word: 'she', translation: 'ella' },
            { word: 'would', translation: 'habría / haría' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'refused.', translation: 'rechazado' },
          ],
          answer: 'known',
          hint: 'know',
          sentenceTranslation: 'De haber sabido los riesgos, habría rechazado.',
        },
        {
          id: 14,
          before: [
            { word: 'Had', translation: 'tenido' },
            { word: 'the', translation: 'el/la' },
            { word: 'manager', translation: 'gerente' },
          ],
          after: [
            { word: 'earlier,', translation: 'antes' },
            { word: 'we', translation: 'nosotros' },
            { word: 'would', translation: 'habría / haría' },
            { word: 'have', translation: 'he / hemos' },
            { word: 'started.', translation: 'empezado' },
          ],
          answer: 'arrived',
          hint: 'arrive',
          sentenceTranslation: 'De haber llegado antes el gerente, habríamos empezado.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 15,
          tokens: [
            { id: 'q15-had', word: 'Had', translation: 'tenido' },
            { id: 'q15-tom', word: 'Tom', translation: 'Tom' },
            { id: 'q15-known', word: 'known,', translation: 'conocido' },
            { id: 'q15-he', word: 'he', translation: 'él' },
            {
              id: 'q15-would',
              word: 'would',
              translation: 'habría / haría',
            },
            { id: 'q15-have', word: 'have', translation: 'he / hemos' },
            { id: 'q15-called', word: 'called.', translation: 'llamado' },
          ],
          correctOrder: ['q15-had', 'q15-tom', 'q15-known', 'q15-he', 'q15-would', 'q15-have', 'q15-called'],
          sentenceTranslation: 'De haberlo sabido Tom, habría llamado.',
        },
        {
          id: 16,
          tokens: [
            { id: 'q16-were', word: 'Were', translation: 'fuera' },
            { id: 'q16-ana', word: 'Ana', translation: 'Ana' },
            { id: 'q16-to', word: 'to', translation: 'con' },
            { id: 'q16-leave', word: 'leave,', translation: 'irse' },
            { id: 'q16-we', word: 'we', translation: 'nosotros' },
            {
              id: 'q16-would',
              word: 'would',
              translation: 'habría / haría',
            },
            { id: 'q16-be', word: 'be', translation: 'ser / estar' },
            { id: 'q16-sad', word: 'sad.', translation: 'triste' },
          ],
          correctOrder: ['q16-were', 'q16-ana', 'q16-to', 'q16-leave', 'q16-we', 'q16-would', 'q16-be', 'q16-sad'],
          sentenceTranslation: 'Si Ana se fuera, estaríamos tristes.',
        },
        {
          id: 17,
          tokens: [
            { id: 'q17-should', word: 'Should', translation: 'si' },
            { id: 'q17-you', word: 'you', translation: 'tú' },
            { id: 'q17-need', word: 'need', translation: 'necesitas' },
            { id: 'q17-help', word: 'help,', translation: 'ayuda' },
            { id: 'q17-call', word: 'call', translation: 'llamar' },
            { id: 'q17-me', word: 'me.', translation: 'me' },
          ],
          correctOrder: ['q17-should', 'q17-you', 'q17-need', 'q17-help', 'q17-call', 'q17-me'],
          sentenceTranslation: 'Si necesitas ayuda, llámame.',
        },
        {
          id: 18,
          tokens: [
            { id: 'q18-had', word: 'Had', translation: 'tenido' },
            { id: 'q18-sam', word: 'Sam', translation: 'Sam' },
            { id: 'q18-not', word: 'not', translation: 'no' },
            { id: 'q18-called', word: 'called,', translation: 'llamado' },
            { id: 'q18-we', word: 'we', translation: 'nosotros' },
            {
              id: 'q18-wouldnt',
              word: 'wouldn’t',
              translation: 'no habría',
            },
            { id: 'q18-have', word: 'have', translation: 'he / hemos' },
            { id: 'q18-known', word: 'known.', translation: 'conocido' },
          ],
          correctOrder: ['q18-had', 'q18-sam', 'q18-not', 'q18-called', 'q18-we', 'q18-wouldnt', 'q18-have', 'q18-known'],
          sentenceTranslation: 'De no haber llamado Sam, no lo habríamos sabido.',
        },
        {
          id: 19,
          tokens: [
            { id: 'q19-were', word: 'Were', translation: 'fuera' },
            { id: 'q19-it', word: 'it', translation: 'eso' },
            { id: 'q19-not', word: 'not', translation: 'no' },
            { id: 'q19-for', word: 'for', translation: 'por' },
            { id: 'q19-the', word: 'the', translation: 'el/la' },
            { id: 'q19-noise', word: 'noise,', translation: 'ruido' },
            { id: 'q19-i', word: 'I', translation: 'yo' },
            {
              id: 'q19-would',
              word: 'would',
              translation: 'habría / haría',
            },
            { id: 'q19-sleep', word: 'sleep.', translation: 'dormiría' },
          ],
          correctOrder: ['q19-were', 'q19-it', 'q19-not', 'q19-for', 'q19-the', 'q19-noise', 'q19-i', 'q19-would', 'q19-sleep'],
          sentenceTranslation: 'De no ser por el ruido, dormiría.',
        },
        {
          id: 20,
          tokens: [
            { id: 'q20-should', word: 'Should', translation: 'si' },
            { id: 'q20-it', word: 'it', translation: 'eso' },
            { id: 'q20-rain', word: 'rain,', translation: 'llueve' },
            { id: 'q20-the', word: 'the', translation: 'el/la' },
            { id: 'q20-event', word: 'event', translation: 'evento' },
            {
              id: 'q20-will',
              word: 'will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q20-be', word: 'be', translation: 'ser / estar' },
            { id: 'q20-moved', word: 'moved.', translation: 'trasladado' },
          ],
          correctOrder: ['q20-should', 'q20-it', 'q20-rain', 'q20-the', 'q20-event', 'q20-will', 'q20-be', 'q20-moved'],
          sentenceTranslation: 'Si llueve, el evento se trasladará.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Cuál es la versión con if?',
      instructions: 'Escucha la oración con inversión y elige la oración equivalente con if.',
      questions: [
        {
          id: 21,
          audioText: 'Had I known, I would have called.',
          language: 'en',
          prompt: '¿Cuál es la versión con if?',
          options: [
            { id: 'a', text: 'If I had known, I would have called.' },
            { id: 'b', text: 'If I knew, I would call.' },
          ],
          correctOptionIds: ['a'],
          explanation: 'Had I known = If I had known.',
        },
        {
          id: 22,
          audioText: 'Were she to win, she would buy a house.',
          language: 'en',
          prompt: '¿Cuál es la versión con if?',
          options: [
            {
              id: 'a',
              text: 'If she had won, she would have bought a house.',
            },
            { id: 'b', text: 'If she were to win, she would buy a house.' },
          ],
          correctOptionIds: ['b'],
          explanation: 'Were she to win = If she were to win.',
        },
        {
          id: 23,
          audioText: 'Should you need help, call me.',
          language: 'en',
          prompt: '¿Cuál es la versión con if?',
          options: [
            { id: 'a', text: 'If you need help, call me.' },
            {
              id: 'b',
              text: 'If you had needed help, you would have called me.',
            },
          ],
          correctOptionIds: ['a'],
          explanation: 'Should you need = If you need.',
        },
        {
          id: 24,
          audioText: 'Had they left earlier, they would have arrived on time.',
          language: 'en',
          prompt: '¿Cuál es la versión con if?',
          options: [
            {
              id: 'a',
              text: 'If they leave earlier, they will arrive on time.',
            },
            {
              id: 'b',
              text: 'If they had left earlier, they would have arrived on time.',
            },
          ],
          correctOptionIds: ['b'],
          explanation: 'Had they left = If they had left.',
        },
        {
          id: 25,
          audioText: 'Should it rain, we will stay home.',
          language: 'en',
          prompt: '¿Cuál es la versión con if?',
          options: [
            { id: 'a', text: 'If it rains, we will stay home.' },
            { id: 'b', text: 'If it rained, we would stay home.' },
          ],
          correctOptionIds: ['a'],
          explanation: 'Should it rain = If it rains.',
        },
        {
          id: 26,
          audioText: 'Were he to resign, we would be in trouble.',
          language: 'en',
          prompt: '¿Cuál es la versión con if?',
          options: [
            {
              id: 'a',
              text: 'If he had resigned, we would have been in trouble.',
            },
            {
              id: 'b',
              text: 'If he were to resign, we would be in trouble.',
            },
          ],
          correctOptionIds: ['b'],
          explanation: 'Were he to resign = If he were to resign.',
        },
      ],
    },
  ],
};

export default lessonB2010;
