import type { LessonContent } from '../types';

const lessonB2014: LessonContent = {
  level: 'b2',
  number: 14,
  title: 'Passive reporting structures',
  subtitle: 'Aprende estructuras como It is said that... y He is said to... para reportar lo que se dice o se cree.',
  videoTitle: 'Passive reporting structures',
  videoDescription: 'En este video verás las dos estructuras pasivas de reporte (It is said that... y He is said to...), con infinitivo simple, perfecto y continuo.',
  objective: 'Al terminar, podrás usar estructuras pasivas de reporte para hablar de lo que se dice, se cree o se piensa.',
  exercises: [
    {
      type: 'fill-in-the-blanks',
      title: 'It is said that...',
      instructions: 'Escribe el participio del verbo entre paréntesis para completar la estructura It + pasiva + that.',
      questions: [
        {
          id: 1,
          before: [
            { word: 'It', translation: 'eso' },
            { word: 'is', translation: 'es' },
          ],
          after: [
            { word: 'that', translation: 'que' },
            { word: 'the', translation: 'el/la' },
            { word: 'mayor', translation: 'alcalde' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'resign.', translation: 'renunciará' },
          ],
          answer: 'said',
          hint: 'say',
          sentenceTranslation: 'Se dice que el alcalde renunciará.',
        },
        {
          id: 2,
          before: [
            { word: 'It', translation: 'eso' },
            { word: 'is', translation: 'es' },
          ],
          after: [
            { word: 'that', translation: 'que' },
            { word: 'he', translation: 'él' },
            { word: 'is', translation: 'es' },
            { word: 'innocent.', translation: 'inocente' },
          ],
          answer: 'believed',
          hint: 'believe',
          sentenceTranslation: 'Se cree que es inocente.',
        },
        {
          id: 3,
          before: [
            { word: 'It', translation: 'eso' },
            { word: 'is', translation: 'es' },
          ],
          after: [
            { word: 'that', translation: 'que' },
            { word: 'smoking', translation: 'fumar' },
            { word: 'is', translation: 'es' },
            { word: 'harmful.', translation: 'dañino' },
          ],
          answer: 'known',
          hint: 'know',
          sentenceTranslation: 'Se sabe que fumar es dañino.',
        },
        {
          id: 4,
          before: [
            { word: 'It', translation: 'eso' },
            { word: 'was', translation: 'fue' },
          ],
          after: [
            { word: 'that', translation: 'que' },
            { word: 'three', translation: 'tres' },
            { word: 'people', translation: 'personas' },
            { word: 'were', translation: 'eran' },
            { word: 'injured.', translation: 'heridas' },
          ],
          answer: 'reported',
          hint: 'report',
          sentenceTranslation: 'Se informó que tres personas resultaron heridas.',
        },
        {
          id: 5,
          before: [
            { word: 'It', translation: 'eso' },
            { word: 'is', translation: 'es' },
          ],
          after: [
            { word: 'that', translation: 'que' },
            { word: 'prices', translation: 'precios' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'rise.', translation: 'subir' },
          ],
          answer: 'expected',
          hint: 'expect',
          sentenceTranslation: 'Se espera que los precios suban.',
        },
        {
          id: 6,
          before: [
            { word: 'It', translation: 'eso' },
            { word: 'is', translation: 'es' },
          ],
          after: [
            { word: 'that', translation: 'que' },
            { word: 'the', translation: 'el/la' },
            { word: 'fire', translation: 'incendio' },
            { word: 'started', translation: 'empezó' },
            { word: 'in', translation: 'en' },
            { word: 'the', translation: 'el/la' },
            { word: 'kitchen.', translation: 'cocina' },
          ],
          answer: 'thought',
          hint: 'think',
          sentenceTranslation: 'Se piensa que el incendio empezó en la cocina.',
        },
        {
          id: 7,
          before: [
            { word: 'It', translation: 'eso' },
            { word: 'is', translation: 'es' },
          ],
          after: [
            { word: 'that', translation: 'que' },
            { word: 'he', translation: 'él' },
            { word: 'stole', translation: 'robó' },
            { word: 'the', translation: 'el/la' },
            { word: 'money.', translation: 'dinero' },
          ],
          answer: 'claimed',
          hint: 'claim',
          sentenceTranslation: 'Se afirma que robó el dinero.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'He is said to...',
      instructions: 'Escribe la palabra que falta: to, have, be o el verbo con ING.',
      questions: [
        {
          id: 8,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'mayor', translation: 'alcalde' },
            { word: 'is', translation: 'es' },
            { word: 'said', translation: 'dicho' },
          ],
          after: [
            { word: 'be', translation: 'ser / estar' },
            { word: 'corrupt.', translation: 'corrupto' },
          ],
          answer: 'to',
          sentenceTranslation: 'Se dice que el alcalde es corrupto.',
        },
        {
          id: 9,
          before: [
            { word: 'He', translation: 'él' },
            { word: 'is', translation: 'es' },
            { word: 'said', translation: 'dicho' },
            { word: 'to', translation: 'para' },
          ],
          after: [
            { word: 'won', translation: 'ganado' },
            { word: 'the', translation: 'el/la' },
            { word: 'lottery.', translation: 'lotería' },
          ],
          answer: 'have',
          sentenceTranslation: 'Se dice que ganó la lotería.',
        },
        {
          id: 10,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'is', translation: 'es' },
            { word: 'believed', translation: 'creído' },
            { word: 'to', translation: 'para' },
          ],
          after: [
            { word: 'in', translation: 'en' },
            { word: 'Paris.', translation: 'París' },
          ],
          answer: 'be',
          sentenceTranslation: 'Se cree que está en París.',
        },
        {
          id: 11,
          before: [
            { word: 'The', translation: 'el/la' },
            { word: 'company', translation: 'empresa' },
            { word: 'is', translation: 'es' },
            { word: 'reported', translation: 'informado' },
            { word: 'to', translation: 'para' },
          ],
          after: [
            { word: 'lost', translation: 'perdido' },
            { word: 'millions.', translation: 'millones' },
          ],
          answer: 'have',
          sentenceTranslation: 'Se informa que la empresa perdió millones.',
        },
        {
          id: 12,
          before: [
            { word: 'They', translation: 'ellos' },
            { word: 'are', translation: 'son' },
            { word: 'thought', translation: 'pensado' },
            { word: 'to', translation: 'para' },
            { word: 'be', translation: 'ser / estar' },
          ],
          after: [
            { word: 'abroad.', translation: 'en el extranjero' },
          ],
          answer: 'working',
          hint: 'work',
          sentenceTranslation: 'Se piensa que están trabajando en el extranjero.',
        },
        {
          id: 13,
          before: [
            { word: 'She', translation: 'ella' },
            { word: 'is', translation: 'es' },
            { word: 'known', translation: 'conocido' },
          ],
          after: [
            { word: 'speak', translation: 'hablar' },
            { word: 'five', translation: 'cinco' },
            { word: 'languages.', translation: 'idiomas' },
          ],
          answer: 'to',
          sentenceTranslation: 'Se sabe que habla cinco idiomas.',
        },
        {
          id: 14,
          before: [
            { word: 'He', translation: 'él' },
            { word: 'is', translation: 'es' },
            { word: 'believed', translation: 'creído' },
            { word: 'to', translation: 'para' },
            { word: 'be', translation: 'ser / estar' },
          ],
          after: [
            { word: 'in', translation: 'en' },
            { word: 'Rome.', translation: 'Roma' },
          ],
          answer: 'living',
          hint: 'live',
          sentenceTranslation: 'Se cree que está viviendo en Roma.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 15,
          tokens: [
            { id: 'q15-it', word: 'It', translation: 'eso' },
            { id: 'q15-is', word: 'is', translation: 'es' },
            { id: 'q15-said', word: 'said', translation: 'dicho' },
            { id: 'q15-that', word: 'that', translation: 'que' },
            { id: 'q15-he', word: 'he', translation: 'él' },
            { id: 'q15-is-2', word: 'is', translation: 'es' },
            { id: 'q15-rich', word: 'rich.', translation: 'rico' },
          ],
          correctOrder: ['q15-it', 'q15-is', 'q15-said', 'q15-that', 'q15-he', 'q15-is-2', 'q15-rich'],
          sentenceTranslation: 'Se dice que es rico.',
        },
        {
          id: 16,
          tokens: [
            { id: 'q16-she', word: 'She', translation: 'ella' },
            { id: 'q16-is', word: 'is', translation: 'es' },
            { id: 'q16-believed', word: 'believed', translation: 'creído' },
            { id: 'q16-to', word: 'to', translation: 'para' },
            { id: 'q16-be', word: 'be', translation: 'ser / estar' },
            { id: 'q16-in', word: 'in', translation: 'en' },
            { id: 'q16-paris', word: 'Paris.', translation: 'París' },
          ],
          correctOrder: ['q16-she', 'q16-is', 'q16-believed', 'q16-to', 'q16-be', 'q16-in', 'q16-paris'],
          sentenceTranslation: 'Se cree que está en París.',
        },
        {
          id: 17,
          tokens: [
            { id: 'q17-he', word: 'He', translation: 'él' },
            { id: 'q17-is', word: 'is', translation: 'es' },
            { id: 'q17-said', word: 'said', translation: 'dicho' },
            { id: 'q17-to', word: 'to', translation: 'para' },
            { id: 'q17-have', word: 'have', translation: 'tengo' },
            { id: 'q17-won', word: 'won', translation: 'ganado' },
            { id: 'q17-the', word: 'the', translation: 'el/la' },
            { id: 'q17-lottery', word: 'lottery.', translation: 'lotería' },
          ],
          correctOrder: ['q17-he', 'q17-is', 'q17-said', 'q17-to', 'q17-have', 'q17-won', 'q17-the', 'q17-lottery'],
          sentenceTranslation: 'Se dice que ganó la lotería.',
        },
        {
          id: 18,
          tokens: [
            { id: 'q18-the', word: 'The', translation: 'el/la' },
            { id: 'q18-company', word: 'company', translation: 'empresa' },
            { id: 'q18-is', word: 'is', translation: 'es' },
            {
              id: 'q18-reported',
              word: 'reported',
              translation: 'informado',
            },
            { id: 'q18-to', word: 'to', translation: 'para' },
            { id: 'q18-have', word: 'have', translation: 'tengo' },
            { id: 'q18-lost', word: 'lost', translation: 'perdido' },
            {
              id: 'q18-millions',
              word: 'millions.',
              translation: 'millones',
            },
          ],
          correctOrder: ['q18-the', 'q18-company', 'q18-is', 'q18-reported', 'q18-to', 'q18-have', 'q18-lost', 'q18-millions'],
          sentenceTranslation: 'Se informa que la empresa perdió millones.',
        },
        {
          id: 19,
          tokens: [
            { id: 'q19-it', word: 'It', translation: 'eso' },
            { id: 'q19-is', word: 'is', translation: 'es' },
            {
              id: 'q19-expected',
              word: 'expected',
              translation: 'esperado',
            },
            { id: 'q19-that', word: 'that', translation: 'que' },
            { id: 'q19-prices', word: 'prices', translation: 'precios' },
            {
              id: 'q19-will',
              word: 'will',
              translation: 'auxiliar de futuro',
            },
            { id: 'q19-rise', word: 'rise.', translation: 'subir' },
          ],
          correctOrder: ['q19-it', 'q19-is', 'q19-expected', 'q19-that', 'q19-prices', 'q19-will', 'q19-rise'],
          sentenceTranslation: 'Se espera que los precios suban.',
        },
        {
          id: 20,
          tokens: [
            { id: 'q20-they', word: 'They', translation: 'ellos' },
            { id: 'q20-are', word: 'are', translation: 'son' },
            { id: 'q20-thought', word: 'thought', translation: 'pensado' },
            { id: 'q20-to', word: 'to', translation: 'para' },
            { id: 'q20-be', word: 'be', translation: 'ser / estar' },
            {
              id: 'q20-working',
              word: 'working',
              translation: 'trabajando',
            },
            {
              id: 'q20-abroad',
              word: 'abroad.',
              translation: 'en el extranjero',
            },
          ],
          correctOrder: ['q20-they', 'q20-are', 'q20-thought', 'q20-to', 'q20-be', 'q20-working', 'q20-abroad'],
          sentenceTranslation: 'Se piensa que están trabajando en el extranjero.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Ahora o antes?',
      instructions: 'Escucha la oración. to be = algo que ocurre ahora; to have + participio = algo que ocurrió antes.',
      questions: [
        {
          id: 21,
          audioText: 'He is said to be very rich.',
          language: 'en',
          prompt: '¿Cuándo ocurre lo que se dice?',
          options: [
            { id: 'now', text: 'Ahora' },
            { id: 'before', text: 'Antes' },
          ],
          correctOptionIds: ['now'],
          explanation: 'to be = ahora.',
        },
        {
          id: 22,
          audioText: 'He is said to have won the lottery.',
          language: 'en',
          prompt: '¿Cuándo ocurre lo que se dice?',
          options: [
            { id: 'now', text: 'Ahora' },
            { id: 'before', text: 'Antes' },
          ],
          correctOptionIds: ['before'],
          explanation: 'to have won = antes.',
        },
        {
          id: 23,
          audioText: 'She is believed to be in Paris.',
          language: 'en',
          prompt: '¿Cuándo ocurre lo que se dice?',
          options: [
            { id: 'now', text: 'Ahora' },
            { id: 'before', text: 'Antes' },
          ],
          correctOptionIds: ['now'],
          explanation: 'to be = ahora.',
        },
        {
          id: 24,
          audioText: 'She is believed to have left the country.',
          language: 'en',
          prompt: '¿Cuándo ocurre lo que se dice?',
          options: [
            { id: 'now', text: 'Ahora' },
            { id: 'before', text: 'Antes' },
          ],
          correctOptionIds: ['before'],
          explanation: 'to have left = antes.',
        },
        {
          id: 25,
          audioText: 'They are thought to be working abroad.',
          language: 'en',
          prompt: '¿Cuándo ocurre lo que se dice?',
          options: [
            { id: 'now', text: 'Ahora' },
            { id: 'before', text: 'Antes' },
          ],
          correctOptionIds: ['now'],
          explanation: 'to be working = ahora, en progreso.',
        },
        {
          id: 26,
          audioText: 'The company is reported to have lost millions.',
          language: 'en',
          prompt: '¿Cuándo ocurre lo que se dice?',
          options: [
            { id: 'now', text: 'Ahora' },
            { id: 'before', text: 'Antes' },
          ],
          correctOptionIds: ['before'],
          explanation: 'to have lost = antes.',
        },
      ],
    },
  ],
};

export default lessonB2014;
