import type { LessonContent } from '../types';

const lessonB2016: LessonContent = {
  level: 'b2',
  number: 16,
  title: 'Reported speech avanzado',
  subtitle: 'Aprende a contar lo que otros dijeron: retroceso de tiempos, preguntas, órdenes y cambios de tiempo y lugar.',
  videoTitle: 'Reported speech avanzado',
  videoDescription: 'En este video verás el retroceso de tiempos, los cambios de tiempo y lugar, y el discurso indirecto de preguntas y órdenes.',
  objective: 'Al terminar, podrás reportar lo que otros dijeron con los cambios de tiempo, pronombres y expresiones de tiempo.',
  exercises: [
    {
      type: 'fill-in-the-blanks',
      title: 'Retroceso de tiempos',
      instructions: 'Escribe la forma correcta en el discurso indirecto: was, would, could, had, might o el verbo en pasado.',
      questions: [
        {
          id: 1,
          before: [
            { word: '“I', translation: 'yo' },
            { word: 'am', translation: 'voy' },
            { word: 'tired,”', translation: 'cansado' },
            { word: 'he', translation: 'él' },
            { word: 'said.', translation: 'dijo' },
            { word: '→', translation: '→' },
            { word: 'He', translation: 'él' },
            { word: 'said', translation: 'dijo' },
            { word: 'he', translation: 'él' },
          ],
          after: [
            { word: 'tired.', translation: 'cansado' },
          ],
          answer: 'was',
          sentenceTranslation: '“Estoy cansado,” dijo. → Dijo que estaba cansado.',
        },
        {
          id: 2,
          before: [
            { word: '“I', translation: 'yo' },
            { word: 'will', translation: 'auxiliar de futuro' },
            { word: 'call', translation: 'llamar' },
            { word: 'you.”', translation: 'tú' },
            { word: '→', translation: '→' },
            { word: 'She', translation: 'ella' },
            { word: 'said', translation: 'dijo' },
            { word: 'she', translation: 'ella' },
          ],
          after: [
            { word: 'call', translation: 'llamar' },
            { word: 'me.', translation: 'me' },
          ],
          answer: 'would',
          sentenceTranslation: '“Te llamaré.” → Dijo que me llamaría.',
        },
        {
          id: 3,
          before: [
            { word: '“I', translation: 'yo' },
            { word: 'can', translation: 'puedo' },
            { word: 'swim.”', translation: 'nadar' },
            { word: '→', translation: '→' },
            { word: 'She', translation: 'ella' },
            { word: 'said', translation: 'dijo' },
            { word: 'she', translation: 'ella' },
          ],
          after: [
            { word: 'swim.', translation: 'nadar' },
          ],
          answer: 'could',
          sentenceTranslation: '“Sé nadar.” → Dijo que sabía nadar.',
        },
        {
          id: 4,
          before: [
            { word: '“We', translation: 'nosotros' },
            { word: 'have', translation: 'tengo' },
            { word: 'finished.”', translation: 'terminado' },
            { word: '→', translation: '→' },
            { word: 'They', translation: 'ellos' },
            { word: 'said', translation: 'dijo' },
            { word: 'they', translation: 'ellos' },
          ],
          after: [
            { word: 'finished.', translation: 'terminado' },
          ],
          answer: 'had',
          sentenceTranslation: '“Hemos terminado.” → Dijeron que habían terminado.',
        },
        {
          id: 5,
          before: [
            { word: '“I', translation: 'yo' },
            { word: 'work', translation: 'trabajo' },
            { word: 'here.”', translation: 'aquí' },
            { word: '→', translation: '→' },
            { word: 'He', translation: 'él' },
            { word: 'said', translation: 'dijo' },
            { word: 'he', translation: 'él' },
          ],
          after: [
            { word: 'there.', translation: 'hay' },
          ],
          answer: 'worked',
          hint: 'work',
          sentenceTranslation: '“Trabajo aquí.” → Dijo que trabajaba allí.',
        },
        {
          id: 6,
          before: [
            { word: '“I’m', translation: 'yo estoy' },
            { word: 'studying.”', translation: 'estudiando' },
            { word: '→', translation: '→' },
            { word: 'She', translation: 'ella' },
            { word: 'said', translation: 'dijo' },
            { word: 'she', translation: 'ella' },
            { word: 'was', translation: 'estaba' },
          ],
          after: [],
          answer: 'studying',
          hint: 'study',
          sentenceTranslation: '“Estoy estudiando.” → Dijo que estaba estudiando.',
        },
        {
          id: 7,
          before: [
            { word: '“I', translation: 'yo' },
            { word: 'may', translation: 'puede que' },
            { word: 'come.”', translation: 'venir' },
            { word: '→', translation: '→' },
            { word: 'He', translation: 'él' },
            { word: 'said', translation: 'dijo' },
            { word: 'he', translation: 'él' },
          ],
          after: [
            { word: 'come.', translation: 'venir' },
          ],
          answer: 'might',
          sentenceTranslation: '“Puede que venga.” → Dijo que podría venir.',
        },
        {
          id: 8,
          before: [
            { word: '“I', translation: 'yo' },
            { word: 'saw', translation: 'vi' },
            { word: 'him.”', translation: 'lo' },
            { word: '→', translation: '→' },
            { word: 'She', translation: 'ella' },
            { word: 'said', translation: 'dijo' },
            { word: 'she', translation: 'ella' },
          ],
          after: [
            { word: 'seen', translation: 'visto' },
            { word: 'him.', translation: 'lo' },
          ],
          answer: 'had',
          sentenceTranslation: '“Lo vi.” → Dijo que lo había visto.',
        },
      ],
    },
    {
      type: 'fill-in-the-blanks',
      title: 'Cambios de tiempo, lugar y preguntas',
      instructions: 'Escribe la palabra que falta en el discurso indirecto.',
      questions: [
        {
          id: 9,
          before: [
            { word: '“I’m', translation: 'yo estoy' },
            { word: 'leaving', translation: 'saliendo' },
            { word: 'tomorrow.”', translation: 'mañana' },
            { word: '→', translation: '→' },
            { word: 'She', translation: 'ella' },
            { word: 'said', translation: 'dijo' },
            { word: 'she', translation: 'ella' },
            { word: 'was', translation: 'estaba' },
            { word: 'leaving', translation: 'saliendo' },
            { word: 'the', translation: 'el/la' },
            { word: 'next', translation: 'al lado' },
          ],
          after: [],
          answer: 'day',
          sentenceTranslation: '“Me voy mañana.” → Dijo que se iba al día siguiente.',
        },
        {
          id: 10,
          before: [
            { word: '“I', translation: 'yo' },
            { word: 'live', translation: 'vivir' },
            { word: 'here.”', translation: 'aquí' },
            { word: '→', translation: '→' },
            { word: 'He', translation: 'él' },
            { word: 'said', translation: 'dijo' },
            { word: 'he', translation: 'él' },
            { word: 'lived', translation: 'vivía' },
          ],
          after: [],
          answer: 'there',
          sentenceTranslation: '“Vivo aquí.” → Dijo que vivía allí.',
        },
        {
          id: 11,
          before: [
            { word: '“I', translation: 'yo' },
            { word: 'saw', translation: 'vi' },
            { word: 'it', translation: 'eso' },
            { word: 'yesterday.”', translation: 'ayer' },
            { word: '→', translation: '→' },
            { word: 'She', translation: 'ella' },
            { word: 'said', translation: 'dijo' },
            { word: 'she', translation: 'ella' },
            { word: 'had', translation: 'hice' },
            { word: 'seen', translation: 'visto' },
            { word: 'it', translation: 'eso' },
            { word: 'the', translation: 'el/la' },
            { word: 'day', translation: 'día' },
          ],
          after: [],
          answer: 'before',
          sentenceTranslation: '“Lo vi ayer.” → Dijo que lo había visto el día anterior.',
        },
        {
          id: 12,
          before: [
            { word: '“I’m', translation: 'yo estoy' },
            { word: 'busy', translation: 'ocupado' },
            { word: 'now.”', translation: 'ahora' },
            { word: '→', translation: '→' },
            { word: 'He', translation: 'él' },
            { word: 'said', translation: 'dijo' },
            { word: 'he', translation: 'él' },
            { word: 'was', translation: 'estaba' },
            { word: 'busy', translation: 'ocupado' },
          ],
          after: [],
          answer: 'then',
          sentenceTranslation: '“Estoy ocupado ahora.” → Dijo que estaba ocupado entonces.',
        },
        {
          id: 13,
          before: [
            { word: '“Sit', translation: 'siéntate' },
            { word: 'down!”', translation: 'abajo' },
            { word: '→', translation: '→' },
            { word: 'He', translation: 'él' },
            { word: 'told', translation: 'dijo' },
            { word: 'me', translation: 'me' },
          ],
          after: [
            { word: 'sit', translation: 'siéntate' },
            { word: 'down.', translation: 'abajo' },
          ],
          answer: 'to',
          sentenceTranslation: '“¡Siéntate!” → Me dijo que me sentara.',
        },
        {
          id: 14,
          before: [
            { word: '“Are', translation: 'son / están' },
            { word: 'you', translation: 'tú' },
            { word: 'tired?”', translation: 'cansado' },
            { word: '→', translation: '→' },
            { word: 'He', translation: 'él' },
            { word: 'asked', translation: 'preguntó' },
          ],
          after: [
            { word: 'I', translation: 'yo' },
            { word: 'was', translation: 'estaba' },
            { word: 'tired.', translation: 'cansado' },
          ],
          answer: 'if',
          sentenceTranslation: '“¿Estás cansado?” → Preguntó si yo estaba cansado.',
        },
        {
          id: 15,
          before: [
            { word: '“Where', translation: 'dónde' },
            { word: 'do', translation: 'hacer' },
            { word: 'you', translation: 'tú' },
            { word: 'live?”', translation: 'vivir' },
            { word: '→', translation: '→' },
            { word: 'She', translation: 'ella' },
            { word: 'asked', translation: 'preguntó' },
            { word: 'where', translation: 'dónde' },
            { word: 'I', translation: 'yo' },
          ],
          after: [],
          answer: 'lived',
          hint: 'live',
          sentenceTranslation: '“¿Dónde vives?” → Preguntó dónde vivía.',
        },
      ],
    },
    {
      type: 'drag-and-drop',
      title: 'Ordena las palabras',
      instructions: 'Arrastra las palabras para formar la oración correcta. Las opciones aparecen en orden aleatorio.',
      questions: [
        {
          id: 16,
          tokens: [
            { id: 'q16-he', word: 'He', translation: 'él' },
            { id: 'q16-said', word: 'said', translation: 'dijo' },
            { id: 'q16-he-2', word: 'he', translation: 'él' },
            { id: 'q16-was', word: 'was', translation: 'estaba' },
            { id: 'q16-tired', word: 'tired.', translation: 'cansado' },
          ],
          correctOrder: ['q16-he', 'q16-said', 'q16-he-2', 'q16-was', 'q16-tired'],
          sentenceTranslation: 'Dijo que estaba cansado.',
        },
        {
          id: 17,
          tokens: [
            { id: 'q17-she', word: 'She', translation: 'ella' },
            { id: 'q17-said', word: 'said', translation: 'dijo' },
            { id: 'q17-she-2', word: 'she', translation: 'ella' },
            { id: 'q17-would', word: 'would', translation: 'llamaría' },
            { id: 'q17-call', word: 'call', translation: 'llamar' },
            { id: 'q17-me', word: 'me.', translation: 'me' },
          ],
          correctOrder: ['q17-she', 'q17-said', 'q17-she-2', 'q17-would', 'q17-call', 'q17-me'],
          sentenceTranslation: 'Dijo que me llamaría.',
        },
        {
          id: 18,
          tokens: [
            { id: 'q18-he', word: 'He', translation: 'él' },
            { id: 'q18-asked', word: 'asked', translation: 'preguntó' },
            { id: 'q18-if', word: 'if', translation: 'si' },
            { id: 'q18-i', word: 'I', translation: 'yo' },
            { id: 'q18-was', word: 'was', translation: 'estaba' },
            { id: 'q18-tired', word: 'tired.', translation: 'cansado' },
          ],
          correctOrder: ['q18-he', 'q18-asked', 'q18-if', 'q18-i', 'q18-was', 'q18-tired'],
          sentenceTranslation: 'Preguntó si yo estaba cansado.',
        },
        {
          id: 19,
          tokens: [
            { id: 'q19-she', word: 'She', translation: 'ella' },
            { id: 'q19-asked', word: 'asked', translation: 'preguntó' },
            { id: 'q19-where', word: 'where', translation: 'dónde' },
            { id: 'q19-i', word: 'I', translation: 'yo' },
            { id: 'q19-lived', word: 'lived.', translation: 'vivía' },
          ],
          correctOrder: ['q19-she', 'q19-asked', 'q19-where', 'q19-i', 'q19-lived'],
          sentenceTranslation: 'Preguntó dónde vivía.',
        },
        {
          id: 20,
          tokens: [
            { id: 'q20-he', word: 'He', translation: 'él' },
            { id: 'q20-told', word: 'told', translation: 'dijo' },
            { id: 'q20-me', word: 'me', translation: 'me' },
            { id: 'q20-to', word: 'to', translation: 'a' },
            { id: 'q20-sit', word: 'sit', translation: 'siéntate' },
            { id: 'q20-down', word: 'down.', translation: 'abajo' },
          ],
          correctOrder: ['q20-he', 'q20-told', 'q20-me', 'q20-to', 'q20-sit', 'q20-down'],
          sentenceTranslation: 'Me dijo que me sentara.',
        },
        {
          id: 21,
          tokens: [
            { id: 'q21-they', word: 'They', translation: 'ellos' },
            { id: 'q21-told', word: 'told', translation: 'dijo' },
            { id: 'q21-us', word: 'us', translation: 'nos' },
            { id: 'q21-not', word: 'not', translation: 'no' },
            { id: 'q21-to', word: 'to', translation: 'a' },
            { id: 'q21-touch', word: 'touch', translation: 'tocar' },
            { id: 'q21-anything', word: 'anything.', translation: 'nada' },
          ],
          correctOrder: ['q21-they', 'q21-told', 'q21-us', 'q21-not', 'q21-to', 'q21-touch', 'q21-anything'],
          sentenceTranslation: 'Nos dijeron que no tocáramos nada.',
        },
      ],
    },
    {
      type: 'listening-choice',
      title: '¿Qué dijo exactamente?',
      instructions: 'Escucha la oración en discurso indirecto y elige lo que la persona dijo exactamente.',
      questions: [
        {
          id: 22,
          audioText: 'She said she would call me.',
          language: 'en',
          prompt: '¿Qué dijo exactamente?',
          options: [
            { id: 'a', text: '“I will call you.”' },
            { id: 'b', text: '“I called you.”' },
          ],
          correctOptionIds: ['a'],
          explanation: 'would = will en el discurso directo.',
        },
        {
          id: 23,
          audioText: 'He said he had finished.',
          language: 'en',
          prompt: '¿Qué dijo exactamente?',
          options: [
            { id: 'a', text: '“I finished.”' },
            { id: 'b', text: '“I have finished.”' },
          ],
          correctOptionIds: ['b'],
          explanation: 'had finished viene de have finished (o past simple).',
        },
        {
          id: 24,
          audioText: 'She said she could swim.',
          language: 'en',
          prompt: '¿Qué dijo exactamente?',
          options: [
            { id: 'a', text: '“I can swim.”' },
            { id: 'b', text: '“I could swim.”' },
          ],
          correctOptionIds: ['a'],
          explanation: 'could = can en el discurso directo.',
        },
        {
          id: 25,
          audioText: 'He said he worked there.',
          language: 'en',
          prompt: '¿Qué dijo exactamente?',
          options: [
            { id: 'a', text: '“I work here.”' },
            { id: 'b', text: '“I worked here.”' },
          ],
          correctOptionIds: ['a'],
          explanation: 'worked = work; there = here.',
        },
        {
          id: 26,
          audioText: 'They said they were leaving the next day.',
          language: 'en',
          prompt: '¿Qué dijeron exactamente?',
          options: [
            { id: 'a', text: '“We are leaving tomorrow.”' },
            { id: 'b', text: '“We left yesterday.”' },
          ],
          correctOptionIds: ['a'],
          explanation: 'were leaving = are leaving; the next day = tomorrow.',
        },
      ],
    },
  ],
};

export default lessonB2016;
